// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/// camera manager object.
///
/// A pointer can be created using [`OH_Camera_GetCameraManager`] method.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
pub struct Camera_Manager {
    _unused: [u8; 0],
}
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_ErrorCode {
    /// Camera result is ok.
    pub const CAMERA_OK: Camera_ErrorCode = Camera_ErrorCode(0);
    /// Parameter missing or parameter type incorrect.
    pub const CAMERA_INVALID_ARGUMENT: Camera_ErrorCode = Camera_ErrorCode(7400101);
    /// Operation not allowed.
    pub const CAMERA_OPERATION_NOT_ALLOWED: Camera_ErrorCode = Camera_ErrorCode(7400102);
    /// Session not config.
    pub const CAMERA_SESSION_NOT_CONFIG: Camera_ErrorCode = Camera_ErrorCode(7400103);
    /// Session not running.
    pub const CAMERA_SESSION_NOT_RUNNING: Camera_ErrorCode = Camera_ErrorCode(7400104);
    /// Session config locked.
    pub const CAMERA_SESSION_CONFIG_LOCKED: Camera_ErrorCode = Camera_ErrorCode(7400105);
    /// Device setting locked.
    pub const CAMERA_DEVICE_SETTING_LOCKED: Camera_ErrorCode = Camera_ErrorCode(7400106);
    /// Can not use camera cause of conflict.
    pub const CAMERA_CONFLICT_CAMERA: Camera_ErrorCode = Camera_ErrorCode(7400107);
    /// Camera disabled cause of security reason.
    pub const CAMERA_DEVICE_DISABLED: Camera_ErrorCode = Camera_ErrorCode(7400108);
    /// Can not use camera cause of preempted.
    pub const CAMERA_DEVICE_PREEMPTED: Camera_ErrorCode = Camera_ErrorCode(7400109);
    /// Unresolved conflicts with current configurations.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const CAMERA_UNRESOLVED_CONFLICTS_WITH_CURRENT_CONFIGURATIONS: Camera_ErrorCode =
        Camera_ErrorCode(7400110);
    /// Camera service fatal error.
    pub const CAMERA_SERVICE_FATAL_ERROR: Camera_ErrorCode = Camera_ErrorCode(7400201);
}
#[repr(transparent)]
/// Enum for camera error code.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_ErrorCode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_Status {
    /// Appear status.
    pub const CAMERA_STATUS_APPEAR: Camera_Status = Camera_Status(0);
    /// Disappear status.
    pub const CAMERA_STATUS_DISAPPEAR: Camera_Status = Camera_Status(1);
    /// Available status.
    pub const CAMERA_STATUS_AVAILABLE: Camera_Status = Camera_Status(2);
    /// Unavailable status.
    pub const CAMERA_STATUS_UNAVAILABLE: Camera_Status = Camera_Status(3);
}
#[repr(transparent)]
/// Enum for camera status.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_Status(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl Camera_SceneMode {
    /// Normal photo mode.
    pub const NORMAL_PHOTO: Camera_SceneMode = Camera_SceneMode(1);
    /// Normal video mode.
    pub const NORMAL_VIDEO: Camera_SceneMode = Camera_SceneMode(2);
    /// Secure photo mode.
    pub const SECURE_PHOTO: Camera_SceneMode = Camera_SceneMode(12);
}
#[repr(transparent)]
/// Enum for scence mode.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_SceneMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_Position {
    /// Unspecified position.
    pub const CAMERA_POSITION_UNSPECIFIED: Camera_Position = Camera_Position(0);
    /// Back position.
    pub const CAMERA_POSITION_BACK: Camera_Position = Camera_Position(1);
    /// Front position.
    pub const CAMERA_POSITION_FRONT: Camera_Position = Camera_Position(2);
}
#[repr(transparent)]
/// Enum for camera position.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_Position(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_Type {
    /// Default camera type.
    pub const CAMERA_TYPE_DEFAULT: Camera_Type = Camera_Type(0);
    /// Wide camera.
    pub const CAMERA_TYPE_WIDE_ANGLE: Camera_Type = Camera_Type(1);
    /// Ultra wide camera.
    pub const CAMERA_TYPE_ULTRA_WIDE: Camera_Type = Camera_Type(2);
    /// Telephoto camera.
    pub const CAMERA_TYPE_TELEPHOTO: Camera_Type = Camera_Type(3);
    /// True depth camera.
    pub const CAMERA_TYPE_TRUE_DEPTH: Camera_Type = Camera_Type(4);
}
#[repr(transparent)]
/// Enum for camera type.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_Type(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_Connection {
    /// Built-in camera.
    pub const CAMERA_CONNECTION_BUILT_IN: Camera_Connection = Camera_Connection(0);
    /// Camera connected using USB.
    pub const CAMERA_CONNECTION_USB_PLUGIN: Camera_Connection = Camera_Connection(1);
    /// Remote camera.
    pub const CAMERA_CONNECTION_REMOTE: Camera_Connection = Camera_Connection(2);
}
#[repr(transparent)]
/// Enum for camera connection type.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_Connection(pub ::core::ffi::c_uint);
/// Describes the query information of the camera device.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_DeviceQueryInfo {
    /// Camera type list.
    pub cameraType: *mut Camera_Type,
    /// Camera type size.
    pub cameraTypeSize: u32,
    /// Camera position attribute.
    pub cameraPosition: Camera_Position,
    /// Camera connection type attribute.
    pub connectionType: Camera_Connection,
}
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_Format {
    /// RGBA 8888 Format.
    pub const CAMERA_FORMAT_RGBA_8888: Camera_Format = Camera_Format(3);
    /// YUV 420 Format.
    pub const CAMERA_FORMAT_YUV_420_SP: Camera_Format = Camera_Format(1003);
    /// JPEG Format.
    pub const CAMERA_FORMAT_JPEG: Camera_Format = Camera_Format(2000);
    /// YCBCR P010 Format.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const CAMERA_FORMAT_YCBCR_P010: Camera_Format = Camera_Format(2001);
    /// YCRCB P010 Format.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const CAMERA_FORMAT_YCRCB_P010: Camera_Format = Camera_Format(2002);
    /// HEIC Format.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_FORMAT_HEIC: Camera_Format = Camera_Format(2003);
}
#[repr(transparent)]
/// Enum for camera format type.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_Format(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_FlashMode {
    /// Close mode.
    pub const FLASH_MODE_CLOSE: Camera_FlashMode = Camera_FlashMode(0);
    /// Open mode.
    pub const FLASH_MODE_OPEN: Camera_FlashMode = Camera_FlashMode(1);
    /// Auto mode.
    pub const FLASH_MODE_AUTO: Camera_FlashMode = Camera_FlashMode(2);
    /// Always open mode.
    pub const FLASH_MODE_ALWAYS_OPEN: Camera_FlashMode = Camera_FlashMode(3);
}
#[repr(transparent)]
/// Enum for flash mode.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_FlashMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_ExposureMode {
    /// Lock exposure mode.
    pub const EXPOSURE_MODE_LOCKED: Camera_ExposureMode = Camera_ExposureMode(0);
    /// Auto exposure mode.
    pub const EXPOSURE_MODE_AUTO: Camera_ExposureMode = Camera_ExposureMode(1);
    /// Continuous automatic exposure.
    pub const EXPOSURE_MODE_CONTINUOUS_AUTO: Camera_ExposureMode = Camera_ExposureMode(2);
}
#[repr(transparent)]
/// Enum for exposure mode.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_ExposureMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_FocusMode {
    /// Manual mode.
    pub const FOCUS_MODE_MANUAL: Camera_FocusMode = Camera_FocusMode(0);
    /// Continuous auto mode.
    pub const FOCUS_MODE_CONTINUOUS_AUTO: Camera_FocusMode = Camera_FocusMode(1);
    /// Auto mode.
    pub const FOCUS_MODE_AUTO: Camera_FocusMode = Camera_FocusMode(2);
    /// Locked mode.
    pub const FOCUS_MODE_LOCKED: Camera_FocusMode = Camera_FocusMode(3);
}
#[repr(transparent)]
/// Enum for focus mode.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_FocusMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_FocusState {
    /// Scan state.
    pub const FOCUS_STATE_SCAN: Camera_FocusState = Camera_FocusState(0);
    /// Focused state.
    pub const FOCUS_STATE_FOCUSED: Camera_FocusState = Camera_FocusState(1);
    /// Unfocused state.
    pub const FOCUS_STATE_UNFOCUSED: Camera_FocusState = Camera_FocusState(2);
}
#[repr(transparent)]
/// Enum for focus state.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_FocusState(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_VideoStabilizationMode {
    /// Turn off video stablization.
    pub const STABILIZATION_MODE_OFF: Camera_VideoStabilizationMode =
        Camera_VideoStabilizationMode(0);
    /// LOW mode provides basic stabilization effect.
    pub const STABILIZATION_MODE_LOW: Camera_VideoStabilizationMode =
        Camera_VideoStabilizationMode(1);
    /// MIDDLE mode means algorithms can achieve better effects than LOW mode.
    pub const STABILIZATION_MODE_MIDDLE: Camera_VideoStabilizationMode =
        Camera_VideoStabilizationMode(2);
    /// HIGH mode means algorithms can achieve better effects than MIDDLE mode.
    pub const STABILIZATION_MODE_HIGH: Camera_VideoStabilizationMode =
        Camera_VideoStabilizationMode(3);
    /// Camera HDF can select mode automatically.
    pub const STABILIZATION_MODE_AUTO: Camera_VideoStabilizationMode =
        Camera_VideoStabilizationMode(4);
}
#[repr(transparent)]
/// Enum for video stabilization mode.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_VideoStabilizationMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_ImageRotation {
    /// The capture image rotates 0 degrees.
    pub const IAMGE_ROTATION_0: Camera_ImageRotation = Camera_ImageRotation(0);
    /// The capture image rotates 0 degrees.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_IMAGE_ROTATION_0: Camera_ImageRotation = Camera_ImageRotation(0);
    /// The capture image rotates 90 degrees.
    pub const IAMGE_ROTATION_90: Camera_ImageRotation = Camera_ImageRotation(90);
    /// The capture image rotates 90 degrees.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_IMAGE_ROTATION_90: Camera_ImageRotation = Camera_ImageRotation(90);
    /// The capture image rotates 180 degrees.
    pub const IAMGE_ROTATION_180: Camera_ImageRotation = Camera_ImageRotation(180);
    /// The capture image rotates 180 degrees.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_IMAGE_ROTATION_180: Camera_ImageRotation = Camera_ImageRotation(180);
    /// The capture image rotates 270 degrees.
    pub const IAMGE_ROTATION_270: Camera_ImageRotation = Camera_ImageRotation(270);
    /// The capture image rotates 270 degrees.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_IMAGE_ROTATION_270: Camera_ImageRotation = Camera_ImageRotation(270);
}
#[repr(transparent)]
/// Enum for the image rotation angles.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_ImageRotation(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_QualityLevel {
    /// High image quality.
    pub const QUALITY_LEVEL_HIGH: Camera_QualityLevel = Camera_QualityLevel(0);
    /// Medium image quality.
    pub const QUALITY_LEVEL_MEDIUM: Camera_QualityLevel = Camera_QualityLevel(1);
    /// Low image quality.
    pub const QUALITY_LEVEL_LOW: Camera_QualityLevel = Camera_QualityLevel(2);
}
#[repr(transparent)]
/// Enum for the image quality levels.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_QualityLevel(pub ::core::ffi::c_uint);
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
impl Camera_MetadataObjectType {
    /// Face detection.
    pub const FACE_DETECTION: Camera_MetadataObjectType = Camera_MetadataObjectType(0);
    /// Face detection type.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_METADATA_OBJECT_TYPE_FACE_DETECTION: Camera_MetadataObjectType =
        Camera_MetadataObjectType(0);
    /// Human body detection type.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_METADATA_OBJECT_TYPE_HUMAN_BODY: Camera_MetadataObjectType =
        Camera_MetadataObjectType(1);
}
#[repr(transparent)]
/// Enum for metadata object type.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_MetadataObjectType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl Camera_TorchMode {
    /// The device torch is always off.
    pub const OFF: Camera_TorchMode = Camera_TorchMode(0);
    /// The device torch is always off.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_TORCH_MODE_OFF: Camera_TorchMode = Camera_TorchMode(0);
    /// The device torch is always on.
    pub const ON: Camera_TorchMode = Camera_TorchMode(1);
    /// The device torch is always on.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_TORCH_MODE_ON: Camera_TorchMode = Camera_TorchMode(1);
    /// The device continuously monitors light levels and
    /// uses the torch when necessary.
    pub const AUTO: Camera_TorchMode = Camera_TorchMode(2);
    /// The device continuously monitors light levels and
    /// uses the torch when necessary.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_TORCH_MODE_AUTO: Camera_TorchMode = Camera_TorchMode(2);
}
#[repr(transparent)]
/// Enum for torch mode.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_TorchMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl Camera_SmoothZoomMode {
    /// Normal smooth zoom mode.
    pub const NORMAL: Camera_SmoothZoomMode = Camera_SmoothZoomMode(0);
    /// Normal smooth zoom mode.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_SMOOTH_ZOOM_MODE_NORMAL: Camera_SmoothZoomMode = Camera_SmoothZoomMode(0);
}
#[repr(transparent)]
/// Enum for smooth zoom mode.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_SmoothZoomMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl Camera_PreconfigType {
    /// The preconfig type is 720P.
    pub const PRECONFIG_720P: Camera_PreconfigType = Camera_PreconfigType(0);
    /// The preconfig type is 1080P.
    pub const PRECONFIG_1080P: Camera_PreconfigType = Camera_PreconfigType(1);
    /// The preconfig type is 4K.
    pub const PRECONFIG_4K: Camera_PreconfigType = Camera_PreconfigType(2);
    /// The preconfig type is high quality.
    pub const PRECONFIG_HIGH_QUALITY: Camera_PreconfigType = Camera_PreconfigType(3);
    /// The preconfig type is high quality photo session with BT2020.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const PRECONFIG_HIGH_QUALITY_PHOTOSESSION_BT2020: Camera_PreconfigType =
        Camera_PreconfigType(4);
}
#[repr(transparent)]
/// Enum for preconfig type.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_PreconfigType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl Camera_PreconfigRatio {
    /// The preconfig ratio is 1:1.
    pub const PRECONFIG_RATIO_1_1: Camera_PreconfigRatio = Camera_PreconfigRatio(0);
    /// The preconfig ratio 4:3.
    pub const PRECONFIG_RATIO_4_3: Camera_PreconfigRatio = Camera_PreconfigRatio(1);
    /// The preconfig ratio 16:9.
    pub const PRECONFIG_RATIO_16_9: Camera_PreconfigRatio = Camera_PreconfigRatio(2);
}
#[repr(transparent)]
/// Enum for preconfig ratio.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_PreconfigRatio(pub ::core::ffi::c_uint);
#[cfg(feature = "api-15")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-15")))]
impl Camera_HostDeviceType {
    /// Indicates an unknown device camera.
    pub const HOST_DEVICE_TYPE_UNKNOWN_TYPE: Camera_HostDeviceType = Camera_HostDeviceType(0);
    /// Indicates a smartphone camera.
    pub const HOST_DEVICE_TYPE_PHONE: Camera_HostDeviceType = Camera_HostDeviceType(14);
    /// Indicates tablet camera.
    pub const HOST_DEVICE_TYPE_TABLET: Camera_HostDeviceType = Camera_HostDeviceType(17);
}
#[repr(transparent)]
/// Enum for remote camera device type.
///
///
/// Available since API-level: 15
///
/// Version: 1.0
#[cfg(feature = "api-15")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-15")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_HostDeviceType(pub ::core::ffi::c_uint);
/// Size parameter.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_Size {
    /// Width.
    pub width: u32,
    /// Height.
    pub height: u32,
}
/// Profile for camera streams.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_Profile {
    /// Camera format.
    pub format: Camera_Format,
    /// Picture size.
    pub size: Camera_Size,
}
/// Frame rate range.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_FrameRateRange {
    /// Min frame rate.
    pub min: u32,
    /// Max frame rate.
    pub max: u32,
}
/// Video profile.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_VideoProfile {
    /// Camera format.
    pub format: Camera_Format,
    /// Picture size.
    pub size: Camera_Size,
    /// Frame rate in unit fps (frames per second).
    pub range: Camera_FrameRateRange,
}
/// Camera output capability.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_OutputCapability {
    /// Preview profiles list.
    pub previewProfiles: *mut *mut Camera_Profile,
    /// Size of preview profiles list.
    pub previewProfilesSize: u32,
    /// Photo profiles list.
    pub photoProfiles: *mut *mut Camera_Profile,
    /// Size of photo profiles list.
    pub photoProfilesSize: u32,
    /// Video profiles list.
    pub videoProfiles: *mut *mut Camera_VideoProfile,
    /// Size of video profiles list.
    pub videoProfilesSize: u32,
    /// Metadata object types list.
    pub supportedMetadataObjectTypes: *mut *mut Camera_MetadataObjectType,
    /// Size of metadata object types list.
    pub metadataProfilesSize: u32,
}
/// Camera device object.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_Device {
    /// Camera id attribute.
    pub cameraId: *mut ::core::ffi::c_char,
    /// Camera position attribute.
    pub cameraPosition: Camera_Position,
    /// Camera type attribute.
    pub cameraType: Camera_Type,
    /// Camera connection type attribute.
    pub connectionType: Camera_Connection,
}
/// Camera status info.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_StatusInfo {
    /// Camera instance.
    pub camera: *mut Camera_Device,
    /// Current camera status.
    pub status: Camera_Status,
}
/// Point parameter.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_Point {
    /// X co-ordinate.
    pub x: f64,
    /// Y co-ordinate.
    pub y: f64,
}
/// Photo capture location.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_Location {
    /// Latitude.
    pub latitude: f64,
    /// Longitude.
    pub longitude: f64,
    /// Altitude.
    pub altitude: f64,
}
/// Photo capture options to set.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_PhotoCaptureSetting {
    /// Photo image quality.
    pub quality: Camera_QualityLevel,
    /// Photo rotation.
    pub rotation: Camera_ImageRotation,
    /// Photo location.
    pub location: *mut Camera_Location,
    /// Set the mirror photo function switch, default to false.
    pub mirror: bool,
}
/// Frame shutter callback info.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_FrameShutterInfo {
    /// Capture id.
    pub captureId: i32,
    /// Timestamp for frame.
    pub timestamp: u64,
}
/// Capture end info.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_CaptureEndInfo {
    /// Capture id.
    pub captureId: i32,
    /// Frame count.
    pub frameCount: i64,
}
/// Rectangle definition.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_Rect {
    /// X coordinator of top left point.
    pub topLeftX: i32,
    /// Y coordinator of top left point.
    pub topLeftY: i32,
    /// Width of this rectangle.
    pub width: i32,
    /// Height of this rectangle.
    pub height: i32,
}
/// Metadata object basis.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_MetadataObject {
    /// Metadata object type.
    pub type_: Camera_MetadataObjectType,
    /// Metadata object timestamp in milliseconds.
    pub timestamp: i64,
    /// The axis-aligned bounding box of detected metadata object.
    pub boundingBox: *mut Camera_Rect,
}
/// Torch Status Info.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_TorchStatusInfo {
    /// is torch available.
    pub isTorchAvailable: bool,
    /// is torch active.
    pub isTorchActive: bool,
    /// the current torch brightness level.
    pub torchLevel: f32,
}
/// SmoothZoomInfo object.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_SmoothZoomInfo {
    /// The duration of smooth zoom.
    pub duration: i32,
}
/// Capture start info.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_CaptureStartInfo {
    /// Capture id.
    pub captureId: i32,
    /// Time(in milliseconds) is the shutter time for the photo.
    pub time: i64,
}
/// Frame shutter end callback info.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_FrameShutterEndInfo {
    /// Capture id.
    pub captureId: i32,
}
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
impl Camera_FoldStatus {
    /// Non_foldable status.
    pub const NON_FOLDABLE: Camera_FoldStatus = Camera_FoldStatus(0);
    /// Non_foldable status.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_FOLD_STATUS_NON_FOLDABLE: Camera_FoldStatus = Camera_FoldStatus(0);
    /// Expanded status.
    pub const EXPANDED: Camera_FoldStatus = Camera_FoldStatus(1);
    /// Expanded status.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_FOLD_STATUS_EXPANDED: Camera_FoldStatus = Camera_FoldStatus(1);
    /// Folded status.
    pub const FOLDED: Camera_FoldStatus = Camera_FoldStatus(2);
    /// Folded status.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const CAMERA_FOLD_STATUS_FOLDED: Camera_FoldStatus = Camera_FoldStatus(2);
}
#[repr(transparent)]
/// Enum for fold status.
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_FoldStatus(pub ::core::ffi::c_uint);
/// Fold status info.
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_FoldStatusInfo {
    /// Camera instance list.
    pub supportedCameras: *mut *mut Camera_Device,
    /// Size of camera list.
    pub cameraSize: u32,
    /// Current fold status.
    pub foldStatus: Camera_FoldStatus,
}
/// Auto device switch status info.
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_AutoDeviceSwitchStatusInfo {
    /// is device switched.
    pub isDeviceSwitched: bool,
    /// is device capability changed.
    pub isDeviceCapabilityChanged: bool,
}
#[cfg(feature = "api-14")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
impl Camera_QualityPrioritization {
    /// Hight quality priority.
    pub const HIGH_QUALITY: Camera_QualityPrioritization = Camera_QualityPrioritization(0);
    /// Power balance priority.
    pub const POWER_BALANCE: Camera_QualityPrioritization = Camera_QualityPrioritization(1);
}
#[repr(transparent)]
/// Enum for quality prioritization.
///
///
/// Available since API-level: 14
///
/// Version: 1.0
#[cfg(feature = "api-14")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_QualityPrioritization(pub ::core::ffi::c_uint);
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
impl Camera_ConcurrentType {
    /// Cameras concurrency with limited capability.
    pub const CAMERA_CONCURRENT_TYPE_LIMITED_CAPABILITY: Camera_ConcurrentType =
        Camera_ConcurrentType(0);
    /// Cameras concurrenct with full capability.
    pub const CAMERA_CONCURRENT_TYPE_FULL_CAPABILITY: Camera_ConcurrentType =
        Camera_ConcurrentType(1);
}
#[repr(transparent)]
/// Enum for camera concurrent type.
///
///
/// Available since API-level: 18
///
/// Version: 1.0
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_ConcurrentType(pub ::core::ffi::c_uint);
/// Concurrency capability infos.
///
///
/// Available since API-level: 18
///
/// Version: 1.0
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_ConcurrentInfo {
    /// Camera instance.
    pub camera: Camera_Device,
    /// Supported concurrent type.
    pub type_: Camera_ConcurrentType,
    /// Supported Modes.
    pub sceneModes: *mut Camera_SceneMode,
    /// Supported outputCapabilities
    pub outputCapabilities: *mut Camera_OutputCapability,
    /// Supported outputCapabilities size.
    pub modeAndCapabilitySize: u32,
}
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
impl Camera_WhiteBalanceMode {
    /// Automatic white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_AUTO: Camera_WhiteBalanceMode = Camera_WhiteBalanceMode(0);
    /// Cloudy white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_CLOUDY: Camera_WhiteBalanceMode =
        Camera_WhiteBalanceMode(1);
    /// Incandescent white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_INCANDESCENT: Camera_WhiteBalanceMode =
        Camera_WhiteBalanceMode(2);
    /// Fluorescent white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_FLUORESCENT: Camera_WhiteBalanceMode =
        Camera_WhiteBalanceMode(3);
    /// Daylight white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_DAYLIGHT: Camera_WhiteBalanceMode =
        Camera_WhiteBalanceMode(4);
    /// Manual white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_MANUAL: Camera_WhiteBalanceMode =
        Camera_WhiteBalanceMode(5);
    /// Lock white balance mode.
    pub const CAMERA_WHITE_BALANCE_MODE_LOCKED: Camera_WhiteBalanceMode =
        Camera_WhiteBalanceMode(6);
}
#[repr(transparent)]
/// Enumerates the white balance modes.
///
///
/// Available since API-level: 20
///
/// Version: 1.0
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_WhiteBalanceMode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
impl Camera_SystemPressureLevel {
    /// Normal level. This level indicates the system pressure is normal.
    pub const SYSTEM_PRESSURE_NORMAL: Camera_SystemPressureLevel = Camera_SystemPressureLevel(0);
    /// Mild level. This level indicates the system pressure is slightly elevated.
    pub const SYSTEM_PRESSURE_MILD: Camera_SystemPressureLevel = Camera_SystemPressureLevel(1);
    /// Severe level. This level indicates the system pressure is severely elevated.
    pub const SYSTEM_PRESSURE_SEVERE: Camera_SystemPressureLevel = Camera_SystemPressureLevel(2);
    /// Critical level. This level indicates the system pressure is critically elevated.
    pub const SYSTEM_PRESSURE_CRITICAL: Camera_SystemPressureLevel = Camera_SystemPressureLevel(3);
    /// Shutdown level. This level indicates the system pressure is fatal, so the camera session will be shut down soon.
    pub const SYSTEM_PRESSURE_SHUTDOWN: Camera_SystemPressureLevel = Camera_SystemPressureLevel(4);
}
#[repr(transparent)]
/// Enumerates the system pressure levels of the current camera session. When the system pressure
/// increases, you are advised to reduce the load of the current camera session.
///
///
/// Available since API-level: 20
///
/// Version: 1.0
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_SystemPressureLevel(pub ::core::ffi::c_uint);
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
impl Camera_ControlCenterEffectType {
    /// Control center beauty effect type.
    pub const CONTROL_CENTER_EFFECT_TYPE_BEAUTY: Camera_ControlCenterEffectType =
        Camera_ControlCenterEffectType(0);
    /// Control center portrait effect type.
    pub const CONTROL_CENTER_EFFECT_TYPE_PORTRAIT: Camera_ControlCenterEffectType =
        Camera_ControlCenterEffectType(1);
}
#[repr(transparent)]
/// Enumerates the control center effect types.
///
///
/// Available since API-level: 20
///
/// Version: 1.0
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_ControlCenterEffectType(pub ::core::ffi::c_uint);
/// Control center status info.
///
///
/// Available since API-level: 20
///
/// Version: 1.0
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_ControlCenterStatusInfo {
    /// Control center effect type.
    pub effectType: Camera_ControlCenterEffectType,
    /// If control center effect is active.
    pub isActive: bool,
}
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
impl Camera_PhotoQualityPrioritization {
    /// High quality photos are the top preference, even at the expense of shot-to-shot time.
    pub const CAMERA_PHOTO_QUALITY_PRIORITIZATION_HIGH_QUALITY: Camera_PhotoQualityPrioritization =
        Camera_PhotoQualityPrioritization(0);
    /// Prefering speed over quality, even at the expense of quality.
    pub const CAMERA_PHOTO_QUALITY_PRIORITIZATION_SPEED: Camera_PhotoQualityPrioritization =
        Camera_PhotoQualityPrioritization(1);
}
#[repr(transparent)]
/// Enum for photo quality prioritization.
///
///
/// Available since API-level: 21
///
/// Version: 1.0
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Camera_PhotoQualityPrioritization(pub ::core::ffi::c_uint);
/// Camera occlusion detection result.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Camera_OcclusionDetectionResult {
    /// Check whether camera is occluded.
    pub isCameraOccluded: bool,
    /// Check whether camera lens is dirty.
    pub isCameraLensDirty: bool,
}
extern "C" {
    /// Creates a CameraManager instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the output [`Camera_Manager`] cameraManager will be created
    /// if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_Camera_GetCameraManager(cameraManager: *mut *mut Camera_Manager) -> Camera_ErrorCode;
    /// Delete the CameraManager instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] cameraManager instance to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_Camera_DeleteCameraManager(cameraManager: *mut Camera_Manager) -> Camera_ErrorCode;
}
