// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::queue::*;
use crate::type_def::*;

/// Defines the loop handle, which identifies different loops.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type ffrt_loop_t = *mut ::core::ffi::c_void;
extern "C" {
    /// Creates a loop.
    ///
    /// # Arguments
    ///
    /// * `queue` - Indicates a queue.
    ///
    /// # Returns
    ///
    /// * Returns a non-null loop handle if the loop is created;
    /// returns a null pointer otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_create(queue: ffrt_queue_t) -> ffrt_loop_t;
    /// Destroys a loop, the user needs to invoke this interface.
    ///
    /// # Arguments
    ///
    /// * `loop` - Indicates a loop handle.
    ///
    /// # Returns
    ///
    /// * Returns 0 if the loop is destroyed;
    /// returns -1 otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_destroy(loop_: ffrt_loop_t) -> ::core::ffi::c_int;
    /// Starts a loop run.
    ///
    /// # Arguments
    ///
    /// * `loop` - Indicates a loop handle.
    ///
    /// # Returns
    ///
    /// * Returns -1 if loop run fail;
    /// returns 0 otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_run(loop_: ffrt_loop_t) -> ::core::ffi::c_int;
    /// Stops a loop run.
    ///
    /// # Arguments
    ///
    /// * `loop` - Indicates a loop handle.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_stop(loop_: ffrt_loop_t);
    /// Controls an epoll file descriptor on ffrt loop.
    ///
    /// Do not call `exit` in `cb` - this may cause unexpected behavior.
    ///
    /// # Arguments
    ///
    /// * `loop` - Indicates a loop handle.
    ///
    /// * `op` - Indicates operation on the target file descriptor.
    ///
    /// * `fd` - Indicates the target file descriptor on which to perform the operation.
    ///
    /// * `events` - Indicates the event type associated with the target file descriptor.
    ///
    /// * `data` - Indicates user data used in cb.
    ///
    /// * `cb` - Indicates user cb which will be executed when the target fd is polled.
    ///
    /// # Returns
    ///
    /// * Returns 0 if success;
    /// returns -1 otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_epoll_ctl(
        loop_: ffrt_loop_t,
        op: ::core::ffi::c_int,
        fd: ::core::ffi::c_int,
        events: u32,
        data: *mut ::core::ffi::c_void,
        cb: ffrt_poller_cb,
    ) -> ::core::ffi::c_int;
    /// Starts a timer on ffrt loop.
    ///
    /// Do not call `exit` in `cb` - this may cause unexpected behavior.
    /// # Arguments
    ///
    /// * `loop` - Indicates a loop handle.
    ///
    /// * `timeout` - Indicates the number of milliseconds that specifies timeout.
    ///
    /// * `data` - Indicates user data used in cb.
    ///
    /// * `cb` - Indicates user cb which will be executed when timeout.
    ///
    /// * `repeat` - Indicates whether to repeat this timer.
    ///
    /// # Returns
    ///
    /// * Returns a timer handle.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_timer_start(
        loop_: ffrt_loop_t,
        timeout: u64,
        data: *mut ::core::ffi::c_void,
        cb: ffrt_timer_cb,
        repeat: bool,
    ) -> ffrt_timer_t;
    /// Stops a timer on ffrt loop.
    ///
    /// # Arguments
    ///
    /// * `loop` - Indicates a loop handle.
    ///
    /// * `handle` - Indicates the target timer handle.
    ///
    /// # Returns
    ///
    /// * Returns 0 if success;
    /// returns -1 otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_loop_timer_stop(loop_: ffrt_loop_t, handle: ffrt_timer_t) -> ::core::ffi::c_int;
}
