// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::camera::*;

/// Metadata output object
///
/// A pointer can be created using [`Camera_MetadataOutput`] method.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
pub struct Camera_MetadataOutput {
    _unused: [u8; 0],
}
/// Metadata output metadata object available callback to be called in [`MetadataOutput_Callbacks`].
///
/// # Arguments
///
/// * `metadataOutput` - the [`Camera_MetadataOutput`] which deliver the callback.
///
/// * `metadataObject` - the [`Camera_MetadataObject`] will be delivered by the callback.
///
/// * `size` - the size of the metadataObject.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_MetadataOutput_OnMetadataObjectAvailable = ::core::option::Option<
    unsafe extern "C" fn(
        metadataOutput: *mut Camera_MetadataOutput,
        metadataObject: *mut Camera_MetadataObject,
        size: u32,
    ),
>;
/// Metadata output error callback to be called in [`MetadataOutput_Callbacks`].
///
/// # Arguments
///
/// * `metadataOutput` - the [`Camera_MetadataOutput`] which deliver the callback.
///
/// * `errorCode` - the [`Camera_ErrorCode`] of the metadata output.
///
/// [`CAMERA_SERVICE_FATAL_ERROR`]
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_MetadataOutput_OnError = ::core::option::Option<
    unsafe extern "C" fn(metadataOutput: *mut Camera_MetadataOutput, errorCode: Camera_ErrorCode),
>;
/// A listener for metadata output.
///
/// [`OH_MetadataOutput_RegisterCallback`]
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MetadataOutput_Callbacks {
    /// Metadata output result data will be called by this callback.
    pub onMetadataObjectAvailable: OH_MetadataOutput_OnMetadataObjectAvailable,
    /// Metadata output error event.
    pub onError: OH_MetadataOutput_OnError,
}
extern "C" {
    /// Register metadata output change event callback.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance.
    ///
    /// * `callback` - the [`MetadataOutput_Callbacks`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_MetadataOutput_RegisterCallback(
        metadataOutput: *mut Camera_MetadataOutput,
        callback: *mut MetadataOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Unregister metadata output change event callback.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance.
    ///
    /// * `callback` - the [`MetadataOutput_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_MetadataOutput_UnregisterCallback(
        metadataOutput: *mut Camera_MetadataOutput,
        callback: *mut MetadataOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Start metadata output.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance to be started.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SESSION_NOT_CONFIG`] if the capture session not config.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_MetadataOutput_Start(metadataOutput: *mut Camera_MetadataOutput) -> Camera_ErrorCode;
    /// Stop metadata output.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance to be stoped.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_MetadataOutput_Stop(metadataOutput: *mut Camera_MetadataOutput) -> Camera_ErrorCode;
    /// Release metadata output.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance to be released.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_MetadataOutput_Release(
        metadataOutput: *mut Camera_MetadataOutput,
    ) -> Camera_ErrorCode;
    /// add metadata object types.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance.
    ///
    /// * `types` - the target [`Camera_MetadataObjectType`] to add.
    ///
    /// * `size` - the size of the metadata Object types.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_MetadataOutput_AddMetadataObjectTypes(
        metadataOutput: *mut Camera_MetadataOutput,
        types: *mut Camera_MetadataObjectType,
        size: u32,
    ) -> Camera_ErrorCode;
    /// remove metadata object types.
    ///
    /// # Arguments
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] instance.
    ///
    /// * `types` - the target [`Camera_MetadataObjectType`] to remove.
    ///
    /// * `size` - the size of the metadata Object types.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_MetadataOutput_RemoveMetadataObjectTypes(
        metadataOutput: *mut Camera_MetadataOutput,
        types: *mut Camera_MetadataObjectType,
        size: u32,
    ) -> Camera_ErrorCode;
}
