// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::environment::error_code::FileManagementResult;

#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl FileIO_FileLocation {
    /// Indicates the file located on the local.
    pub const LOCAL: FileIO_FileLocation = FileIO_FileLocation(1);
    /// Indicates the file located on the cloud.
    pub const CLOUD: FileIO_FileLocation = FileIO_FileLocation(2);
    /// Indicates the file located on the local and cloud.
    pub const LOCAL_AND_CLOUD: FileIO_FileLocation = FileIO_FileLocation(3);
}
#[repr(transparent)]
/// Enumerates the file location.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct FileIO_FileLocation(pub ::core::ffi::c_uint);
extern "C" {
    /// Get the file location.
    ///
    /// # Arguments
    ///
    /// * `uri` - Input a pointer to a uri.
    ///
    /// * `uriLength` - Input the length of the uri.
    ///
    /// * `location` - Output the result of file location.
    ///
    /// # Returns
    ///
    /// * Return the status code of the execution.
    /// [`ERR_INVALID_PARAMETER`] 401 - Invalid input parameter, pointer is null.
    /// [`ERR_ENOENT`] 13900002 - No such file or directory.
    /// [`ERR_ENOMEM`] 13900011 - Failed to apply for memory.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_FileIO_GetFileLocation(
        uri: *mut ::core::ffi::c_char,
        uriLength: ::core::ffi::c_int,
        location: *mut FileIO_FileLocation,
    ) -> FileManagementResult;
}
