[package]
name = "ohos-purgeable-memory-sys"
version = "0.1.0"
edition = "2021"
keywords = ["OpenHarmony", "HarmonyOS", "purgeable", "memory", "reclaimable"]
license = "Apache-2.0"
description = "Bindings to the PurgeableMemory (purgeable/reclaimable memory) API of OpenHarmony"
repository = "https://github.com/openharmony-rs/ohos-sys"
readme = "README.md"
include = ["/src"]

[dependencies]
document-features = { version = "0.2", optional = true }

[features]
default = []

## Enables bindings for OpenHarmony API-level 10. This is the lowest API level
## at which any PurgeableMemory APIs are available — selecting this feature is required to
## use the purgeable memory APIs.
api-10 = []
api-11 = ["api-10"]
api-12 = ["api-11"]
api-13 = ["api-12"]
api-14 = ["api-13"]
api-15 = ["api-14"]
api-16 = ["api-15"]
api-17 = ["api-16"]
api-18 = ["api-17"]
api-19 = ["api-18"]
api-20 = ["api-19"]
api-21 = ["api-20"]
api-22 = ["api-21"]
api-23 = ["api-22"]
## Document available features when building the documentation
document-features = ["dep:document-features"]

[package.metadata.docs.rs]
features = ["document-features"]
targets = ["aarch64-unknown-linux-ohos", "armv7-unknown-linux-ohos", "x86_64-unknown-linux-ohos"]
all-features = true
