// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

extern "C" {
    /// Obtains the default cellular data slot id.
    ///
    ///
    /// # Returns
    ///
    /// * the default cellular data slot id (0 for slot 1, 1 for slot 2).
    ///
    /// Required System Capabilities: SystemCapability.Telephony.CellularData
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_Telephony_GetDefaultCellularDataSlotId() -> i32;
}
