// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::environment::error_code::FileManagementResult;

extern "C" {
    /// Get uri From path.
    ///
    /// # Arguments
    ///
    /// * `path` - Input a pointer to the path string.
    ///
    /// * `length` - The length of the input path.
    ///
    /// * `result` - Output a pointer to a uri string. Please use free() to clear the resource.
    ///
    /// # Returns
    ///
    /// * Returns the status code of the execution.
    /// [`ERR_INVALID_PARAMETER`] 401 - Invalid input parameter.
    /// [`ERR_UNKNOWN`] 13900042 - Unknow error. The length of the output uri string is 0.
    /// [`ERR_ENOMEM`] 13900011 - Failed to apply for memory or failed to copy memory.
    /// [`ERR_OK`] 0 - This operation was successfully executed.
    ///
    /// Required System Capabilities: SystemCapability.FileManagement.AppFileService
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_FileUri_GetUriFromPath(
        path: *const ::core::ffi::c_char,
        length: ::core::ffi::c_uint,
        result: *mut *mut ::core::ffi::c_char,
    ) -> FileManagementResult;
    /// Get path From uri.
    ///
    /// # Arguments
    ///
    /// * `uri` - Input a pointer to the uri string.
    ///
    /// * `length` - The length of the input uri.
    ///
    /// * `result` - Output a pointer to a path string. Please use free() to clear the resource.
    ///
    /// # Returns
    ///
    /// * Returns the status code of the execution.
    /// [`ERR_INVALID_PARAMETER`] 401 - Invalid input parameter.
    /// [`ERR_UNKNOWN`] 13900042 - Unknow error. The length of the output path string is 0.
    /// [`ERR_ENOMEM`] 13900011 - Failed to apply for memory or failed to copy memory.
    /// [`ERR_OK`] 0 - This operation was successfully executed.
    ///
    /// Required System Capabilities: SystemCapability.FileManagement.AppFileService
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_FileUri_GetPathFromUri(
        uri: *const ::core::ffi::c_char,
        length: ::core::ffi::c_uint,
        result: *mut *mut ::core::ffi::c_char,
    ) -> FileManagementResult;
    /// Gets the uri of the path or directory where the uri is located.
    ///
    /// # Arguments
    ///
    /// * `uri` - Input a pointer to the uri string.
    ///
    /// * `length` - The length of the input uri.
    ///
    /// * `result` - Output a pointer to a uri string. Please use free() to clear the resource.
    ///
    /// # Returns
    ///
    /// * Returns the status code of the execution.
    /// [`ERR_INVALID_PARAMETER`] 401 - Invalid input parameter.
    /// [`ERR_ENOMEM`] 13900011 - Failed to apply for memory or failed to copy memory.
    /// [`ERR_ENOENT`] 13900002 - No such file or directory.
    /// [`ERR_UNKNOWN`] 13900042 - Unknow error. The length of the output path string is 0.
    /// [`ERR_OK`] 0 - This operation was successfully executed.
    ///
    /// Required System Capabilities: SystemCapability.FileManagement.AppFileService
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_FileUri_GetFullDirectoryUri(
        uri: *const ::core::ffi::c_char,
        length: ::core::ffi::c_uint,
        result: *mut *mut ::core::ffi::c_char,
    ) -> FileManagementResult;
    /// Check that the incoming uri is valid
    ///
    /// # Arguments
    ///
    /// * `uri` - Input a pointer to the uri string.
    ///
    /// * `length` - The length of the input uri.
    ///
    /// # Returns
    ///
    /// * Returns true: Valid incoming uri, false: Invalid incoming uri.
    ///
    /// Required System Capabilities: SystemCapability.FileManagement.AppFileService
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_FileUri_IsValidUri(
        uri: *const ::core::ffi::c_char,
        length: ::core::ffi::c_uint,
    ) -> bool;
    /// Gets the fileName From uri.
    /// This function obtains that the last segment of the URI string is the return value of the function,
    /// and the URI of the media type is not supported
    /// # Arguments
    ///
    /// * `uri` - Input a pointer to the uri string.
    ///
    /// * `length` - The length of the input uri.
    ///
    /// * `result` - Output a pointer to a FileName string. Please use free() to clear the resource.
    ///
    /// # Returns
    ///
    /// * Returns the status code of the execution.
    /// [`ERR_INVALID_PARAMETER`] 401 - Invalid input parameter.
    /// [`ERR_ENOMEM`] 13900011 - Failed to apply for memory or failed to copy memory.
    /// [`ERR_OK`] 0 - This operation was successfully executed.
    ///
    /// Required System Capabilities: SystemCapability.FileManagement.AppFileService
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_FileUri_GetFileName(
        uri: *const ::core::ffi::c_char,
        length: ::core::ffi::c_uint,
        result: *mut *mut ::core::ffi::c_char,
    ) -> FileManagementResult;
}
