// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/// Defines the native displaySoloist struct.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_DisplaySoloist {
    _unused: [u8; 0],
}
/// Defines the native displaySoloist callback.
///
/// # Arguments
///
/// * `timestamp` - Indicates the current timestamp.
///
/// * `targetTimestamp` - Indicates the target timestamp.
///
/// * `data` - Indicates the pointer to user data.
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_DisplaySoloist_FrameCallback = ::core::option::Option<
    unsafe extern "C" fn(
        timestamp: ::core::ffi::c_longlong,
        targetTimestamp: ::core::ffi::c_longlong,
        data: *mut ::core::ffi::c_void,
    ),
>;
/// Defines the expected frame rate range struct.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DisplaySoloist_ExpectedRateRange {
    /// The minimum frame rate of dynamical callback rate range.
    pub min: i32,
    /// The maximum frame rate of dynamical callback rate range.
    pub max: i32,
    /// The expected frame rate of dynamical callback rate range.
    pub expected: i32,
}
extern "C" {
    /// Creates a <b>OH_DisplaySoloist</b> instance.
    ///
    ///
    /// # Arguments
    ///
    /// * `useExclusiveThread` - Indicates whether the vsync run in a exclusive thread.
    ///
    /// # Returns
    ///
    /// * Returns the pointer to the <b>OH_DisplaySoloist</b> instance created if the execution is successful.
    /// if nullptr is returned, the creation fails.
    /// the possible cause of the failure is that the available memory is empty.
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_DisplaySoloist_Create(useExclusiveThread: bool) -> *mut OH_DisplaySoloist;
    /// Destroys a <b>OH_DisplaySoloist</b> instance and reclaims the memory occupied by the object.
    ///
    /// # Arguments
    ///
    /// * `displaySoloist` - Indicates the pointer to a native displaySoloist.
    ///
    /// # Returns
    ///
    /// * Returns int32_t, returns 0 if the execution is successful, returns -1 if displaySoloist is incorrect.
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_DisplaySoloist_Destroy(displaySoloist: *mut OH_DisplaySoloist) -> i32;
    /// Start to request next vsync with callback.
    ///
    /// # Arguments
    ///
    /// * `displaySoloist` - Indicates the pointer to a native displaySoloist.
    ///
    /// * `callback` - Indicates the OH_DisplaySoloist_FrameCallback which will be called when next vsync coming.
    ///
    /// * `data` - Indicates data whick will be used in callback.
    ///
    /// # Returns
    ///
    /// * Returns int32_t, returns 0 if the execution is successful.
    /// returns -1 if displaySoloist or callback is incorrect.
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_DisplaySoloist_Start(
        displaySoloist: *mut OH_DisplaySoloist,
        callback: OH_DisplaySoloist_FrameCallback,
        data: *mut ::core::ffi::c_void,
    ) -> i32;
    /// Stop to request next vsync with callback.
    ///
    /// # Arguments
    ///
    /// * `displaySoloist` - Indicates the pointer to a native displaySoloist.
    ///
    /// # Returns
    ///
    /// * Returns int32_t, returns 0 if the execution is successful, returns -1 if displaySoloist is incorrect.
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_DisplaySoloist_Stop(displaySoloist: *mut OH_DisplaySoloist) -> i32;
    /// Set vsync expected frame rate range.
    ///
    /// # Arguments
    ///
    /// * `displaySoloist` - Indicates the pointer to a native displaySoloist.
    ///
    /// * `range` - Indicates the pointer to an expected rate range.
    ///
    /// # Returns
    ///
    /// * Returns int32_t, returns 0 if the execution is successful
    /// returns -1 if displaySoloist or range is incorrect.
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_DisplaySoloist_SetExpectedFrameRateRange(
        displaySoloist: *mut OH_DisplaySoloist,
        range: *mut DisplaySoloist_ExpectedRateRange,
    ) -> i32;
}
