// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::avsession_errors::AVQueueItem_Result;

/// Declaring the AVMediaDescription.
/// The instance of AVMediaDescription set by application for current resource.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVSession_AVMediaDescription {
    _unused: [u8; 0],
}
/// Declaring the avqueue item.
/// The instance of AVQueueItem.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OH_AVSession_AVQueueItem {
    /// itemId.
    pub itemId: u32,
    /// media item info.
    pub description: *mut OH_AVSession_AVMediaDescription,
}
/// Declaring the AVMediaDescription builder.
/// The instance of builder is used for creating AVMediaDescription.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVSession_AVMediaDescriptionBuilder {
    _unused: [u8; 0],
}
extern "C" {
    /// Creates an OH_AVSession_AVMediaDescriptionBuilder instance.
    /// Call [`OH_AVSession_AVMediaDescriptionBuilder_Destroy`] to release the builder object
    /// when it is not used anymore.
    ///
    /// # Arguments
    ///
    /// * `builder` - The builder reference to the created result.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`] The param of builder is nullptr.
    /// [`AVQUEUEITEM_ERROR_NO_MEMORY`] No memory to allocate a new instance.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_Create(
        builder: *mut *mut OH_AVSession_AVMediaDescriptionBuilder,
    ) -> AVQueueItem_Result;
    /// Destroy a builder.
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`] The param of builder is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_Destroy(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
    ) -> AVQueueItem_Result;
    /// Set current asset id of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `assetId` - The current assetId of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of assetId is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetAssetId(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        assetId: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the title of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `title` - The title of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of title is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetTitle(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        title: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the subtitle of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `subtitle` - The subtitle of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of subtitle is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetSubTitle(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        subtitle: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the artist of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `artist` - The artist of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of artist is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetArtist(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        artist: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the media image url of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `albumCoverUri` - The image url of resource use to display in media center.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of albumCoverUri is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetAlbumCoverUri(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        albumCoverUri: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the media type of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `mediaType` - The type of this resource, such as VIDEO or AUDIO, which is capital.
    ///
    /// # Returns
    ///
    /// * Return code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of mediaType is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetMediaType(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        mediaType: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the lyric content of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `lyricContent` - The lyricContent of resource, it should be lrc format.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of lyricContent is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetLyricContent(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        lyricContent: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the duration of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `duration` - The duration of resource, in miliseconds
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of duration is invalid.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetDuration(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        duration: i32,
    ) -> AVQueueItem_Result;
    /// Set the media uri of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `mediaUri` - The media uri of the resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of mediaUri nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetMediaUri(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        mediaUri: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the start position of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `startPosition` - The start position of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of startPosition is invalid.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetStartPosition(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        startPosition: i32,
    ) -> AVQueueItem_Result;
    /// Set the size of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `mediaSize` - The size of the resource.
    ///
    /// # Returns
    ///
    /// * Return code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of mediaSize is invalid.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetMediaSize(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        mediaSize: i32,
    ) -> AVQueueItem_Result;
    /// Set the album title of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `albumTitle` - The album title of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr.
    /// 2.The param of albumTitle is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetAlbumTitle(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        albumTitle: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Set the app name of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `appName` - The app name of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr.
    /// 2.The param of title is appName.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_SetAppName(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        appName: *const ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get current asset id of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `assetId` - Pointer variable that will be set assetId.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of assetId is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetAssetId(
        description: *mut OH_AVSession_AVMediaDescription,
        assetId: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the title of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `title` - Pointer variable that will be set title.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of title is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetTitle(
        description: *mut OH_AVSession_AVMediaDescription,
        title: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the subtitle of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `subtitle` - Pointer variable that will be set subtitle.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of subtitle is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetSubtitle(
        description: *mut OH_AVSession_AVMediaDescription,
        subtitle: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the artist of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `artist` - Pointer variable that will be set artist.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of artist is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetArtist(
        description: *mut OH_AVSession_AVMediaDescription,
        artist: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the media image url of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `albumCoverUri` - Pointer variable that will be set to media image url.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of albumCoverUri is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetAlbumCoverUri(
        description: *mut OH_AVSession_AVMediaDescription,
        albumCoverUri: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the media type information
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `mediaType` - Pointer variable that will be set media type.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of mediaType is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetMediaType(
        description: *mut OH_AVSession_AVMediaDescription,
        mediaType: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the lyric content of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `lyricContent` - Pointer variable that will be set lyric content.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of lyricContent is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetLyricContent(
        description: *mut OH_AVSession_AVMediaDescription,
        lyricContent: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the duration of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `duration` - Pointer variable that will be set duration of the resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]
    /// 1. The param of builder is nullptr.
    /// 2. The param of duration is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetDuration(
        description: *mut OH_AVSession_AVMediaDescription,
        duration: *mut i32,
    ) -> AVQueueItem_Result;
    /// Get the media uri of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `mediaUri` - Pointer variable that will be set media uri.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of mediaUri is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetMediaUri(
        description: *mut OH_AVSession_AVMediaDescription,
        mediaUri: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get start position of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `startPosition` - Pointer variable that will be set start position of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]
    /// 1. The param of description is nullptr.
    /// 2. The param of startPosition is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetStartPosition(
        description: *mut OH_AVSession_AVMediaDescription,
        startPosition: *mut i32,
    ) -> AVQueueItem_Result;
    /// Get media size of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `mediaSize` - Pointer variable that will be set media size of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]
    /// 1. The param of description is nullptr.
    /// 2. The param of mediaSize is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetMediaSize(
        description: *mut OH_AVSession_AVMediaDescription,
        mediaSize: *mut i32,
    ) -> AVQueueItem_Result;
    /// Get the album title of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `albumTitle` - Pointer variable that will be set album title of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of albumTitle is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetAlbumTitle(
        description: *mut OH_AVSession_AVMediaDescription,
        albumTitle: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Get the app name of the resource
    ///
    /// # Arguments
    ///
    /// * `description` - The AVMediaDescription instance pointer
    ///
    /// * `appName` - Pointer variable that will be set to app name of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of description is nullptr.
    /// 2.The param of appName is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_GetAppName(
        description: *mut OH_AVSession_AVMediaDescription,
        appName: *mut *mut ::core::ffi::c_char,
    ) -> AVQueueItem_Result;
    /// Create the avMediaDescription.
    /// Call [`OH_AVSession_AVMediaDescription_Destroy`] to release the avMediaDescription object
    /// when it is not used anymore.
    ///
    /// # Arguments
    ///
    /// * `builder` - The AVMediaDescription builder instance pointer
    ///
    /// * `avMediaDescription` - Pointer to a variable to receive the avMediaDescription object.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_NO_MEMORY`] No memory to allocate a new instance.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of avMediaDescription is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescriptionBuilder_GenerateAVMediaDescription(
        builder: *mut OH_AVSession_AVMediaDescriptionBuilder,
        avMediaDescription: *mut *mut OH_AVSession_AVMediaDescription,
    ) -> AVQueueItem_Result;
    /// Request to release the avMediaDescription.
    ///
    /// # Arguments
    ///
    /// * `avMediaDescription` - Pointer to a viriable to receive the avMediaDescription object.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVQUEUEITEM_SUCCESS`] If the execution is successful.
    /// [`AVQUEUEITEM_ERROR_INVALID_PARAM`] The param of avMediaDescription is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AVMediaDescription_Destroy(
        avMediaDescription: *mut OH_AVSession_AVMediaDescription,
    ) -> AVQueueItem_Result;
}
