// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub struct OH_PixelmapNative;

/// Defines a effect filter.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_Filter {
    _unused: [u8; 0],
}
/// Defines a matrix for create effect filter.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OH_Filter_ColorMatrix {
    /// val mast be 5*4
    pub val: [f32; 20usize],
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl EffectErrorCode {
    /// success
    pub const EFFECT_SUCCESS: EffectErrorCode = EffectErrorCode(0);
    /// invalid parameter
    pub const EFFECT_BAD_PARAMETER: EffectErrorCode = EffectErrorCode(401);
    /// unsupported operations
    pub const EFFECT_UNSUPPORTED_OPERATION: EffectErrorCode = EffectErrorCode(7600201);
    /// unknown error
    pub const EFFECT_UNKNOWN_ERROR: EffectErrorCode = EffectErrorCode(7600901);
}
#[repr(transparent)]
/// Defines a effect filter error code.
///
///
/// Available since API-level: 12
///
/// Version: 1.0
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct EffectErrorCode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-14")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
impl EffectTileMode {
    /// Replicate the edge color if the shader draws outside of its original bounds
    pub const CLAMP: EffectTileMode = EffectTileMode(0);
    /// Repeat the shader's image horizontally and vertically
    pub const REPEAT: EffectTileMode = EffectTileMode(1);
    /// Repeat the shader's image horizontally and vertically,
    /// alternating mirror images so that adjacent images always seam
    pub const MIRROR: EffectTileMode = EffectTileMode(2);
    /// Only draw within the original domain, return transparent-black everywhere else
    pub const DECAL: EffectTileMode = EffectTileMode(3);
}
#[repr(transparent)]
/// Defines a effect filter tile mode.
///
///
/// Available since API-level: 14
#[cfg(feature = "api-14")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct EffectTileMode(pub ::core::ffi::c_uint);
extern "C" {
    /// Creates an <b>OH_Filter</b> object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `pixelmap` - The pixelmap pointer to create filter.
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_CreateEffect(
        pixelmap: *mut OH_PixelmapNative,
        filter: *mut *mut OH_Filter,
    ) -> EffectErrorCode;
    /// Release an <b>OH_Filter</b> object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`]
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_Release(filter: *mut OH_Filter) -> EffectErrorCode;
    /// Creates a blur effect and then add to the filter.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// * `radius` - The radius of the blur effect.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_Blur(filter: *mut OH_Filter, radius: f32) -> EffectErrorCode;
    /// Creates a blur effect and then add to the filter.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// * `radius` - The radius of the blur effect.
    ///
    /// * `tileMode` - The tileMode of the blur effect.
    ///
    /// # Returns
    ///
    /// * BlurWithTileMode result code.
    /// [`EFFECT_SUCCESS`] if the operation is successful.
    /// [`EFFECT_BAD_PARAMETER`] if parameter is invalid.
    ///
    /// Available since API-level: 14
    #[cfg(feature = "api-14")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
    pub fn OH_Filter_BlurWithTileMode(
        filter: *mut OH_Filter,
        radius: f32,
        tileMode: EffectTileMode,
    ) -> EffectErrorCode;
    /// Creates a brighten effect and then add to the filter.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// * `brightness` - The brightness of the brighten effect.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_Brighten(filter: *mut OH_Filter, brightness: f32) -> EffectErrorCode;
    /// Creates a gray scale effect and then add to the filter.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_GrayScale(filter: *mut OH_Filter) -> EffectErrorCode;
    /// Creates a invert effect and then add to the filter.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_Invert(filter: *mut OH_Filter) -> EffectErrorCode;
    /// Creates a effect with a matrix and then add to the filter.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// * `matrix` - The [`OH_Filter_ColorMatrix`] pointer to create a custom effect.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_SetColorMatrix(
        filter: *mut OH_Filter,
        matrix: *mut OH_Filter_ColorMatrix,
    ) -> EffectErrorCode;
    /// Get a pixelmap with the filter effect.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Multimedia.Image.Core
    /// # Arguments
    ///
    /// * `filter` - The OH_Filter pointer will be operated.
    ///
    /// * `pixelmap` - The pixelmap pointer wiil be operated.
    ///
    /// # Returns
    ///
    /// * Returns [`EffectErrorCode`].
    ///
    /// Available since API-level: 12
    ///
    /// Version: 1.0
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Filter_GetEffectPixelMap(
        filter: *mut OH_Filter,
        pixelmap: *mut *mut OH_PixelmapNative,
    ) -> EffectErrorCode;
}
