// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl ffrt_queue_priority_t {
    /// Should be distributed at once if possible, handle time equals to send time, prior to high level.
    pub const ffrt_queue_priority_immediate: ffrt_queue_priority_t = ffrt_queue_priority_t(0);
    /// High priority, sorted by handle time, prior to low level.
    pub const ffrt_queue_priority_high: ffrt_queue_priority_t = ffrt_queue_priority_t(1);
    /// Low priority, sorted by handle time, prior to idle level.
    pub const ffrt_queue_priority_low: ffrt_queue_priority_t = ffrt_queue_priority_t(2);
    /// Lowest priority, sorted by handle time, only distribute when there is no other level inside queue.
    pub const ffrt_queue_priority_idle: ffrt_queue_priority_t = ffrt_queue_priority_t(3);
}
#[repr(transparent)]
/// Enumerates the task priority types.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_queue_priority_t(pub ::core::ffi::c_uint);
impl ffrt_qos_default_t {
    /// Inheritance.
    pub const ffrt_qos_inherit: ffrt_qos_default_t = ffrt_qos_default_t(-1);
    /// Background task.
    pub const ffrt_qos_background: ffrt_qos_default_t = ffrt_qos_default_t(0);
    /// Real-time tool.
    pub const ffrt_qos_utility: ffrt_qos_default_t = ffrt_qos_default_t(1);
    /// Default type.
    pub const ffrt_qos_default: ffrt_qos_default_t = ffrt_qos_default_t(2);
    /// User initiated.
    pub const ffrt_qos_user_initiated: ffrt_qos_default_t = ffrt_qos_default_t(3);
    /// Deadline request.
    ///
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const ffrt_qos_deadline_request: ffrt_qos_default_t = ffrt_qos_default_t(4);
    /// User interactive.
    ///
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const ffrt_qos_user_interactive: ffrt_qos_default_t = ffrt_qos_default_t(5);
    /// Max qos.
    ///
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const ffrt_qos_max: ffrt_qos_default_t = ffrt_qos_default_t(5);
}
#[repr(transparent)]
/// Enumerates the task QoS types.
///
///
/// Available since API-level: 10
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_qos_default_t(pub ::core::ffi::c_int);
/// Defines the QoS type.
///
///
/// Available since API-level: 10
pub type ffrt_qos_t = ::core::ffi::c_int;
/// Defines the task function pointer type.
///
///
/// Available since API-level: 10
pub type ffrt_function_t =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>;
/// Defines a task executor.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_function_header_t {
    /// Function used to execute a task.
    pub exec: ffrt_function_t,
    /// Function used to destroy a task.
    pub destroy: ffrt_function_t,
    /// Need to be set to 0.
    pub reserve: [u64; 2usize],
}
impl ffrt_storage_size_t {
    /// Task attribute storage size.
    pub const ffrt_task_attr_storage_size: ffrt_storage_size_t = ffrt_storage_size_t(128);
    /// Task executor storage size.
    pub const ffrt_auto_managed_function_storage_size: ffrt_storage_size_t =
        ffrt_storage_size_t(88);
    /// Mutex storage size.
    pub const ffrt_mutex_storage_size: ffrt_storage_size_t = ffrt_storage_size_t(64);
    /// Condition variable storage size.
    pub const ffrt_cond_storage_size: ffrt_storage_size_t = ffrt_storage_size_t(64);
    /// Queue storage size.
    pub const ffrt_queue_attr_storage_size: ffrt_storage_size_t = ffrt_storage_size_t(128);
    /// Rwlock storage size.
    ///
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub const ffrt_rwlock_storage_size: ffrt_storage_size_t = ffrt_storage_size_t(64);
    pub const ffrt_fiber_storage_size: ffrt_storage_size_t = ffrt_storage_size_t(64);
}
#[repr(transparent)]
/// Defines the storage size of multiple types of structs.
///
///
/// Available since API-level: 10
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_storage_size_t(pub ::core::ffi::c_uint);
impl ffrt_function_kind_t {
    /// General task.
    pub const ffrt_function_kind_general: ffrt_function_kind_t = ffrt_function_kind_t(0);
    /// Queue task.
    pub const ffrt_function_kind_queue: ffrt_function_kind_t = ffrt_function_kind_t(1);
}
#[repr(transparent)]
/// Enumerates the task types.
///
///
/// Available since API-level: 10
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_function_kind_t(pub ::core::ffi::c_uint);
impl ffrt_dependence_type_t {
    /// Data dependency type.
    pub const ffrt_dependence_data: ffrt_dependence_type_t = ffrt_dependence_type_t(0);
    /// Task dependency type.
    pub const ffrt_dependence_task: ffrt_dependence_type_t = ffrt_dependence_type_t(1);
}
#[repr(transparent)]
/// Enumerates the dependency types.
///
///
/// Available since API-level: 10
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_dependence_type_t(pub ::core::ffi::c_uint);
/// Defines the dependency data structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_dependence_t {
    /// Dependency type.
    pub type_: ffrt_dependence_type_t,
    /// Dependency pointer.
    pub ptr: *const ::core::ffi::c_void,
}
/// Defines the dependency structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_deps_t {
    /// Number of dependencies.
    pub len: u32,
    /// Dependency data.
    pub items: *const ffrt_dependence_t,
}
/// Defines the task attribute structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_task_attr_t {
    /// An array of uint32_t used to store the task attribute.
    pub storage: [u32; 32usize],
}
/// Defines the queue attribute structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_queue_attr_t {
    /// An array of uint32_t used to store the queue attribute.
    pub storage: [u32; 32usize],
}
/// Defines the task handle, which identifies different tasks.
///
///
/// Available since API-level: 10
pub type ffrt_task_handle_t = *mut ::core::ffi::c_void;
impl ffrt_error_t {
    /// A generic error.
    pub const ffrt_error: ffrt_error_t = ffrt_error_t(-1);
    /// Success.
    pub const ffrt_success: ffrt_error_t = ffrt_error_t(0);
    /// An out of memory error.
    pub const ffrt_error_nomem: ffrt_error_t = ffrt_error_t(12);
    /// A timeout error.
    pub const ffrt_error_timedout: ffrt_error_t = ffrt_error_t(110);
    /// A busy error.
    pub const ffrt_error_busy: ffrt_error_t = ffrt_error_t(16);
    /// A invalid value error.
    pub const ffrt_error_inval: ffrt_error_t = ffrt_error_t(22);
}
#[repr(transparent)]
/// Enumerates the ffrt error codes.
///
///
/// Available since API-level: 10
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_error_t(pub ::core::ffi::c_int);
/// Defines the condition variable attribute structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_condattr_t {
    /// A long integer used to store the condition variable attribute.
    pub storage: ::core::ffi::c_long,
}
/// Defines the mutex attribute structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_mutexattr_t {
    /// A long integer used to store the mutex attribute.
    pub storage: ::core::ffi::c_long,
}
/// Defines the rwlock attribute structure.
///
///
/// Available since API-level: 18
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_rwlockattr_t {
    /// A long integer used to store the rwlock attribute.
    pub storage: ::core::ffi::c_long,
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl ffrt_mutex_type {
    /// Normal mutex type.
    pub const ffrt_mutex_normal: ffrt_mutex_type = ffrt_mutex_type(0);
    /// Recursive mutex type.
    pub const ffrt_mutex_recursive: ffrt_mutex_type = ffrt_mutex_type(2);
    /// Default mutex type.
    pub const ffrt_mutex_default: ffrt_mutex_type = ffrt_mutex_type(0);
}
#[repr(transparent)]
/// Enumerates the mutex types.
///
/// Describes the mutex type, ffrt_mutex_normal is normal mutex;
/// ffrt_mutex_recursive is recursive mutex, ffrt_mutex_default is normal mutex.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ffrt_mutex_type(pub ::core::ffi::c_uint);
/// Defines the mutex structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_mutex_t {
    /// An array of uint32_t used to store the mutex.
    pub storage: [u32; 16usize],
}
/// Defines the rwlock structure.
///
///
/// Available since API-level: 18
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_rwlock_t {
    /// An array of uint32_t used to store the rwlock.
    pub storage: [u32; 16usize],
}
/// Defines the condition variable structure.
///
///
/// Available since API-level: 10
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_cond_t {
    /// An array of uint32_t used to store the condition variable.
    pub storage: [u32; 16usize],
}
/// Defines the fiber structure.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ffrt_fiber_t {
    /// An array of uint32_t used to store the fiber.
    pub storage: [usize; 64usize],
}
/// Defines the poller callback function type.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type ffrt_poller_cb =
    ::core::option::Option<unsafe extern "C" fn(data: *mut ::core::ffi::c_void, event: u32)>;
/// Defines the timer callback function type.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type ffrt_timer_cb =
    ::core::option::Option<unsafe extern "C" fn(data: *mut ::core::ffi::c_void)>;
/// Defines the timer handler.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type ffrt_timer_t = ::core::ffi::c_int;
