// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::camera::Camera_Device;
use crate::camera::*;
use crate::camera_input::Camera_Input;
use crate::capture_session::Camera_CaptureSession;
use crate::metadata_output::Camera_MetadataOutput;
use crate::photo_output::Camera_PhotoOutput;
use crate::preview_output::Camera_PreviewOutput;
use crate::video_output::Camera_VideoOutput;

/// Camera manager status callback to be called in [`CameraManager_Callbacks`].
///
/// # Arguments
///
/// * `cameraManager` - the [`Camera_Manager`] which deliver the callback.
///
/// * `status` - the [`Camera_StatusInfo`] of each camera device.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_CameraManager_StatusCallback = ::core::option::Option<
    unsafe extern "C" fn(cameraManager: *mut Camera_Manager, status: *mut Camera_StatusInfo),
>;
/// Camera manager torch status callback.
///
/// # Arguments
///
/// * `cameraManager` - the [`Camera_Manager`] which deliver the callback.
///
/// * `status` - the [`Camera_TorchStatusInfo`] of the torch.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_CameraManager_TorchStatusCallback = ::core::option::Option<
    unsafe extern "C" fn(cameraManager: *mut Camera_Manager, status: *mut Camera_TorchStatusInfo),
>;
/// Camera manager fold status info callback.
///
/// # Arguments
///
/// * `cameraManager` - the [`Camera_Manager`] which deliver the callback.
///
/// * `foldStatusInfo` - the [`Camera_FoldStatusInfo`] of the device.
///
/// Available since API-level: 13
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_CameraManager_OnFoldStatusInfoChange = ::core::option::Option<
    unsafe extern "C" fn(
        cameraManager: *mut Camera_Manager,
        foldStatusInfo: *mut Camera_FoldStatusInfo,
    ),
>;
/// A listener for camera devices status.
///
/// [`OH_CameraManager_RegisterCallback`]
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CameraManager_Callbacks {
    /// Camera status change event.
    pub onCameraStatus: OH_CameraManager_StatusCallback,
}
extern "C" {
    /// Register camera status change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `callback` - the [`CameraManager_Callbacks`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_RegisterCallback(
        cameraManager: *mut Camera_Manager,
        callback: *mut CameraManager_Callbacks,
    ) -> Camera_ErrorCode;
    /// Unregister camera status change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `callback` - the [`CameraManager_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_UnregisterCallback(
        cameraManager: *mut Camera_Manager,
        callback: *mut CameraManager_Callbacks,
    ) -> Camera_ErrorCode;
    /// Register torch status change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `torchStatusCallback` - the [`OH_CameraManager_TorchStatusCallback`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_RegisterTorchStatusCallback(
        cameraManager: *mut Camera_Manager,
        torchStatusCallback: OH_CameraManager_TorchStatusCallback,
    ) -> Camera_ErrorCode;
    /// Unregister torch status change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `torchStatusCallback` - the [`OH_CameraManager_TorchStatusCallback`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_UnregisterTorchStatusCallback(
        cameraManager: *mut Camera_Manager,
        torchStatusCallback: OH_CameraManager_TorchStatusCallback,
    ) -> Camera_ErrorCode;
    /// Register fold status info change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `foldStatusInfoCallback` - the [`OH_CameraManager_OnFoldStatusInfoChange`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_CameraManager_RegisterFoldStatusInfoCallback(
        cameraManager: *mut Camera_Manager,
        foldStatusInfoCallback: OH_CameraManager_OnFoldStatusInfoChange,
    ) -> Camera_ErrorCode;
    /// Unregister fold status info change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `foldStatusInfoCallback` - the [`OH_CameraManager_OnFoldStatusInfoChange`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_CameraManager_UnregisterFoldStatusInfoCallback(
        cameraManager: *mut Camera_Manager,
        foldStatusInfoCallback: OH_CameraManager_OnFoldStatusInfoChange,
    ) -> Camera_ErrorCode;
    /// Gets supported camera descriptions.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `cameras` - the supported [`Camera_Device`] list will be filled
    /// if the method call succeeds.
    ///
    /// * `size` - the size of supported [`Camera_Device`] list will be filled
    /// if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_GetSupportedCameras(
        cameraManager: *mut Camera_Manager,
        cameras: *mut *mut Camera_Device,
        size: *mut u32,
    ) -> Camera_ErrorCode;
    /// Delete supported camera.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `cameras` - the [`Camera_Device`] list to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_DeleteSupportedCameras(
        cameraManager: *mut Camera_Manager,
        cameras: *mut Camera_Device,
        size: u32,
    ) -> Camera_ErrorCode;
    /// Gets the supported output capability for the specific camera and specific mode.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `camera` - the [`Camera_Device`] to be queryed.
    ///
    /// * `cameraOutputCapability` - the supported [`Camera_OutputCapability`] will be filled
    /// if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_GetSupportedCameraOutputCapability(
        cameraManager: *mut Camera_Manager,
        camera: *const Camera_Device,
        cameraOutputCapability: *mut *mut Camera_OutputCapability,
    ) -> Camera_ErrorCode;
    /// Gets supported output capability for specific camera and specific sceneMode.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `camera` - the [`Camera_Device`] to be queryed.
    ///
    /// * `sceneMode` - the [`Camera_SceneMode`] to be queryed.
    ///
    /// * `cameraOutputCapability` - the supported [`Camera_OutputCapability`] will be filled
    /// if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_GetSupportedCameraOutputCapabilityWithSceneMode(
        cameraManager: *mut Camera_Manager,
        camera: *const Camera_Device,
        sceneMode: Camera_SceneMode,
        cameraOutputCapability: *mut *mut Camera_OutputCapability,
    ) -> Camera_ErrorCode;
    /// Gets the supported full output capability for the specific camera, including capabilities of yuv, heif and hdr etc.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `camera` - the [`Camera_Device`] to be queried.
    ///
    /// * `sceneMode` - the [`Camera_SceneMode`] to be queried.
    ///
    /// * `cameraOutputCapability` - the supported [`Camera_OutputCapability`] will be filled
    /// if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_CameraManager_GetSupportedFullCameraOutputCapabilityWithSceneMode(
        cameraManager: *mut Camera_Manager,
        camera: *const Camera_Device,
        sceneMode: Camera_SceneMode,
        cameraOutputCapability: *mut *mut Camera_OutputCapability,
    ) -> Camera_ErrorCode;
    /// Delete the supported output capability.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `cameraOutputCapability` - the [`Camera_OutputCapability`] to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_DeleteSupportedCameraOutputCapability(
        cameraManager: *mut Camera_Manager,
        cameraOutputCapability: *mut Camera_OutputCapability,
    ) -> Camera_ErrorCode;
    /// Determine whether camera is muted.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `isCameraMuted` - whether camera is muted will be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_IsCameraMuted(
        cameraManager: *mut Camera_Manager,
        isCameraMuted: *mut bool,
    ) -> Camera_ErrorCode;
    /// Create a capture session instance.The default session mode is photo session.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `captureSession` - the [`Camera_CaptureSession`] will be created
    /// if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreateCaptureSession(
        cameraManager: *mut Camera_Manager,
        captureSession: *mut *mut Camera_CaptureSession,
    ) -> Camera_ErrorCode;
    /// Create a camera input instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `camera` - the [`Camera_Device`] which use to create [`Camera_Input`].
    ///
    /// * `cameraInput` - the [`Camera_Input`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    /// ohos.permission.CAMERA
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreateCameraInput(
        cameraManager: *mut Camera_Manager,
        camera: *const Camera_Device,
        cameraInput: *mut *mut Camera_Input,
    ) -> Camera_ErrorCode;
    /// Create a camera input instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `position` - the [`Camera_Position`] which use to create [`Camera_Input`].
    ///
    /// * `type` - the [`Camera_Type`] which use to create [`Camera_Input`].
    ///
    /// * `cameraInput` - the [`Camera_Input`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    /// ohos.permission.CAMERA
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreateCameraInput_WithPositionAndType(
        cameraManager: *mut Camera_Manager,
        position: Camera_Position,
        type_: Camera_Type,
        cameraInput: *mut *mut Camera_Input,
    ) -> Camera_ErrorCode;
    /// Create a preview output instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `profile` - the [`Camera_Profile`] to create [`Camera_PreviewOutput`].
    ///
    /// * `surfaceId` - the which use to create [`Camera_PreviewOutput`].
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreatePreviewOutput(
        cameraManager: *mut Camera_Manager,
        profile: *const Camera_Profile,
        surfaceId: *const ::core::ffi::c_char,
        previewOutput: *mut *mut Camera_PreviewOutput,
    ) -> Camera_ErrorCode;
    /// Create a preview output instance used in preconfig.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `surfaceId` - the which use to create [`Camera_PreviewOutput`].
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_CreatePreviewOutputUsedInPreconfig(
        cameraManager: *mut Camera_Manager,
        surfaceId: *const ::core::ffi::c_char,
        previewOutput: *mut *mut Camera_PreviewOutput,
    ) -> Camera_ErrorCode;
    /// Create a photo output instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `profile` - the [`Camera_Profile`] to create [`Camera_PhotoOutput`].
    ///
    /// * `surfaceId` - the which use to create [`Camera_PhotoOutput`].
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreatePhotoOutput(
        cameraManager: *mut Camera_Manager,
        profile: *const Camera_Profile,
        surfaceId: *const ::core::ffi::c_char,
        photoOutput: *mut *mut Camera_PhotoOutput,
    ) -> Camera_ErrorCode;
    /// Create a photo output instance used in preconfig.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `surfaceId` - the which use to create [`Camera_PhotoOutput`].
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_CreatePhotoOutputUsedInPreconfig(
        cameraManager: *mut Camera_Manager,
        surfaceId: *const ::core::ffi::c_char,
        photoOutput: *mut *mut Camera_PhotoOutput,
    ) -> Camera_ErrorCode;
    /// Create a photo output instance without surfaceId.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `profile` - the [`Camera_Profile`] to create [`Camera_PhotoOutput`].
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_CreatePhotoOutputWithoutSurface(
        cameraManager: *mut Camera_Manager,
        profile: *const Camera_Profile,
        photoOutput: *mut *mut Camera_PhotoOutput,
    ) -> Camera_ErrorCode;
    /// Create a video output instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `profile` - the [`Camera_VideoProfile`] to create [`Camera_VideoOutput`].
    ///
    /// * `surfaceId` - the which use to create [`Camera_VideoOutput`].
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreateVideoOutput(
        cameraManager: *mut Camera_Manager,
        profile: *const Camera_VideoProfile,
        surfaceId: *const ::core::ffi::c_char,
        videoOutput: *mut *mut Camera_VideoOutput,
    ) -> Camera_ErrorCode;
    /// Create a video output instance used in preconfig.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `surfaceId` - the which use to create [`Camera_VideoOutput`].
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_CreateVideoOutputUsedInPreconfig(
        cameraManager: *mut Camera_Manager,
        surfaceId: *const ::core::ffi::c_char,
        videoOutput: *mut *mut Camera_VideoOutput,
    ) -> Camera_ErrorCode;
    /// Create a metadata output instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `profile` - the [`Camera_MetadataObjectType`] to create [`Camera_MetadataOutput`].
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraManager_CreateMetadataOutput(
        cameraManager: *mut Camera_Manager,
        profile: *const Camera_MetadataObjectType,
        metadataOutput: *mut *mut Camera_MetadataOutput,
    ) -> Camera_ErrorCode;
    /// Create a metadata output with object types instance.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `metadataObjectTypes` - the [`Camera_MetadataObjectType`] to create [`Camera_MetadataOutput`].
    ///
    /// * `size` - the size of the [`Camera_MetadataObjectType`].
    ///
    /// * `metadataOutput` - the [`Camera_MetadataOutput`] will be created if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_CameraManager_CreateMetadataOutputWithObjectTypes(
        cameraManager: *mut Camera_Manager,
        metadataObjectTypes: *const Camera_MetadataObjectType,
        size: u32,
        metadataOutput: *mut *mut Camera_MetadataOutput,
    ) -> Camera_ErrorCode;
    /// Gets supported scene mode for specific camera.
    ///
    /// # Arguments
    ///
    /// * `camera` - the [`Camera_Device`] to be queryed.
    ///
    /// * `sceneModes` - the supported [`Camera_SceneMode`] will be filled if the method call succeeds.
    ///
    /// * `size` - the size of supported [`Camera_SceneMode`] list will be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_GetSupportedSceneModes(
        camera: *mut Camera_Device,
        sceneModes: *mut *mut Camera_SceneMode,
        size: *mut u32,
    ) -> Camera_ErrorCode;
    /// Delete the scene mode.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `sceneModes` - the [`Camera_SceneMode`] to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_DeleteSceneModes(
        cameraManager: *mut Camera_Manager,
        sceneModes: *mut Camera_SceneMode,
    ) -> Camera_ErrorCode;
    /// Check if the device supports torch.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `isTorchSupported` - whether the device supports torch.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_IsTorchSupported(
        cameraManager: *mut Camera_Manager,
        isTorchSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Check whether the device supports the torch with the specified torch mode.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `torchMode` - the [`Camera_TorchMode`] to be checked.
    ///
    /// * `isTorchSupported` - whether device supports the torch mode.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_IsTorchSupportedByTorchMode(
        cameraManager: *mut Camera_Manager,
        torchMode: Camera_TorchMode,
        isTorchSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Set camera torch mode.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `torchMode` - the [`Camera_TorchMode`] to be set.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraManager_SetTorchMode(
        cameraManager: *mut Camera_Manager,
        torchMode: Camera_TorchMode,
    ) -> Camera_ErrorCode;
    /// Queries a specified device based on position and type.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `position` - the [`Camera_Position`] instance.
    ///
    /// * `type` - the [`Camera_Type`] instance.
    ///
    /// * `camera` - the [`Camera_Device`] to be set.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_CameraManager_GetCameraDevice(
        cameraManager: *mut Camera_Manager,
        position: Camera_Position,
        type_: Camera_Type,
        camera: *mut Camera_Device,
    ) -> Camera_ErrorCode;
    /// Queries specified devices based on camera type, connection type and position.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `deviceQueryInfo` - the [`Camera_DeviceQueryInfo`] instance.
    ///
    /// * `cameraSize` - the size of supported [`Camera_Device`] list.
    ///
    /// * `cameras` - the supported [`Camera_Device`] list.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_CameraManager_GetCameraDevices(
        cameraManager: *mut Camera_Manager,
        deviceQueryInfo: *mut Camera_DeviceQueryInfo,
        cameraSize: *mut u32,
        cameras: *mut *mut Camera_Device,
    ) -> Camera_ErrorCode;
    /// Delete specified devices.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `cameras` - the [`Camera_Device`] list to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_CameraManager_DeleteCameraDevices(
        cameraManager: *mut Camera_Manager,
        cameras: *mut Camera_Device,
    ) -> Camera_ErrorCode;
    /// Obtains the concurrent information of specified cameras, the empty return means concurrency is not supported.
    ///
    /// # Arguments
    ///
    /// * `cameraManager` - the [`Camera_Manager`] instance.
    ///
    /// * `camera` - the [`Camera_Device`] instance.
    ///
    /// * `deviceSize` - length of the input device array.
    ///
    /// * `cameraConcurrentInfo` - the [`Camera_ConcurrentInfo`] to be set.
    ///
    /// * `infoSize` - length of the returned concurrency information array.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_CameraManager_GetCameraConcurrentInfos(
        cameraManager: *mut Camera_Manager,
        camera: *const Camera_Device,
        deviceSize: u32,
        cameraConcurrentInfo: *mut *mut Camera_ConcurrentInfo,
        infoSize: *mut u32,
    ) -> Camera_ErrorCode;
}
