// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
pub use ohos_sys_opaque_types::{OH_ImageSourceNative, OH_PictureNative};

/// Define UUID max length
///
/// This constant defines the maximum length of a UUID string.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub const UUID_STR_MAX_LENGTH: i32 = 37;
/// Define Media Asset Manager
///
/// This structure provides the ability to request media library resources.
/// Null pointer is returned if the creation fails.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_MediaAssetManager {
    _unused: [u8; 0],
}
/// Define Media Asset Change Request
///
/// This structure provides the ability to handle a media asset change request.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_MediaAssetChangeRequest {
    _unused: [u8; 0],
}
/// Define Moving Photo
///
/// This structure provides the ability to obtain information about moving photo.
///
///
/// Available since API-level: 13
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[repr(C)]
pub struct OH_MovingPhoto {
    _unused: [u8; 0],
}
/// Define Media Asset
///
/// This structure provides the ability to encapsulate file asset attributes.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_MediaAsset {
    _unused: [u8; 0],
}
/// Define MediaLibrary_RequestId
///
/// This type is returned when requesting a media library resource.
/// The request id is used to cancel the request.
/// The value is all zero like "00000000-0000-0000-0000-000000000000" if the request fails.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MediaLibrary_RequestId {
    pub requestId: [::core::ffi::c_char; 37usize],
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_ErrorCode {
    /// Media library result is ok.
    pub const MEDIA_LIBRARY_OK: MediaLibrary_ErrorCode = MediaLibrary_ErrorCode(0);
    /// Permission is denied.
    pub const MEDIA_LIBRARY_PERMISSION_DENIED: MediaLibrary_ErrorCode = MediaLibrary_ErrorCode(201);
    /// Mandatory parameters are left unspecified
    /// or incorrect parameter types or parameter verification failed.
    pub const MEDIA_LIBRARY_PARAMETER_ERROR: MediaLibrary_ErrorCode = MediaLibrary_ErrorCode(401);
    /// File does not exist.
    pub const MEDIA_LIBRARY_NO_SUCH_FILE: MediaLibrary_ErrorCode = MediaLibrary_ErrorCode(23800101);
    /// Invalid display name.
    pub const MEDIA_LIBRARY_INVALID_DISPLAY_NAME: MediaLibrary_ErrorCode =
        MediaLibrary_ErrorCode(23800102);
    /// Invalid asset uri.
    pub const MEDIA_LIBRARY_INVALID_ASSET_URI: MediaLibrary_ErrorCode =
        MediaLibrary_ErrorCode(23800103);
    /// Member is not a valid PhotoKey.
    pub const MEDIA_LIBRARY_INVALID_PHOTO_KEY: MediaLibrary_ErrorCode =
        MediaLibrary_ErrorCode(23800104);
    /// Operation is not supported.
    pub const MEDIA_LIBRARY_OPERATION_NOT_SUPPORTED: MediaLibrary_ErrorCode =
        MediaLibrary_ErrorCode(23800201);
    /// Internal system error.
    /// It is recommended to retry and check the logs.
    /// Possible causes:
    /// 1. Database corrupted.
    /// 2. The file system is abnormal.
    /// 3. The IPC request timed out.
    pub const MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR: MediaLibrary_ErrorCode =
        MediaLibrary_ErrorCode(23800301);
}
#[repr(transparent)]
/// Enum for media library error code.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_ErrorCode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_DeliveryMode {
    pub const MEDIA_LIBRARY_FAST_MODE: MediaLibrary_DeliveryMode = MediaLibrary_DeliveryMode(0);
    pub const MEDIA_LIBRARY_HIGH_QUALITY_MODE: MediaLibrary_DeliveryMode =
        MediaLibrary_DeliveryMode(1);
    pub const MEDIA_LIBRARY_BALANCED_MODE: MediaLibrary_DeliveryMode = MediaLibrary_DeliveryMode(2);
}
#[repr(transparent)]
/// Delivery Mode
///
/// This enumeration defines the delivery mode of the requested resources.
/// The delivery mode can be set to fast mode, high quality mode, or balanced mode.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_DeliveryMode(pub ::core::ffi::c_uint);
/// Request Options
///
/// This structure provides options for requesting media library resources.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MediaLibrary_RequestOptions {
    pub deliveryMode: MediaLibrary_DeliveryMode,
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_MediaType {
    pub const MEDIA_LIBRARY_IMAGE: MediaLibrary_MediaType = MediaLibrary_MediaType(1);
    pub const MEDIA_LIBRARY_VIDEO: MediaLibrary_MediaType = MediaLibrary_MediaType(2);
}
#[repr(transparent)]
/// Enum for media type.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_MediaType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_MediaSubType {
    pub const MEDIA_LIBRARY_DEFAULT: MediaLibrary_MediaSubType = MediaLibrary_MediaSubType(0);
    pub const MEDIA_LIBRARY_MOVING_PHOTO: MediaLibrary_MediaSubType = MediaLibrary_MediaSubType(3);
    pub const MEDIA_LIBRARY_BURST: MediaLibrary_MediaSubType = MediaLibrary_MediaSubType(4);
}
#[repr(transparent)]
/// Enum for media asset subtype.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_MediaSubType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_ResourceType {
    pub const MEDIA_LIBRARY_IMAGE_RESOURCE: MediaLibrary_ResourceType =
        MediaLibrary_ResourceType(1);
    pub const MEDIA_LIBRARY_VIDEO_RESOURCE: MediaLibrary_ResourceType =
        MediaLibrary_ResourceType(2);
}
#[repr(transparent)]
/// Enum for resource types.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_ResourceType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_ImageFileType {
    pub const MEDIA_LIBRARY_IMAGE_JPEG: MediaLibrary_ImageFileType = MediaLibrary_ImageFileType(1);
    /// HEIF type
    ///
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const MEDIA_LIBRARY_IMAGE_HEIF: MediaLibrary_ImageFileType = MediaLibrary_ImageFileType(2);
    /// MPEG type
    ///
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub const MEDIA_LIBRARY_FILE_VIDEO: MediaLibrary_ImageFileType = MediaLibrary_ImageFileType(3);
}
#[repr(transparent)]
/// Enum for image file Type.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_ImageFileType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_MediaQuality {
    pub const MEDIA_LIBRARY_QUALITY_FAST: MediaLibrary_MediaQuality = MediaLibrary_MediaQuality(1);
    pub const MEDIA_LIBRARY_QUALITY_FULL: MediaLibrary_MediaQuality = MediaLibrary_MediaQuality(2);
}
#[repr(transparent)]
/// Enum for media quality.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_MediaQuality(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl MediaLibrary_MediaContentType {
    pub const MEDIA_LIBRARY_COMPRESSED: MediaLibrary_MediaContentType =
        MediaLibrary_MediaContentType(1);
    pub const MEDIA_LIBRARY_PICTURE_OBJECT: MediaLibrary_MediaContentType =
        MediaLibrary_MediaContentType(2);
}
#[repr(transparent)]
/// Enum for media content type.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MediaLibrary_MediaContentType(pub ::core::ffi::c_uint);
/// Called when a requested source is prepared.
///
/// This function is called when the requested source is prepared.
///
/// # Arguments
///
/// * `result` - Results of the processing of the requested resources.
///
/// * `requestId` - Request ID.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_MediaLibrary_OnDataPrepared =
    ::core::option::Option<unsafe extern "C" fn(result: i32, requestId: MediaLibrary_RequestId)>;
/// Called when a requested image source is prepared.
///
/// This function is called when the requested image source is prepared.
///
/// # Arguments
///
/// * `result` - results [`MediaLibrary_ErrorCode`] of the processing of the requested resources.
///
/// * `requestId` - indicates the [`MediaLibrary_RequestId`] of the request.
///
/// * `mediaQuality` - the [`MediaLibrary_MediaQuality`] of the requested source.
///
/// * `type` - the [`MediaLibrary_MediaContentType`] of the requested source.
///
/// * `imageSourceNative` - it used to obtain [`OH_ImageSourceNative`] information when image source is prepared.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_MediaLibrary_OnImageDataPrepared = ::core::option::Option<
    unsafe extern "C" fn(
        result: MediaLibrary_ErrorCode,
        requestId: MediaLibrary_RequestId,
        mediaQuality: MediaLibrary_MediaQuality,
        type_: MediaLibrary_MediaContentType,
        imageSourceNative: *mut OH_ImageSourceNative,
    ),
>;
/// Called when a requested moving photo is prepared.
///
/// This function is called when the requested moving photo is prepared.
///
/// # Arguments
///
/// * `result` - results [`MediaLibrary_ErrorCode`] of the processing of the requested resources.
///
/// * `requestId` - indicates the [`MediaLibrary_RequestId`] of the request.
///
/// * `mediaQuality` - the [`MediaLibrary_MediaQuality`] of the requested source.
///
/// * `type` - the [`MediaLibrary_MediaContentType`] of the requested source.
///
/// * `movingPhoto` - it used to obtain [`OH_MovingPhoto`] information when the data is prepared.
///
/// Available since API-level: 13
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_MediaLibrary_OnMovingPhotoDataPrepared = ::core::option::Option<
    unsafe extern "C" fn(
        result: MediaLibrary_ErrorCode,
        requestId: MediaLibrary_RequestId,
        mediaQuality: MediaLibrary_MediaQuality,
        type_: MediaLibrary_MediaContentType,
        movingPhoto: *mut OH_MovingPhoto,
    ),
>;
/// Called when a requested quickly image is prepared.
///
/// This function is called when the requested quickly image is prepared.When there is an image buffer in the system,
/// a picture object will be returned, reducing the decoding time.
///
/// # Arguments
///
/// * `result` - results [`MediaLibrary_ErrorCode`] of the processing of the requested resources.
///
/// * `requestId` - indicates the [`MediaLibrary_RequestId`] of the request.
///
/// * `mediaQuality` - the [`MediaLibrary_MediaQuality`] of the requested source.
///
/// * `type` - the [`MediaLibrary_MediaContentType`] of the requested source.
///
/// * `imageSourceNative` - it is used to obtain [`OH_ImageSourceNative`] information when image file is prepared,
/// otherwise imageSourceNative is null.
///
/// * `pictureNative` - it is used to obtain [`OH_PictureNative`] information when image source is prepared,
/// otherwise OH_PictureNative is null.
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_MediaLibrary_OnQuickImageDataPrepared = ::core::option::Option<
    unsafe extern "C" fn(
        result: MediaLibrary_ErrorCode,
        requestId: MediaLibrary_RequestId,
        mediaQuality: MediaLibrary_MediaQuality,
        type_: MediaLibrary_MediaContentType,
        imageSourceNative: *mut OH_ImageSourceNative,
        pictureNative: *mut OH_PictureNative,
    ),
>;
