// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub const OH_AI_MAX_SHAPE_NUM: u32 = 32;
impl OH_AI_CompCode {
    pub const OH_AI_COMPCODE_CORE: OH_AI_CompCode = OH_AI_CompCode(0);
    pub const OH_AI_COMPCODE_MD: OH_AI_CompCode = OH_AI_CompCode(268435456);
    pub const OH_AI_COMPCODE_ME: OH_AI_CompCode = OH_AI_CompCode(536870912);
    pub const OH_AI_COMPCODE_MC: OH_AI_CompCode = OH_AI_CompCode(805306368);
    pub const OH_AI_COMPCODE_LITE: OH_AI_CompCode = OH_AI_CompCode(4026531840);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_CompCode(pub ::core::ffi::c_uint);
impl OH_AI_Status {
    pub const OH_AI_STATUS_SUCCESS: OH_AI_Status = OH_AI_Status(0);
    pub const OH_AI_STATUS_CORE_FAILED: OH_AI_Status = OH_AI_Status(1);
    pub const OH_AI_STATUS_LITE_ERROR: OH_AI_Status = OH_AI_Status(4294967295);
    pub const OH_AI_STATUS_LITE_NULLPTR: OH_AI_Status = OH_AI_Status(4294967294);
    pub const OH_AI_STATUS_LITE_PARAM_INVALID: OH_AI_Status = OH_AI_Status(4294967293);
    pub const OH_AI_STATUS_LITE_NO_CHANGE: OH_AI_Status = OH_AI_Status(4294967292);
    pub const OH_AI_STATUS_LITE_SUCCESS_EXIT: OH_AI_Status = OH_AI_Status(4294967291);
    pub const OH_AI_STATUS_LITE_MEMORY_FAILED: OH_AI_Status = OH_AI_Status(4294967290);
    pub const OH_AI_STATUS_LITE_NOT_SUPPORT: OH_AI_Status = OH_AI_Status(4294967289);
    pub const OH_AI_STATUS_LITE_THREADPOOL_ERROR: OH_AI_Status = OH_AI_Status(4294967288);
    pub const OH_AI_STATUS_LITE_UNINITIALIZED_OBJ: OH_AI_Status = OH_AI_Status(4294967287);
    pub const OH_AI_STATUS_LITE_OUT_OF_TENSOR_RANGE: OH_AI_Status = OH_AI_Status(4294967196);
    pub const OH_AI_STATUS_LITE_INPUT_TENSOR_ERROR: OH_AI_Status = OH_AI_Status(4294967195);
    pub const OH_AI_STATUS_LITE_REENTRANT_ERROR: OH_AI_Status = OH_AI_Status(4294967194);
    pub const OH_AI_STATUS_LITE_GRAPH_FILE_ERROR: OH_AI_Status = OH_AI_Status(4294967096);
    pub const OH_AI_STATUS_LITE_NOT_FIND_OP: OH_AI_Status = OH_AI_Status(4294966996);
    pub const OH_AI_STATUS_LITE_INVALID_OP_NAME: OH_AI_Status = OH_AI_Status(4294966995);
    pub const OH_AI_STATUS_LITE_INVALID_OP_ATTR: OH_AI_Status = OH_AI_Status(4294966994);
    pub const OH_AI_STATUS_LITE_OP_EXECUTE_FAILURE: OH_AI_Status = OH_AI_Status(4294966993);
    pub const OH_AI_STATUS_LITE_FORMAT_ERROR: OH_AI_Status = OH_AI_Status(4294966896);
    pub const OH_AI_STATUS_LITE_INFER_ERROR: OH_AI_Status = OH_AI_Status(4294966796);
    pub const OH_AI_STATUS_LITE_INFER_INVALID: OH_AI_Status = OH_AI_Status(4294966795);
    pub const OH_AI_STATUS_LITE_INPUT_PARAM_INVALID: OH_AI_Status = OH_AI_Status(4294966696);
    pub const OH_AI_STATUS_LITE_AIPP_NOT_SUPPORTED: OH_AI_Status = OH_AI_Status(4294966596);
    pub const OH_AI_STATUS_LITE_AIPP_INFER_ERROR: OH_AI_Status = OH_AI_Status(4294966595);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_Status(pub ::core::ffi::c_uint);
impl OH_AI_ModelType {
    pub const OH_AI_MODELTYPE_MINDIR: OH_AI_ModelType = OH_AI_ModelType(0);
    pub const OH_AI_MODELTYPE_INVALID: OH_AI_ModelType = OH_AI_ModelType(4294967295);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_ModelType(pub ::core::ffi::c_uint);
impl OH_AI_DeviceType {
    pub const OH_AI_DEVICETYPE_CPU: OH_AI_DeviceType = OH_AI_DeviceType(0);
    pub const OH_AI_DEVICETYPE_GPU: OH_AI_DeviceType = OH_AI_DeviceType(1);
    pub const OH_AI_DEVICETYPE_KIRIN_NPU: OH_AI_DeviceType = OH_AI_DeviceType(2);
    pub const OH_AI_DEVICETYPE_NNRT: OH_AI_DeviceType = OH_AI_DeviceType(60);
    pub const OH_AI_DEVICETYPE_INVALID: OH_AI_DeviceType = OH_AI_DeviceType(100);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_DeviceType(pub ::core::ffi::c_uint);
impl OH_AI_NNRTDeviceType {
    pub const OH_AI_NNRTDEVICE_OTHERS: OH_AI_NNRTDeviceType = OH_AI_NNRTDeviceType(0);
    pub const OH_AI_NNRTDEVICE_CPU: OH_AI_NNRTDeviceType = OH_AI_NNRTDeviceType(1);
    pub const OH_AI_NNRTDEVICE_GPU: OH_AI_NNRTDeviceType = OH_AI_NNRTDeviceType(2);
    pub const OH_AI_NNRTDEVICE_ACCELERATOR: OH_AI_NNRTDeviceType = OH_AI_NNRTDeviceType(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_NNRTDeviceType(pub ::core::ffi::c_uint);
impl OH_AI_PerformanceMode {
    pub const OH_AI_PERFORMANCE_NONE: OH_AI_PerformanceMode = OH_AI_PerformanceMode(0);
    pub const OH_AI_PERFORMANCE_LOW: OH_AI_PerformanceMode = OH_AI_PerformanceMode(1);
    pub const OH_AI_PERFORMANCE_MEDIUM: OH_AI_PerformanceMode = OH_AI_PerformanceMode(2);
    pub const OH_AI_PERFORMANCE_HIGH: OH_AI_PerformanceMode = OH_AI_PerformanceMode(3);
    pub const OH_AI_PERFORMANCE_EXTREME: OH_AI_PerformanceMode = OH_AI_PerformanceMode(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_PerformanceMode(pub ::core::ffi::c_uint);
impl OH_AI_Priority {
    pub const OH_AI_PRIORITY_NONE: OH_AI_Priority = OH_AI_Priority(0);
    pub const OH_AI_PRIORITY_LOW: OH_AI_Priority = OH_AI_Priority(1);
    pub const OH_AI_PRIORITY_MEDIUM: OH_AI_Priority = OH_AI_Priority(2);
    pub const OH_AI_PRIORITY_HIGH: OH_AI_Priority = OH_AI_Priority(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_Priority(pub ::core::ffi::c_uint);
impl OH_AI_OptimizationLevel {
    pub const OH_AI_KO0: OH_AI_OptimizationLevel = OH_AI_OptimizationLevel(0);
    pub const OH_AI_KO2: OH_AI_OptimizationLevel = OH_AI_OptimizationLevel(2);
    pub const OH_AI_KO3: OH_AI_OptimizationLevel = OH_AI_OptimizationLevel(3);
    pub const OH_AI_KAUTO: OH_AI_OptimizationLevel = OH_AI_OptimizationLevel(4);
    pub const OH_AI_KOPTIMIZATIONTYPE: OH_AI_OptimizationLevel =
        OH_AI_OptimizationLevel(4294967295);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_OptimizationLevel(pub ::core::ffi::c_uint);
impl OH_AI_QuantizationType {
    pub const OH_AI_NO_QUANT: OH_AI_QuantizationType = OH_AI_QuantizationType(0);
    pub const OH_AI_WEIGHT_QUANT: OH_AI_QuantizationType = OH_AI_QuantizationType(1);
    pub const OH_AI_FULL_QUANT: OH_AI_QuantizationType = OH_AI_QuantizationType(2);
    pub const OH_AI_UNKNOWN_QUANT_TYPE: OH_AI_QuantizationType = OH_AI_QuantizationType(4294967295);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_QuantizationType(pub ::core::ffi::c_uint);
#[repr(C)]
pub struct NNRTDeviceDesc {
    _unused: [u8; 0],
}
impl OH_AI_DataType {
    pub const OH_AI_DATATYPE_UNKNOWN: OH_AI_DataType = OH_AI_DataType(0);
    pub const OH_AI_DATATYPE_OBJECTTYPE_STRING: OH_AI_DataType = OH_AI_DataType(12);
    pub const OH_AI_DATATYPE_OBJECTTYPE_LIST: OH_AI_DataType = OH_AI_DataType(13);
    pub const OH_AI_DATATYPE_OBJECTTYPE_TUPLE: OH_AI_DataType = OH_AI_DataType(14);
    pub const OH_AI_DATATYPE_OBJECTTYPE_TENSOR: OH_AI_DataType = OH_AI_DataType(17);
    pub const OH_AI_DATATYPE_NUMBERTYPE_BEGIN: OH_AI_DataType = OH_AI_DataType(29);
    pub const OH_AI_DATATYPE_NUMBERTYPE_BOOL: OH_AI_DataType = OH_AI_DataType(30);
    pub const OH_AI_DATATYPE_NUMBERTYPE_INT8: OH_AI_DataType = OH_AI_DataType(32);
    pub const OH_AI_DATATYPE_NUMBERTYPE_INT16: OH_AI_DataType = OH_AI_DataType(33);
    pub const OH_AI_DATATYPE_NUMBERTYPE_INT32: OH_AI_DataType = OH_AI_DataType(34);
    pub const OH_AI_DATATYPE_NUMBERTYPE_INT64: OH_AI_DataType = OH_AI_DataType(35);
    pub const OH_AI_DATATYPE_NUMBERTYPE_UINT8: OH_AI_DataType = OH_AI_DataType(37);
    pub const OH_AI_DATATYPE_NUMBERTYPE_UINT16: OH_AI_DataType = OH_AI_DataType(38);
    pub const OH_AI_DATATYPE_NUMBERTYPE_UINT32: OH_AI_DataType = OH_AI_DataType(39);
    pub const OH_AI_DATATYPE_NUMBERTYPE_UINT64: OH_AI_DataType = OH_AI_DataType(40);
    pub const OH_AI_DATATYPE_NUMBERTYPE_FLOAT16: OH_AI_DataType = OH_AI_DataType(42);
    pub const OH_AI_DATATYPE_NUMBERTYPE_FLOAT32: OH_AI_DataType = OH_AI_DataType(43);
    pub const OH_AI_DATATYPE_NUMBERTYPE_FLOAT64: OH_AI_DataType = OH_AI_DataType(44);
    pub const OH_AI_DATATYPE_NUMBERTYPE_END: OH_AI_DataType = OH_AI_DataType(46);
    pub const OH_AI_DataTypeInvalid: OH_AI_DataType = OH_AI_DataType(2147483647);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_DataType(pub ::core::ffi::c_uint);
impl OH_AI_Format {
    pub const OH_AI_FORMAT_NCHW: OH_AI_Format = OH_AI_Format(0);
    pub const OH_AI_FORMAT_NHWC: OH_AI_Format = OH_AI_Format(1);
    pub const OH_AI_FORMAT_NHWC4: OH_AI_Format = OH_AI_Format(2);
    pub const OH_AI_FORMAT_HWKC: OH_AI_Format = OH_AI_Format(3);
    pub const OH_AI_FORMAT_HWCK: OH_AI_Format = OH_AI_Format(4);
    pub const OH_AI_FORMAT_KCHW: OH_AI_Format = OH_AI_Format(5);
    pub const OH_AI_FORMAT_CKHW: OH_AI_Format = OH_AI_Format(6);
    pub const OH_AI_FORMAT_KHWC: OH_AI_Format = OH_AI_Format(7);
    pub const OH_AI_FORMAT_CHWK: OH_AI_Format = OH_AI_Format(8);
    pub const OH_AI_FORMAT_HW: OH_AI_Format = OH_AI_Format(9);
    pub const OH_AI_FORMAT_HW4: OH_AI_Format = OH_AI_Format(10);
    pub const OH_AI_FORMAT_NC: OH_AI_Format = OH_AI_Format(11);
    pub const OH_AI_FORMAT_NC4: OH_AI_Format = OH_AI_Format(12);
    pub const OH_AI_FORMAT_NC4HW4: OH_AI_Format = OH_AI_Format(13);
    pub const OH_AI_FORMAT_NCDHW: OH_AI_Format = OH_AI_Format(15);
    pub const OH_AI_FORMAT_NWC: OH_AI_Format = OH_AI_Format(16);
    pub const OH_AI_FORMAT_NCW: OH_AI_Format = OH_AI_Format(17);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AI_Format(pub ::core::ffi::c_uint);
pub type OH_AI_TensorHandle = *mut ::core::ffi::c_void;
pub type OH_AI_AllocatorHandle = *mut ::core::ffi::c_void;
pub type OH_AI_ContextHandle = *mut ::core::ffi::c_void;
pub type OH_AI_DeviceInfoHandle = *mut ::core::ffi::c_void;
pub type OH_AI_ModelHandle = *mut ::core::ffi::c_void;
/// Defines a pointer to a training configuration object.
///
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_AI_TrainCfgHandle = *mut ::core::ffi::c_void;
#[repr(C)]
pub struct OH_AI_TensorHandleArray {
    pub handle_num: usize,
    pub handle_list: *mut OH_AI_TensorHandle,
}
#[repr(C)]
pub struct OH_AI_ShapeInfo {
    pub shape_num: usize,
    pub shape: [i64; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OH_AI_CallBackParam {
    pub node_name: *mut ::core::ffi::c_char,
    pub node_type: *mut ::core::ffi::c_char,
}
pub type OH_AI_KernelCallBack = ::core::option::Option<
    unsafe extern "C" fn(
        inputs: OH_AI_TensorHandleArray,
        outputs: OH_AI_TensorHandleArray,
        kernel_Info: OH_AI_CallBackParam,
    ) -> bool,
>;
extern "C" {
    pub fn OH_AI_TensorCreate(
        name: *const ::core::ffi::c_char,
        type_: OH_AI_DataType,
        shape: *const i64,
        shape_num: usize,
        data: *const ::core::ffi::c_void,
        data_len: usize,
    ) -> OH_AI_TensorHandle;
    pub fn OH_AI_TensorDestroy(tensor: *mut OH_AI_TensorHandle);
    pub fn OH_AI_TensorClone(tensor: OH_AI_TensorHandle) -> OH_AI_TensorHandle;
    pub fn OH_AI_TensorSetName(tensor: OH_AI_TensorHandle, name: *const ::core::ffi::c_char);
    pub fn OH_AI_TensorGetName(tensor: OH_AI_TensorHandle) -> *const ::core::ffi::c_char;
    pub fn OH_AI_TensorSetDataType(tensor: OH_AI_TensorHandle, type_: OH_AI_DataType);
    pub fn OH_AI_TensorGetDataType(tensor: OH_AI_TensorHandle) -> OH_AI_DataType;
    pub fn OH_AI_TensorSetShape(tensor: OH_AI_TensorHandle, shape: *const i64, shape_num: usize);
    pub fn OH_AI_TensorGetShape(tensor: OH_AI_TensorHandle, shape_num: *mut usize) -> *const i64;
    pub fn OH_AI_TensorSetFormat(tensor: OH_AI_TensorHandle, format: OH_AI_Format);
    pub fn OH_AI_TensorGetFormat(tensor: OH_AI_TensorHandle) -> OH_AI_Format;
    pub fn OH_AI_TensorSetData(tensor: OH_AI_TensorHandle, data: *mut ::core::ffi::c_void);
    pub fn OH_AI_TensorGetData(tensor: OH_AI_TensorHandle) -> *const ::core::ffi::c_void;
    pub fn OH_AI_TensorGetMutableData(tensor: OH_AI_TensorHandle) -> *mut ::core::ffi::c_void;
    pub fn OH_AI_TensorGetElementNum(tensor: OH_AI_TensorHandle) -> i64;
    pub fn OH_AI_TensorGetDataSize(tensor: OH_AI_TensorHandle) -> usize;
    pub fn OH_AI_TensorSetUserData(
        tensor: OH_AI_TensorHandle,
        data: *mut ::core::ffi::c_void,
        data_size: usize,
    ) -> OH_AI_Status;
    pub fn OH_AI_TensorGetAllocator(tensor: OH_AI_TensorHandle) -> OH_AI_AllocatorHandle;
    pub fn OH_AI_TensorSetAllocator(
        tensor: OH_AI_TensorHandle,
        allocator: OH_AI_AllocatorHandle,
    ) -> OH_AI_Status;
    pub fn OH_AI_ContextCreate() -> OH_AI_ContextHandle;
    pub fn OH_AI_ContextDestroy(context: *mut OH_AI_ContextHandle);
    pub fn OH_AI_ContextSetThreadNum(context: OH_AI_ContextHandle, thread_num: i32);
    pub fn OH_AI_ContextGetThreadNum(context: OH_AI_ContextHandle) -> i32;
    pub fn OH_AI_ContextSetThreadAffinityMode(
        context: OH_AI_ContextHandle,
        mode: ::core::ffi::c_int,
    );
    pub fn OH_AI_ContextGetThreadAffinityMode(context: OH_AI_ContextHandle) -> ::core::ffi::c_int;
    pub fn OH_AI_ContextSetThreadAffinityCoreList(
        context: OH_AI_ContextHandle,
        core_list: *const i32,
        core_num: usize,
    );
    pub fn OH_AI_ContextGetThreadAffinityCoreList(
        context: OH_AI_ContextHandle,
        core_num: *mut usize,
    ) -> *const i32;
    pub fn OH_AI_ContextSetEnableParallel(context: OH_AI_ContextHandle, is_parallel: bool);
    pub fn OH_AI_ContextGetEnableParallel(context: OH_AI_ContextHandle) -> bool;
    pub fn OH_AI_ContextAddDeviceInfo(
        context: OH_AI_ContextHandle,
        device_info: OH_AI_DeviceInfoHandle,
    );
    pub fn OH_AI_DeviceInfoCreate(device_type: OH_AI_DeviceType) -> OH_AI_DeviceInfoHandle;
    pub fn OH_AI_DeviceInfoDestroy(device_info: *mut OH_AI_DeviceInfoHandle);
    pub fn OH_AI_DeviceInfoSetProvider(
        device_info: OH_AI_DeviceInfoHandle,
        provider: *const ::core::ffi::c_char,
    );
    pub fn OH_AI_DeviceInfoGetProvider(
        device_info: OH_AI_DeviceInfoHandle,
    ) -> *const ::core::ffi::c_char;
    pub fn OH_AI_DeviceInfoSetProviderDevice(
        device_info: OH_AI_DeviceInfoHandle,
        device: *const ::core::ffi::c_char,
    );
    pub fn OH_AI_DeviceInfoGetProviderDevice(
        device_info: OH_AI_DeviceInfoHandle,
    ) -> *const ::core::ffi::c_char;
    pub fn OH_AI_DeviceInfoGetDeviceType(device_info: OH_AI_DeviceInfoHandle) -> OH_AI_DeviceType;
    pub fn OH_AI_DeviceInfoSetEnableFP16(device_info: OH_AI_DeviceInfoHandle, is_fp16: bool);
    pub fn OH_AI_DeviceInfoGetEnableFP16(device_info: OH_AI_DeviceInfoHandle) -> bool;
    pub fn OH_AI_DeviceInfoSetFrequency(
        device_info: OH_AI_DeviceInfoHandle,
        frequency: ::core::ffi::c_int,
    );
    pub fn OH_AI_DeviceInfoGetFrequency(device_info: OH_AI_DeviceInfoHandle) -> ::core::ffi::c_int;
    pub fn OH_AI_GetAllNNRTDeviceDescs(num: *mut usize) -> *mut NNRTDeviceDesc;
    pub fn OH_AI_GetElementOfNNRTDeviceDescs(
        descs: *mut NNRTDeviceDesc,
        index: usize,
    ) -> *mut NNRTDeviceDesc;
    pub fn OH_AI_DestroyAllNNRTDeviceDescs(desc: *mut *mut NNRTDeviceDesc);
    pub fn OH_AI_GetDeviceIdFromNNRTDeviceDesc(desc: *const NNRTDeviceDesc) -> usize;
    pub fn OH_AI_GetNameFromNNRTDeviceDesc(
        desc: *const NNRTDeviceDesc,
    ) -> *const ::core::ffi::c_char;
    pub fn OH_AI_GetTypeFromNNRTDeviceDesc(desc: *const NNRTDeviceDesc) -> OH_AI_NNRTDeviceType;
    pub fn OH_AI_CreateNNRTDeviceInfoByName(
        name: *const ::core::ffi::c_char,
    ) -> OH_AI_DeviceInfoHandle;
    pub fn OH_AI_CreateNNRTDeviceInfoByType(type_: OH_AI_NNRTDeviceType) -> OH_AI_DeviceInfoHandle;
    pub fn OH_AI_DeviceInfoSetDeviceId(device_info: OH_AI_DeviceInfoHandle, device_id: usize);
    pub fn OH_AI_DeviceInfoGetDeviceId(device_info: OH_AI_DeviceInfoHandle) -> usize;
    pub fn OH_AI_DeviceInfoSetPerformanceMode(
        device_info: OH_AI_DeviceInfoHandle,
        mode: OH_AI_PerformanceMode,
    );
    pub fn OH_AI_DeviceInfoGetPerformanceMode(
        device_info: OH_AI_DeviceInfoHandle,
    ) -> OH_AI_PerformanceMode;
    pub fn OH_AI_DeviceInfoSetPriority(
        device_info: OH_AI_DeviceInfoHandle,
        priority: OH_AI_Priority,
    );
    pub fn OH_AI_DeviceInfoGetPriority(device_info: OH_AI_DeviceInfoHandle) -> OH_AI_Priority;
    pub fn OH_AI_DeviceInfoAddExtension(
        device_info: OH_AI_DeviceInfoHandle,
        name: *const ::core::ffi::c_char,
        value: *const ::core::ffi::c_char,
        value_size: usize,
    ) -> OH_AI_Status;
    /// Create a model object.
    ///
    ///
    /// # Returns
    ///
    /// * Model object handle.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelCreate() -> OH_AI_ModelHandle;
    /// Destroy the model object.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle address.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelDestroy(model: *mut OH_AI_ModelHandle);
    /// Build the model from model file buffer so that it can run on a device.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `model_data` - Define the buffer read from a model file.
    ///
    /// * `data_size` - Define bytes number of model file buffer.
    ///
    /// * `model_type` - Define The type of model file.
    ///
    /// * `model_context` - Define the context used to store options during execution.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelBuild(
        model: OH_AI_ModelHandle,
        model_data: *const ::core::ffi::c_void,
        data_size: usize,
        model_type: OH_AI_ModelType,
        model_context: OH_AI_ContextHandle,
    ) -> OH_AI_Status;
    /// Load and build the model from model path so that it can run on a device.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `model_path` - Define the model file path.
    ///
    /// * `model_type` - Define The type of model file.
    ///
    /// * `model_context` - Define the context used to store options during execution.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelBuildFromFile(
        model: OH_AI_ModelHandle,
        model_path: *const ::core::ffi::c_char,
        model_type: OH_AI_ModelType,
        model_context: OH_AI_ContextHandle,
    ) -> OH_AI_Status;
    /// Resizes the shapes of inputs.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `inputs` - The array that includes all input tensor handles.
    ///
    /// * `shape_infos` - Defines the new shapes of inputs, should be consistent with inputs.
    ///
    /// * `shape_info_num` - The num of shape_infos.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelResize(
        model: OH_AI_ModelHandle,
        inputs: OH_AI_TensorHandleArray,
        shape_infos: *mut OH_AI_ShapeInfo,
        shape_info_num: usize,
    ) -> OH_AI_Status;
    /// Inference model.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `inputs` - The array that includes all input tensor handles.
    ///
    /// * `outputs` - The array that includes all output tensor handles.
    ///
    /// * `before` - CallBack before predict.
    ///
    /// * `after` - CallBack after predict.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelPredict(
        model: OH_AI_ModelHandle,
        inputs: OH_AI_TensorHandleArray,
        outputs: *mut OH_AI_TensorHandleArray,
        before: OH_AI_KernelCallBack,
        after: OH_AI_KernelCallBack,
    ) -> OH_AI_Status;
    /// Obtains all input tensor handles of the model.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// # Returns
    ///
    /// * The array that includes all input tensor handles.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelGetInputs(model: OH_AI_ModelHandle) -> OH_AI_TensorHandleArray;
    /// Obtains all output tensor handles of the model.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// # Returns
    ///
    /// * The array that includes all output tensor handles.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelGetOutputs(model: OH_AI_ModelHandle) -> OH_AI_TensorHandleArray;
    /// Obtains the input tensor handle of the model by name.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `tensor_name` - The name of tensor.
    ///
    /// # Returns
    ///
    /// * The input tensor handle with the given name, if the name is not found, an NULL is returned.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelGetInputByTensorName(
        model: OH_AI_ModelHandle,
        tensor_name: *const ::core::ffi::c_char,
    ) -> OH_AI_TensorHandle;
    /// Obtains the output tensor handle of the model by name.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `tensor_name` - The name of tensor.
    ///
    /// # Returns
    ///
    /// * The output tensor handle with the given name, if the name is not found, an NULL is returned.
    ///
    /// Available since API-level: 9
    pub fn OH_AI_ModelGetOutputByTensorName(
        model: OH_AI_ModelHandle,
        tensor_name: *const ::core::ffi::c_char,
    ) -> OH_AI_TensorHandle;
    /// Create a TrainCfg object. Only valid for Lite Train.
    ///
    ///
    /// # Returns
    ///
    /// * TrainCfg object handle.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainCfgCreate() -> OH_AI_TrainCfgHandle;
    /// Destroy the train_cfg object. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `train_cfg` - TrainCfg object handle.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainCfgDestroy(train_cfg: *mut OH_AI_TrainCfgHandle);
    /// Obtains part of the name that identify a loss kernel. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `train_cfg` - TrainCfg object handle.
    ///
    /// * `num` - The num of loss_name.
    ///
    /// # Returns
    ///
    /// * loss_name.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainCfgGetLossName(
        train_cfg: OH_AI_TrainCfgHandle,
        num: *mut usize,
    ) -> *mut *mut ::core::ffi::c_char;
    /// Set part of the name that identify a loss kernel. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `train_cfg` - TrainCfg object handle.
    ///
    /// * `loss_name` - Define part of the name that identify a loss kernel.
    ///
    /// * `num` - The num of loss_name.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainCfgSetLossName(
        train_cfg: OH_AI_TrainCfgHandle,
        loss_name: *mut *const ::core::ffi::c_char,
        num: usize,
    );
    /// Obtains optimization level of the train_cfg. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `train_cfg` - TrainCfg object handle.
    ///
    /// # Returns
    ///
    /// * OH_AI_OptimizationLevel.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainCfgGetOptimizationLevel(
        train_cfg: OH_AI_TrainCfgHandle,
    ) -> OH_AI_OptimizationLevel;
    /// Set optimization level of the train_cfg. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `train_cfg` - TrainCfg object handle.
    ///
    /// * `level` - The optimization level of train_cfg.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainCfgSetOptimizationLevel(
        train_cfg: OH_AI_TrainCfgHandle,
        level: OH_AI_OptimizationLevel,
    );
    /// Build the train model from model buffer so that it can run on a device. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `model_data` - Define the buffer read from a model file.
    ///
    /// * `data_size` - Define bytes number of model file buffer.
    ///
    /// * `model_type` - Define The type of model file.
    ///
    /// * `model_context` - Define the context used to store options during execution.
    ///
    /// * `train_cfg` - Define the config used by training.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainModelBuild(
        model: OH_AI_ModelHandle,
        model_data: *const ::core::ffi::c_void,
        data_size: usize,
        model_type: OH_AI_ModelType,
        model_context: OH_AI_ContextHandle,
        train_cfg: OH_AI_TrainCfgHandle,
    ) -> OH_AI_Status;
    /// Build the train model from model file buffer so that it can run on a device. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `model_path` - Define the model path.
    ///
    /// * `model_type` - Define The type of model file.
    ///
    /// * `model_context` - Define the context used to store options during execution.
    ///
    /// * `train_cfg` - Define the config used by training.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_TrainModelBuildFromFile(
        model: OH_AI_ModelHandle,
        model_path: *const ::core::ffi::c_char,
        model_type: OH_AI_ModelType,
        model_context: OH_AI_ContextHandle,
        train_cfg: OH_AI_TrainCfgHandle,
    ) -> OH_AI_Status;
    /// Train model by step. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `before` - CallBack before predict.
    ///
    /// * `after` - CallBack after predict.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_RunStep(
        model: OH_AI_ModelHandle,
        before: OH_AI_KernelCallBack,
        after: OH_AI_KernelCallBack,
    ) -> OH_AI_Status;
    /// Sets the Learning Rate of the training. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `learning_rate` - to set.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status of operation.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelSetLearningRate(model: OH_AI_ModelHandle, learning_rate: f32)
        -> OH_AI_Status;
    /// Obtains the Learning Rate of the optimizer. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// # Returns
    ///
    /// * Learning rate. 0.0 if no optimizer was found.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelGetLearningRate(model: OH_AI_ModelHandle) -> f32;
    /// Obtains all weights tensors of the model. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// # Returns
    ///
    /// * The vector that includes all gradient tensors.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelGetWeights(model: OH_AI_ModelHandle) -> OH_AI_TensorHandleArray;
    /// update weights tensors of the model. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `new_weights` - A vector new weights.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelUpdateWeights(
        model: OH_AI_ModelHandle,
        new_weights: OH_AI_TensorHandleArray,
    ) -> OH_AI_Status;
    /// Get the model running mode.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// # Returns
    ///
    /// * Is Train Mode or not.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelGetTrainMode(model: OH_AI_ModelHandle) -> bool;
    /// Set the model running mode. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `train` - True means model runs in Train Mode, otherwise Eval Mode.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelSetTrainMode(model: OH_AI_ModelHandle, train: bool) -> OH_AI_Status;
    /// Setup training with virtual batches. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `virtual_batch_multiplier` - Virtual batch multiplier, use any number < 1 to disable.
    ///
    /// * `lr` - Learning rate to use for virtual batch, -1 for internal configuration.
    ///
    /// * `momentum` - Batch norm momentum to use for virtual batch, -1 for internal configuration.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ModelSetupVirtualBatch(
        model: OH_AI_ModelHandle,
        virtual_batch_multiplier: ::core::ffi::c_int,
        lr: f32,
        momentum: f32,
    ) -> OH_AI_Status;
    /// Export training model from file. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - The model data.
    ///
    /// * `model_type` - The model file type.
    ///
    /// * `model_file` - The exported model file.
    ///
    /// * `quantization_type` - The quantification type.
    ///
    /// * `export_inference_only` - Whether to export a reasoning only model.
    ///
    /// * `output_tensor_name` - The set the name of the output tensor of the exported reasoning model, default as
    /// empty, and export the complete reasoning model.
    ///
    /// * `num` - The number of output_tensor_name.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ExportModel(
        model: OH_AI_ModelHandle,
        model_type: OH_AI_ModelType,
        model_file: *const ::core::ffi::c_char,
        quantization_type: OH_AI_QuantizationType,
        export_inference_only: bool,
        output_tensor_name: *mut *mut ::core::ffi::c_char,
        num: usize,
    ) -> OH_AI_Status;
    /// Export training model from buffer. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - The model data.
    ///
    /// * `model_type` - The model file type.
    ///
    /// * `model_data` - The exported model buffer.
    ///
    /// * `data_size` - The exported model buffer size.
    ///
    /// * `quantization_type` - The quantification type.
    ///
    /// * `export_inference_only` - Whether to export a reasoning only model.
    ///
    /// * `output_tensor_name` - The set the name of the output tensor of the exported reasoning model, default as
    /// empty, and export the complete reasoning model.
    ///
    /// * `num` - The number of output_tensor_name.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ExportModelBuffer(
        model: OH_AI_ModelHandle,
        model_type: OH_AI_ModelType,
        model_data: *mut ::core::ffi::c_void,
        data_size: *mut usize,
        quantization_type: OH_AI_QuantizationType,
        export_inference_only: bool,
        output_tensor_name: *mut *mut ::core::ffi::c_char,
        num: usize,
    ) -> OH_AI_Status;
    /// Export model's weights, which can be used in micro only. Only valid for Lite Train.
    ///
    /// # Arguments
    ///
    /// * `model` - The model data.
    ///
    /// * `model_type` - The model file type.
    ///
    /// * `weight_file` - The path of exported weight file.
    ///
    /// * `is_inference` - Whether to export weights from a reasoning model. Currently, only support this is `true`.
    ///
    /// * `enable_fp16` - Float-weight is whether to be saved in float16 format.
    ///
    /// * `changeable_weights_name` - The set the name of these weight tensors, whose shape is changeable.
    ///
    /// * `num` - The number of changeable_weights_name.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_AI_ExportWeightsCollaborateWithMicro(
        model: OH_AI_ModelHandle,
        model_type: OH_AI_ModelType,
        weight_file: *const ::core::ffi::c_char,
        is_inference: bool,
        enable_fp16: bool,
        changeable_weights_name: *mut *mut ::core::ffi::c_char,
        num: usize,
    ) -> OH_AI_Status;
    /// Load the config file of the model.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `config_path` - The config file path.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_AI_ModelLoadConfig(
        model: OH_AI_ModelHandle,
        config_path: *const ::core::ffi::c_char,
    ) -> OH_AI_Status;
    /// Run model inference with configuration.
    ///
    /// # Arguments
    ///
    /// * `model` - Model object handle.
    ///
    /// * `inputs` - The array that includes all input tensor handles.
    ///
    /// * `outputs` - The array that includes all output tensor handles.
    ///
    /// * `config` - The config buffer of predition, as format of key-values.
    ///
    /// * `before` - CallBack before predict.
    ///
    /// * `after` - CallBack after predict.
    ///
    /// # Returns
    ///
    /// * OH_AI_Status.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AI_ModelPredictWithConfig(
        model: OH_AI_ModelHandle,
        inputs: OH_AI_TensorHandleArray,
        outputs: *mut OH_AI_TensorHandleArray,
        config: *const ::core::ffi::c_char,
        before: OH_AI_KernelCallBack,
        after: OH_AI_KernelCallBack,
    ) -> OH_AI_Status;
}
