// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::camera::*;
use crate::photo_native::OH_PhotoNative;
use ohos_sys_opaque_types::OH_MediaAsset;

/// Photo output object
///
/// A pointer can be created using [`Camera_PhotoOutput`] method.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
pub struct Camera_PhotoOutput {
    _unused: [u8; 0],
}
/// Photo output frame start callback to be called in [`PhotoOutput_Callbacks`].
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PhotoOutput_OnFrameStart =
    ::core::option::Option<unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput)>;
/// Photo output frame shutter callback to be called in [`PhotoOutput_Callbacks`].
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `info` - the [`Camera_FrameShutterInfo`] which delivered by the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PhotoOutput_OnFrameShutter = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, info: *mut Camera_FrameShutterInfo),
>;
/// Photo output frame end callback to be called in [`PhotoOutput_Callbacks`].
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `frameCount` - the frame count which delivered by the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PhotoOutput_OnFrameEnd = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, frameCount: i32),
>;
/// Photo output error callback to be called in [`PhotoOutput_Callbacks`].
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `errorCode` - the [`Camera_ErrorCode`] of the photo output.
///
/// [`CAMERA_SERVICE_FATAL_ERROR`]
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PhotoOutput_OnError = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, errorCode: Camera_ErrorCode),
>;
/// Photo output capture end callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `frameCount` - the frameCount which is delivered by the callback.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_CaptureEnd = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, frameCount: i32),
>;
/// Photo output capture start with infomation callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `Info` - the [`Camera_CaptureStartInfo`] which is delivered by the callback..
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_CaptureStartWithInfo = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, Info: *mut Camera_CaptureStartInfo),
>;
/// Photo output eframe shutter end callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `Info` - the [`Camera_CaptureStartInfo`] which is delivered by the callback.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_OnFrameShutterEnd = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, Info: *mut Camera_FrameShutterInfo),
>;
/// Photo output capture ready callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_CaptureReady =
    ::core::option::Option<unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput)>;
/// Photo output estimated capture duration callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `duration` - the duration which is delivered by the callback.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_EstimatedCaptureDuration = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, duration: i64),
>;
/// Photo output available high-resolution images callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `photo` - the [`OH_PhotoNative`] which delivered by the callback.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_PhotoAvailable = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, photo: *mut OH_PhotoNative),
>;
/// Photo output photo asset available callback.
///
/// # Arguments
///
/// * `photoOutput` - the [`Camera_PhotoOutput`] which deliver the callback.
///
/// * `photoAsset` - the [`OH_MediaAsset`] which delivered by the callback.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_PhotoOutput_PhotoAssetAvailable = ::core::option::Option<
    unsafe extern "C" fn(photoOutput: *mut Camera_PhotoOutput, photoAsset: *mut OH_MediaAsset),
>;
/// A listener for photo output.
///
/// [`OH_PhotoOutput_RegisterCallback`]
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PhotoOutput_Callbacks {
    /// Photo output frame start event.
    pub onFrameStart: OH_PhotoOutput_OnFrameStart,
    /// Photo output frame shutter event.
    pub onFrameShutter: OH_PhotoOutput_OnFrameShutter,
    /// Photo output frame end event.
    pub onFrameEnd: OH_PhotoOutput_OnFrameEnd,
    /// Photo output error event.
    pub onError: OH_PhotoOutput_OnError,
}
extern "C" {
    /// Register photo output change event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`PhotoOutput_Callbacks`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PhotoOutput_RegisterCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: *mut PhotoOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Unregister photo output change event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`PhotoOutput_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PhotoOutput_UnregisterCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: *mut PhotoOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Register capture start event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_CaptureStartWithInfo`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterCaptureStartWithInfoCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_CaptureStartWithInfo,
    ) -> Camera_ErrorCode;
    /// Gets the photo rotation angle.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to get the photo rotation angle.
    ///
    /// * `deviceDegree` - the current device rotation degree.
    ///
    /// * `imageRotation` - the [`Camera_ImageRotation`] result of photo rotation angle.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_GetPhotoRotation(
        photoOutput: *mut Camera_PhotoOutput,
        deviceDegree: ::core::ffi::c_int,
        imageRotation: *mut Camera_ImageRotation,
    ) -> Camera_ErrorCode;
    /// Gets the photo rotation angle without device degree.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to get the photo rotation angle.
    ///
    /// * `imageRotation` - the [`Camera_ImageRotation`] result of photo rotation angle.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_PhotoOutput_GetPhotoRotationWithoutDeviceDegree(
        photoOutput: *mut Camera_PhotoOutput,
        imageRotation: *mut Camera_ImageRotation,
    ) -> Camera_ErrorCode;
    /// Unregister capture start event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_CaptureStartWithInfo`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterCaptureStartWithInfoCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_CaptureStartWithInfo,
    ) -> Camera_ErrorCode;
    /// Register capture end event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_CaptureEnd`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterCaptureEndCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_CaptureEnd,
    ) -> Camera_ErrorCode;
    /// Unregister capture end event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_CaptureEnd`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterCaptureEndCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_CaptureEnd,
    ) -> Camera_ErrorCode;
    /// Register frame shutter end event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_OnFrameShutterEnd`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterFrameShutterEndCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_OnFrameShutterEnd,
    ) -> Camera_ErrorCode;
    /// Unregister frame shutter end event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_OnFrameShutterEnd`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterFrameShutterEndCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_OnFrameShutterEnd,
    ) -> Camera_ErrorCode;
    /// Register capture ready event callback. After receiving the callback, can proceed to the next capture.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_CaptureReady`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterCaptureReadyCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_CaptureReady,
    ) -> Camera_ErrorCode;
    /// Unregister capture ready event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_CaptureReady`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterCaptureReadyCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_CaptureReady,
    ) -> Camera_ErrorCode;
    /// Register estimated capture duration event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_EstimatedCaptureDuration`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterEstimatedCaptureDurationCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_EstimatedCaptureDuration,
    ) -> Camera_ErrorCode;
    /// Unregister estimated capture duration event callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_EstimatedCaptureDuration`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterEstimatedCaptureDurationCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_EstimatedCaptureDuration,
    ) -> Camera_ErrorCode;
    /// Register photo output photo available callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_PhotoAvailable`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterPhotoAvailableCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_PhotoAvailable,
    ) -> Camera_ErrorCode;
    /// Unregister photo output photo available callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`PhotoOutput_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterPhotoAvailableCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_PhotoAvailable,
    ) -> Camera_ErrorCode;
    /// Register photo output photo asset available callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_PhotoAssetAvailable`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_RegisterPhotoAssetAvailableCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_PhotoAssetAvailable,
    ) -> Camera_ErrorCode;
    /// Unregister photo output photo asset available callback.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance.
    ///
    /// * `callback` - the [`OH_PhotoOutput_PhotoAssetAvailable`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_UnregisterPhotoAssetAvailableCallback(
        photoOutput: *mut Camera_PhotoOutput,
        callback: OH_PhotoOutput_PhotoAssetAvailable,
    ) -> Camera_ErrorCode;
    /// Capture photo.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to capture photo.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SESSION_NOT_RUNNING`] if the capture session not running.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PhotoOutput_Capture(photoOutput: *mut Camera_PhotoOutput) -> Camera_ErrorCode;
    /// Capture photo with capture setting.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to capture photo.
    ///
    /// * `setting` - the [`Camera_PhotoCaptureSetting`] to used to capture photo.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SESSION_NOT_RUNNING`] if the capture session not running.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PhotoOutput_Capture_WithCaptureSetting(
        photoOutput: *mut Camera_PhotoOutput,
        setting: Camera_PhotoCaptureSetting,
    ) -> Camera_ErrorCode;
    /// Release photo output.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance to released.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PhotoOutput_Release(photoOutput: *mut Camera_PhotoOutput) -> Camera_ErrorCode;
    /// Check whether to support mirror photo.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to check whether mirror supported.
    ///
    /// * `isSupported` - the result of whether mirror supported.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PhotoOutput_IsMirrorSupported(
        photoOutput: *mut Camera_PhotoOutput,
        isSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Enable mirror for photo capture.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to configure mirror.
    ///
    /// * `enabled` - the flag indicates whether mirror is enabled.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_PhotoOutput_EnableMirror(
        photoOutput: *mut Camera_PhotoOutput,
        enabled: bool,
    ) -> Camera_ErrorCode;
    /// Get active photo output profile.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance to deliver active profile.
    ///
    /// * `profile` - the active [`Camera_Profile`] to be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_GetActiveProfile(
        photoOutput: *mut Camera_PhotoOutput,
        profile: *mut *mut Camera_Profile,
    ) -> Camera_ErrorCode;
    /// Delete photo profile instance.
    ///
    /// # Arguments
    ///
    /// * `profile` - the [`Camera_Profile`] instance to deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_DeleteProfile(profile: *mut Camera_Profile) -> Camera_ErrorCode;
    /// Check whether to support moving photo.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to check whether moving photo supported.
    ///
    /// * `isSupported` - the result of whether moving photo supported.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_IsMovingPhotoSupported(
        photoOutput: *mut Camera_PhotoOutput,
        isSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Enable moving photo or not.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to enable moving photo or not.
    ///
    /// * `enabled` - the flag of enable moving photo or not.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PhotoOutput_EnableMovingPhoto(
        photoOutput: *mut Camera_PhotoOutput,
        enabled: bool,
    ) -> Camera_ErrorCode;
    /// Check whether to support photo quality prioritization.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to check whether photo quality prioritization supported.
    ///
    /// * `qualityPrioritization` - the [`Camera_PhotoQualityPrioritization`] instance indicating quality preference.
    ///
    /// * `isSupported` - the result of whether quality prioritization is supported.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_PhotoOutput_IsPhotoQualityPrioritizationSupported(
        photoOutput: *mut Camera_PhotoOutput,
        qualityPrioritization: Camera_PhotoQualityPrioritization,
        isSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Set photo quality prioritization.
    ///
    /// # Arguments
    ///
    /// * `photoOutput` - the [`Camera_PhotoOutput`] instance which used to configure photo quality prioritization.
    ///
    /// * `qualityPrioritization` - the [`Camera_PhotoQualityPrioritization`] instance indicating the choice of quality or speed.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_OPERATION_NOT_ALLOWED`] if operation not allowed.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_PhotoOutput_SetPhotoQualityPrioritization(
        photoOutput: *mut Camera_PhotoOutput,
        qualityPrioritization: Camera_PhotoQualityPrioritization,
    ) -> Camera_ErrorCode;
}
