// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::clouddiskmanager::cloud_disk_error_code::CloudDiskResult;

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
impl CloudDisk_SyncState {
    /// The cloud disk is idle and not performing any synchronization.
    pub const IDLE: CloudDisk_SyncState = CloudDisk_SyncState(0);
    /// The cloud disk is currently synchronizing.
    pub const SYNCING: CloudDisk_SyncState = CloudDisk_SyncState(1);
    /// The cloud disk synchronization completed successfully.
    pub const SYNC_SUCCEEDED: CloudDisk_SyncState = CloudDisk_SyncState(2);
    /// The cloud disk synchronization failed.
    pub const SYNC_FAILED: CloudDisk_SyncState = CloudDisk_SyncState(3);
    /// The cloud disk synchronization was canceled.
    pub const SYNC_CANCELED: CloudDisk_SyncState = CloudDisk_SyncState(4);
    /// The cloud disk synchronization encountered a conflict.
    pub const SYNC_CONFLICTED: CloudDisk_SyncState = CloudDisk_SyncState(5);
}
#[repr(transparent)]
/// Enumerates the synchronization states of a cloud disk.
///
/// This enumeration defines the possible states during cloud disk synchronization.
///
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CloudDisk_SyncState(pub ::core::ffi::c_uint);
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
impl CloudDisk_OperationType {
    /// Create a file or folder.
    pub const CREATE: CloudDisk_OperationType = CloudDisk_OperationType(0);
    /// Delete a file or folder.
    pub const DELETE: CloudDisk_OperationType = CloudDisk_OperationType(1);
    /// Move a file or folder from a source location.
    pub const MOVE_FROM: CloudDisk_OperationType = CloudDisk_OperationType(2);
    /// Move a file or folder to a target location.
    pub const MOVE_TO: CloudDisk_OperationType = CloudDisk_OperationType(3);
    /// Close a file after writing to operations.
    pub const CLOSE_WRITE: CloudDisk_OperationType = CloudDisk_OperationType(4);
    /// The sync folder path is invalid.
    pub const SYNC_FOLDER_INVALID: CloudDisk_OperationType = CloudDisk_OperationType(5);
}
#[repr(transparent)]
/// Enumerates the operation types for file changes in the cloud disk.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CloudDisk_OperationType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
impl CloudDisk_ErrorReason {
    /// The input parameter is invalid.
    pub const INVALID_ARGUMENT: CloudDisk_ErrorReason = CloudDisk_ErrorReason(0);
    /// The specified file does not exist.
    pub const NO_SUCH_FILE: CloudDisk_ErrorReason = CloudDisk_ErrorReason(1);
    /// There is no space left on the device.
    pub const NO_SPACE_LEFT: CloudDisk_ErrorReason = CloudDisk_ErrorReason(2);
    /// The operation is out of the valid range.
    pub const OUT_OF_RANGE: CloudDisk_ErrorReason = CloudDisk_ErrorReason(3);
    /// The sync state is not set for the cloud disk.
    pub const NO_SYNC_STATE: CloudDisk_ErrorReason = CloudDisk_ErrorReason(4);
}
#[repr(transparent)]
/// Enumerates the error reasons for file synchronization failures.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CloudDisk_ErrorReason(pub ::core::ffi::c_uint);
/// Represents file path information.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_PathInfo {
    /// The file path as a null-terminated string.
    pub value: *mut ::core::ffi::c_char,
    /// The length of the file path, excluding the null terminator.
    pub length: usize,
}
/// Defines the file ID information.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
pub type CloudDisk_FileIdInfo = CloudDisk_PathInfo;
/// Defines the sync folder path information.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
pub type CloudDisk_SyncFolderPath = CloudDisk_PathInfo;
/// Defines file sync states.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_FileSyncState {
    /// Indicates the file path information.
    pub filePathInfo: CloudDisk_PathInfo,
    /// Indicates the synchronization state of the file.
    pub syncState: CloudDisk_SyncState,
}
/// Defines the data structure for a single file change event in the sync folder.
///
/// This structure contains detailed information about a file change, including its unique ID,
/// parent ID, relative path, change type, file size, and timestamps.
///
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_ChangeData {
    /// The update sequence number for the change event.
    /// Increases by 1 each time the file is changed, and is monotonically increasing.
    /// Used for incremental change queries.
    pub updateSequenceNumber: u64,
    /// The globally unique file ID. Remains unchanged during the lifecycle of the file.
    pub fileId: CloudDisk_FileIdInfo,
    /// The parent file ID information.
    pub parentFileId: CloudDisk_FileIdInfo,
    /// The relative path information of the file.
    pub relativePathInfo: CloudDisk_PathInfo,
    /// The type of operation for this file change (such as create, delete, move, etc.).
    pub operationType: CloudDisk_OperationType,
    /// The size of the file in bytes.
    pub size: u64,
    /// The last modified time of the file, in milliseconds.
    pub mtime: u64,
    /// The timestamp of the change event, in milliseconds.
    pub timeStamp: u64,
}
/// Represents the result of querying file changes in a sync folder.
///
/// This structure contains the incremental change data for files in a sync folder,
/// including the next update sequence number, end-of-log flag, and an array of change data items.
///
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_ChangesResult {
    /// The next update sequence number for incremental queries.
    pub nextUsn: u64,
    /// Indicates whether the end of the change log is reached.
    /// If true, all file changes have been returned.
    pub isEof: bool,
    /// The number of change data items in the array.
    pub bufferLength: usize,
    /// The array of file change data items.
    pub changeDatas: __IncompleteArrayField<CloudDisk_ChangeData>,
}
/// Represents a failed file in a synchronization operation.
///
/// This structure contains the file path information and the specific error reason for the failure.
///
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_FailedList {
    /// The file path information of the failed file.
    pub pathInfo: CloudDisk_PathInfo,
    /// The error reason for the file synchronization failure.
    pub errorReason: CloudDisk_ErrorReason,
}
/// Represents the result of a file synchronization operation.
///
/// This structure contains the absolute path of the file, the synchronization result,
/// and either the sync state or the error reason depending on the operation outcome.
///
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_ResultList {
    /// The absolute path information of the file.
    pub pathInfo: CloudDisk_PathInfo,
    /// Indicates whether the synchronization operation was successful.
    /// If true, syncState is valid; if false, errorReason is valid.
    pub isSuccess: bool,
    /// The synchronization state of the file. Valid only if isSuccess is true.
    pub syncState: CloudDisk_SyncState,
    /// The error reason for the file synchronization failure. Valid only if isSuccess is false.
    pub errorReason: CloudDisk_ErrorReason,
}
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
impl CloudDisk_SyncFolderState {
    /// Indicates that the state of sync folder is inactive.
    pub const INACTIVE: CloudDisk_SyncFolderState = CloudDisk_SyncFolderState(0);
    /// Indicates that the state of sync folder is active.
    pub const ACTIVE: CloudDisk_SyncFolderState = CloudDisk_SyncFolderState(1);
}
#[repr(transparent)]
/// Enumerates the state of sync folder.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CloudDisk_SyncFolderState(pub ::core::ffi::c_uint);
/// Defines the sync folder displayName info of cloud disk.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_DisplayNameInfo {
    /// Indicates the displayNameResId of sync folder.
    pub displayNameResId: u32,
    /// Indicates the user-defined alias.
    pub customAlias: *mut ::core::ffi::c_char,
    /// Indicates the length of the customAlias.
    pub customAliasLength: usize,
}
/// Defines the sync folder of cloud disk.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[repr(C)]
pub struct CloudDisk_SyncFolder {
    /// Indicates the path of sync folder.
    pub path: CloudDisk_SyncFolderPath,
    /// Indicates the state of sync folder.
    pub state: CloudDisk_SyncFolderState,
    /// Indicates the displayName info of sync folder.
    pub displayNameInfo: CloudDisk_DisplayNameInfo,
}
extern "C" {
    /// Registers a callback function to notify the application of sync folder changes.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path information.
    ///
    /// * `callback` - Indicates the callback function to be registered.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the callback function is registered successfully;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_RegisterSyncFolderChanges(
        syncFolderPath: CloudDisk_SyncFolderPath,
        callback: ::core::option::Option<
            unsafe extern "C" fn(
                syncFolderPath: CloudDisk_SyncFolderPath,
                changeDatas: *const CloudDisk_ChangeData,
                bufferLength: usize,
            ),
        >,
    ) -> CloudDiskResult;
    /// Unregisters a callback function for sync folder changes.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path information.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the callback function is unregistered successfully;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_UnregisterSyncFolderChanges(
        syncFolderPath: CloudDisk_SyncFolderPath,
    ) -> CloudDiskResult;
    /// Gets the change datas of specified folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path information.
    ///
    /// * `startUsn` - Indicates the start update sequence number.
    ///
    /// * `count` - Indicates the number of files.
    ///
    /// * `changesResult` - Indicates the result of querying file changes. For details, see [`CloudDisk_ChangesResult`].
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the callback function is unregistered successfully;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_GetSyncFolderChanges(
        syncFolderPath: CloudDisk_SyncFolderPath,
        startUsn: u64,
        count: usize,
        changesResult: *mut *mut CloudDisk_ChangesResult,
    ) -> CloudDiskResult;
    /// Sets the synchronization state for specified files in a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path information.
    ///
    /// * `fileSyncStates` - The array of [`CloudDisk_FileSyncState`] specifying the file paths and their target sync
    /// <br> states.
    ///
    /// * `bufferLength` - The number of files to set.
    ///
    /// * `failedLists` - Output parameter. Returns a pointer to an array of [`CloudDisk_FailedList`] for files that
    /// <br> failed to set.
    ///
    /// * `failedCount` - Output parameter. Returns the number of failed files in [`failedLists`].
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> otherwise, returns an error code defined in [`cloud_disk_error_code.h`].
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_SetFileSyncStates(
        syncFolderPath: CloudDisk_SyncFolderPath,
        fileSyncStates: *const CloudDisk_FileSyncState,
        bufferLength: usize,
        failedLists: *mut *mut CloudDisk_FailedList,
        failedCount: *mut usize,
    ) -> CloudDiskResult;
    /// Queries the synchronization state of specified files in a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path information.
    ///
    /// * `paths` - The array of file paths to query.
    ///
    /// * `bufferLength` - The number of file paths in the array.
    ///
    /// * `resultLists` - Output parameter. Returns a pointer to an array of [`CloudDisk_ResultList`] containing the
    /// <br> query results.
    ///
    /// * `resultCount` - Output parameter. Returns the number of results in [`resultLists`].
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the query is successful;
    /// <br> otherwise, returns an error code defined in [`cloud_disk_error_code.h`].
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_GetFileSyncStates(
        syncFolderPath: CloudDisk_SyncFolderPath,
        paths: *const CloudDisk_PathInfo,
        bufferLength: usize,
        resultLists: *mut *mut CloudDisk_ResultList,
        resultCount: *mut usize,
    ) -> CloudDiskResult;
    /// Registers a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolder` - Indicates the sync folder.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_RegisterSyncFolder(
        syncFolder: *const CloudDisk_SyncFolder,
    ) -> CloudDiskResult;
    /// Unregisters a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_UnregisterSyncFolder(
        syncFolderPath: CloudDisk_SyncFolderPath,
    ) -> CloudDiskResult;
    /// Activates a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_ActiveSyncFolder(
        syncFolderPath: CloudDisk_SyncFolderPath,
    ) -> CloudDiskResult;
    /// Deactivates a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_DeactiveSyncFolder(
        syncFolderPath: CloudDisk_SyncFolderPath,
    ) -> CloudDiskResult;
    /// Gets the sync folders.
    ///
    /// # Arguments
    ///
    /// * `syncFolders` - Output parameter. Returns the array of [`CloudDisk_SyncFolder`] to store the sync folders.
    ///
    /// * `count` - Output parameter. Returns the number of sync folders.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_GetSyncFolders(
        syncFolders: *mut *mut CloudDisk_SyncFolder,
        count: *mut usize,
    ) -> CloudDiskResult;
    /// Updates the display name of a sync folder.
    ///
    /// # Arguments
    ///
    /// * `syncFolderPath` - Indicates the sync folder path.
    ///
    /// * `customAlias` - Indicates the user-defined alias.
    ///
    /// * `customAliasLength` - Indicates the length of the customAlias.
    ///
    /// # Returns
    ///
    /// * Returns [`CLOUD_DISK_OK`] if the operation is successful;
    /// <br> returns an error code defined in [`cloud_disk_error_code.h`] otherwise.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_CloudDisk_UpdateCustomAlias(
        syncFolderPath: CloudDisk_SyncFolderPath,
        customAlias: *const ::core::ffi::c_char,
        customAliasLength: usize,
    ) -> CloudDiskResult;
}
