// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::avplaybackstate::OH_AVSession_AVPlaybackState;
use crate::avqueueitem::OH_AVSession_AVQueueItem;
use crate::avsession::OH_AVCastController;
use crate::avsession_base::*;
use crate::avsession_errors::{AVSessionCallback_Result, AVSession_ErrCode};

/// Declaring the callback struct for playback state change
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_PlaybackStateChanged = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        playbackState: *mut OH_AVSession_AVPlaybackState,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for media item change
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_MediaItemChange = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        avQueueItem: *mut OH_AVSession_AVQueueItem,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for Play Next
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_PlayNext = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for Play Previous
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_PlayPrevious = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for seekDone
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_SeekDone = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        position: i32,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for EndOfStream
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_EndOfStream = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for cast play error
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVCastControllerCallback_Error = ::core::option::Option<
    unsafe extern "C" fn(
        avcastcontroller: *mut OH_AVCastController,
        userData: *mut ::core::ffi::c_void,
        error: AVSession_ErrCode,
    ) -> AVSessionCallback_Result,
>;
extern "C" {
    /// Request to destory the avcastcontroller.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`] The param of avcastcontroller is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_Destroy(
        avcastcontroller: *mut OH_AVCastController,
    ) -> AVSession_ErrCode;
    /// Get the playback status of the current player.
    /// Do not release the playbackState pointer separately.
    /// It will be destroyed when [`OH_AVCastController_Destroy`] is called.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `playbackState` - The returned playbackState
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of playbackState is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_GetPlaybackState(
        avcastcontroller: *mut OH_AVCastController,
        playbackState: *mut *mut OH_AVSession_AVPlaybackState,
    ) -> AVSession_ErrCode;
    /// Request to register playback state changed callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `filter` - The filter [`AVSession_PlaybackFilter`] of playback state determines
    /// which param are included in callback.
    ///
    /// * `callback` - The callback [`OH_AVCastControllerCallback_PlaybackStateChanged`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    /// 3. filter is invalid
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterPlaybackStateChangedCallback(
        avcastcontroller: *mut OH_AVCastController,
        filter: i32,
        callback: OH_AVCastControllerCallback_PlaybackStateChanged,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister playback state changed callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_PlaybackStateChanged`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterPlaybackStateChangedCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_PlaybackStateChanged,
    ) -> AVSession_ErrCode;
    /// Request to register current media changed callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_MediaItemChange`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterMediaItemChangedCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_MediaItemChange,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister current media item changed callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_MediaItemChange`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterMediaItemChangedCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_MediaItemChange,
    ) -> AVSession_ErrCode;
    /// Request to register playnext callback send by remote side or media center.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_PlayNext`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterPlayNextCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_PlayNext,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister playnext callback send by remote side or media center.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_PlayNext`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterPlayNextCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_PlayNext,
    ) -> AVSession_ErrCode;
    /// Request to register playprevious command callback send by remote side or media center.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_PlayPrevious`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterPlayPreviousCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_PlayPrevious,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister playprevious command callback send by remote side or media center.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_PlayPrevious`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterPlayPreviousCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_PlayPrevious,
    ) -> AVSession_ErrCode;
    /// Request to register seek done callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_SeekDone`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterSeekDoneCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_SeekDone,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister seek done callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_SeekDone`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterSeekDoneCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_SeekDone,
    ) -> AVSession_ErrCode;
    /// Request to register end of stream callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_EndOfStream`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterEndOfStreamCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_EndOfStream,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister end of stream callback.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_EndOfStream`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterEndOfStreamCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_EndOfStream,
    ) -> AVSession_ErrCode;
    /// Request to register listener for playback error events.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_Error`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_RegisterErrorCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_Error,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister listener for playback error events.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `callback` - the [`OH_AVCastControllerCallback_Error`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_UnregisterErrorCallback(
        avcastcontroller: *mut OH_AVCastController,
        callback: OH_AVCastControllerCallback_Error,
    ) -> AVSession_ErrCode;
    /// Request to send common command to Remote, only support to send play pause stop playnext playprevious command.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `avCastControlcommand` - control command [`AVSession_AVCastControlCommandType`].
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`] The param of avcastcontroller is nullptr.
    /// [`AV_SESSION_ERR_CODE_COMMAND_INVALID`] The param of avCastControlcommand is invalid.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_SendCommonCommand(
        avcastcontroller: *mut OH_AVCastController,
        avCastControlcommand: *mut AVSession_AVCastControlCommandType,
    ) -> AVSession_ErrCode;
    /// Request to send seek command to Remote.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `seekTimeMS` - seek time, the unit of time is milliseconds.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. seekTimeMS invalid.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_SendSeekCommand(
        avcastcontroller: *mut OH_AVCastController,
        seekTimeMS: i32,
    ) -> AVSession_ErrCode;
    /// Request to send forward command to Remote.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `forwardTimeS` - forward time, the unit of time is seconds.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. forwardTimeS invalid.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_SendFastForwardCommand(
        avcastcontroller: *mut OH_AVCastController,
        forwardTimeS: i32,
    ) -> AVSession_ErrCode;
    /// Request to send rewind command to Remote.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `rewindTimeS` - rewind time, the unit of time is seconds.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. rewindTimeS invalid.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_SendRewindCommand(
        avcastcontroller: *mut OH_AVCastController,
        rewindTimeS: i32,
    ) -> AVSession_ErrCode;
    /// Request to send set speed command to Remote.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `speed` - control command [`AVSession_PlaybackSpeed`].
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. speed invalid.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_SendSetSpeedCommand(
        avcastcontroller: *mut OH_AVCastController,
        speed: AVSession_PlaybackSpeed,
    ) -> AVSession_ErrCode;
    /// Request to send volume command to Remote.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `volume` - volume.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. volume invalid.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_SendVolumeCommand(
        avcastcontroller: *mut OH_AVCastController,
        volume: i32,
    ) -> AVSession_ErrCode;
    /// Request to prepare the current player item, this is needed for sink media information displaying.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `avqueueItem` - media item info [`OH_AVSession_AVQueueItem`].
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of avqueueItem is nullptr.
    /// [`AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST`] The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_Prepare(
        avcastcontroller: *mut OH_AVCastController,
        avqueueItem: *mut OH_AVSession_AVQueueItem,
    ) -> AVSession_ErrCode;
    /// Request to Play the current item, should contain media uri otherwise the playback will fail.
    ///
    /// # Arguments
    ///
    /// * `avcastcontroller` - The avcastcontroller instance pointer
    ///
    /// * `avqueueItem` - media item info [`OH_AVSession_AVQueueItem`].
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avcastcontroller is nullptr.
    /// 2. The param of avqueueItem is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVCastController_Start(
        avcastcontroller: *mut OH_AVCastController,
        avqueueItem: *mut OH_AVSession_AVQueueItem,
    ) -> AVSession_ErrCode;
}
