// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
impl GameController_ErrorCode {
    /// Success.
    pub const GAME_CONTROLLER_SUCCESS: GameController_ErrorCode = GameController_ErrorCode(0);
    /// Invalid parameter.
    pub const GAME_CONTROLLER_PARAM_ERROR: GameController_ErrorCode = GameController_ErrorCode(401);
    /// The multimodal input is abnormal.
    pub const GAME_CONTROLLER_MULTIMODAL_INPUT_ERROR: GameController_ErrorCode =
        GameController_ErrorCode(32200001);
    /// There is no sufficient memory.
    pub const GAME_CONTROLLER_NO_MEMORY: GameController_ErrorCode =
        GameController_ErrorCode(32200002);
}
#[repr(transparent)]
/// Defines an enum for the error codes of GameController.
///
/// Available since API-level: 21
#[cfg(feature = "api-21")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct GameController_ErrorCode(pub ::core::ffi::c_uint);
