// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

extern "C" {
    /// Checks whether this application is allowed to publish notifications.
    ///
    ///
    /// # Returns
    ///
    /// * true - This application is allowed to publish notifications.
    /// false - This application is not allowed to publish notifications.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_Notification_IsNotificationEnabled() -> bool;
}
