// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

impl DeviceManager_ErrorCode {
    pub const ERR_OK: DeviceManager_ErrorCode = DeviceManager_ErrorCode(0);
    pub const ERR_PERMISSION_ERROR: DeviceManager_ErrorCode = DeviceManager_ErrorCode(201);
    pub const ERR_INVALID_PARAMETER: DeviceManager_ErrorCode = DeviceManager_ErrorCode(401);
    pub const DM_ERR_FAILED: DeviceManager_ErrorCode = DeviceManager_ErrorCode(11600101);
    pub const DM_ERR_OBTAIN_SERVICE: DeviceManager_ErrorCode = DeviceManager_ErrorCode(11600102);
    pub const DM_ERR_OBTAIN_BUNDLE_NAME: DeviceManager_ErrorCode =
        DeviceManager_ErrorCode(11600109);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DeviceManager_ErrorCode(pub ::core::ffi::c_uint);
extern "C" {
    /// Obtains the display name of the local device.
    /// The device display name involves user privacy.
    /// You need to provide a privacy statement to declare the purpose of the device display name.
    ///
    /// ohos.permission.READ_LOCAL_DEVICE_NAME
    /// # Arguments
    ///
    /// * `localDeviceName` - Pointer to the display name of the local device.
    /// After using this API, you need to manually release resources to free up space.
    /// If the application has the ohos.permission.READ_LOCAL_DEVICE_NAME permission, the device display name is returned.
    /// Otherwise, the default device name is returned.
    ///
    /// * `len` - Length of the display name of the local device.
    ///
    /// # Returns
    ///
    /// * Error code. For details about the error code definitions, see [`DeviceManager_ErrorCode`].
    /// Returns [`ERR_OK`] is returned if the execution is successful.
    /// Returns [`DM_ERR_FAILED`] is returned if the function fails to be executed.
    /// Returns [`DM_ERR_OBTAIN_SERVICE`] is returned if the device management service fails to be obtained.
    /// Returns [`DM_ERR_OBTAIN_BUNDLE_NAME`] is returned if the bundle name fails to be obtained.
    /// Returns [`ERR_INVALID_PARAMETER`] is returned if the localDeviceName is nullptr or
    /// *localDeviceName is not nullptr.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_DeviceManager_GetLocalDeviceName(
        localDeviceName: *mut *mut ::core::ffi::c_char,
        len: *mut ::core::ffi::c_uint,
    ) -> i32;
}
