// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::type_def::*;

extern "C" {
    /// Initializes a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns <b>0</b> if the task attribute is initialized;
    /// returns <b>-1</b> otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_init(attr: *mut ffrt_task_attr_t) -> ::core::ffi::c_int;
    /// Sets the name of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// * `name` - Indicates a pointer to the task name.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_set_name(attr: *mut ffrt_task_attr_t, name: *const ::core::ffi::c_char);
    /// Gets the name of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns a non-null pointer to the task name if the name is obtained;
    /// returns a null pointer otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_get_name(attr: *const ffrt_task_attr_t) -> *const ::core::ffi::c_char;
    /// Destroys a task attribute, the user needs to invoke this interface.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_destroy(attr: *mut ffrt_task_attr_t);
    /// Sets the QoS of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// * `qos` - Indicates the QoS.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_set_qos(attr: *mut ffrt_task_attr_t, qos: ffrt_qos_t);
    /// Gets the QoS of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns the QoS, which is <b>ffrt_qos_default</b> by default.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_get_qos(attr: *const ffrt_task_attr_t) -> ffrt_qos_t;
    /// Sets the delay time of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// * `delay_us` - Indicates the delay time, in microseconds.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_set_delay(attr: *mut ffrt_task_attr_t, delay_us: u64);
    /// Gets the delay time of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns the delay time.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_attr_get_delay(attr: *const ffrt_task_attr_t) -> u64;
    /// Sets the priority of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// * `priority` - Indicates the execute priority of concurrent queue task.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_task_attr_set_queue_priority(
        attr: *mut ffrt_task_attr_t,
        priority: ffrt_queue_priority_t,
    );
    /// Gets the priority of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns the priority of concurrent queue task.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_task_attr_get_queue_priority(
        attr: *const ffrt_task_attr_t,
    ) -> ffrt_queue_priority_t;
    /// Sets the stack size of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// * `size` - Indicates the task stack size, unit is byte.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_task_attr_set_stack_size(attr: *mut ffrt_task_attr_t, size: u64);
    /// Gets the stack size of a task attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns the task stack size, unit is byte.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_task_attr_get_stack_size(attr: *const ffrt_task_attr_t) -> u64;
    /// Updates the QoS of this task.
    ///
    /// # Arguments
    ///
    /// * `qos` - Indicates the new QoS.
    ///
    /// # Returns
    ///
    /// * Returns <b>0</b> if the QoS is updated;
    /// returns <b>-1</b> otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_this_task_update_qos(qos: ffrt_qos_t) -> ::core::ffi::c_int;
    /// Gets the QoS of this task.
    ///
    ///
    /// # Returns
    ///
    /// * Returns the task qos.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_this_task_get_qos() -> ffrt_qos_t;
    /// Gets the ID of this task.
    ///
    ///
    /// # Returns
    ///
    /// * Returns the task ID.
    ///
    /// Available since API-level: 10
    pub fn ffrt_this_task_get_id() -> u64;
    /// Applies memory for the function execution structure.
    ///
    /// # Arguments
    ///
    /// * `kind` - Indicates the type of the function execution structure, which can be common or queue.
    ///
    /// # Returns
    ///
    /// * Returns a non-null pointer if the memory is allocated;
    /// returns a null pointer otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_alloc_auto_managed_function_storage_base(
        kind: ffrt_function_kind_t,
    ) -> *mut ::core::ffi::c_void;
    /// Submits a task.
    ///
    /// # Arguments
    ///
    /// * `f` - Indicates a pointer to the task executor.
    ///
    /// * `in_deps` - Indicates a pointer to the input dependencies.
    ///
    /// * `out_deps` - Indicates a pointer to the output dependencies.
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// Available since API-level: 10
    pub fn ffrt_submit_base(
        f: *mut ffrt_function_header_t,
        in_deps: *const ffrt_deps_t,
        out_deps: *const ffrt_deps_t,
        attr: *const ffrt_task_attr_t,
    );
    /// Submits a task, and obtains a task handle.
    ///
    /// # Arguments
    ///
    /// * `f` - Indicates a pointer to the task executor.
    ///
    /// * `in_deps` - Indicates a pointer to the input dependencies.
    ///
    /// * `out_deps` - Indicates a pointer to the output dependencies.
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns a non-null task handle if the task is submitted;
    /// returns a null pointer otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_submit_h_base(
        f: *mut ffrt_function_header_t,
        in_deps: *const ffrt_deps_t,
        out_deps: *const ffrt_deps_t,
        attr: *const ffrt_task_attr_t,
    ) -> ffrt_task_handle_t;
    /// Submits a task, simplified from the ffrt_submit_base interface.
    ///
    /// This interface wraps the provided task function and its argument into a task wrapper
    /// designated as a general task (ffrt_function_kind_general). During wrapper creation, the
    /// task destroy callback (after_func), which is intended to handle any post-execution cleanup,
    /// is simplified to NULL. The resulting task wrapper is then submitted using the underlying
    /// ffrt_submit_base interface.
    ///
    /// # Arguments
    ///
    /// * `func` - Indicates a task function to be executed.
    ///
    /// * `arg` - Indicates a pointer to the argument or closure data that will be passed to the task function.
    ///
    /// * `in_deps` - Indicates a pointer to the input dependencies.
    ///
    /// * `out_deps` - Indicates a pointer to the output dependencies.
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    /// [`ffrt_submit_base`]
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn ffrt_submit_f(
        func: ffrt_function_t,
        arg: *mut ::core::ffi::c_void,
        in_deps: *const ffrt_deps_t,
        out_deps: *const ffrt_deps_t,
        attr: *const ffrt_task_attr_t,
    );
    /// Submits a task, and obtains a task handle, simplified from the ffrt_submit_h_base interface.
    ///
    /// This interface wraps the provided task function and its argument into a task wrapper
    /// designated as a general task (ffrt_function_kind_general). During wrapper creation, the
    /// task destroy callback (after_func), which is intended to handle any post-execution cleanup,
    /// is simplified to NULL. The resulting task wrapper is then submitted using the underlying
    /// ffrt_submit_h_base interface.
    ///
    /// # Arguments
    ///
    /// * `func` - Indicates a task function to be executed.
    ///
    /// * `arg` - Indicates a pointer to the argument or closure data that will be passed to the task function.
    ///
    /// * `in_deps` - Indicates a pointer to the input dependencies.
    ///
    /// * `out_deps` - Indicates a pointer to the output dependencies.
    ///
    /// * `attr` - Indicates a pointer to the task attribute.
    ///
    /// # Returns
    ///
    /// * Returns a non-null task handle if the task is submitted;
    /// returns a null pointer otherwise.
    /// [`ffrt_submit_h_base`]
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn ffrt_submit_h_f(
        func: ffrt_function_t,
        arg: *mut ::core::ffi::c_void,
        in_deps: *const ffrt_deps_t,
        out_deps: *const ffrt_deps_t,
        attr: *const ffrt_task_attr_t,
    ) -> ffrt_task_handle_t;
    /// Increases reference count of a task.
    ///
    /// # Arguments
    ///
    /// * `handle` - Indicates a task handle.
    ///
    /// # Returns
    ///
    /// * Returns the task handle original reference count.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_task_handle_inc_ref(handle: ffrt_task_handle_t) -> u32;
    /// Decreases reference count of a task.
    ///
    /// # Arguments
    ///
    /// * `handle` - Indicates a task handle.
    ///
    /// # Returns
    ///
    /// * Returns the task handle original reference count.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_task_handle_dec_ref(handle: ffrt_task_handle_t) -> u32;
    /// Destroys a task handle, the user needs to invoke this interface.
    ///
    /// # Arguments
    ///
    /// * `handle` - Indicates a task handle.
    ///
    /// Available since API-level: 10
    pub fn ffrt_task_handle_destroy(handle: ffrt_task_handle_t);
    /// Waits until the dependent tasks are complete.
    ///
    /// # Arguments
    ///
    /// * `deps` - Indicates a pointer to the dependent tasks.
    ///
    /// Available since API-level: 10
    pub fn ffrt_wait_deps(deps: *const ffrt_deps_t);
    /// Waits until all submitted tasks are complete.
    ///
    ///
    /// Available since API-level: 10
    pub fn ffrt_wait();
}
