// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::deprecated_semver)]
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub use ohos_ddk_sys::DDK_Ashmem;

/// Setup data for control transfer. It corresponds to <b>Setup Data</b> in the USB protocol.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct UsbControlRequestSetup {
    /// Request type.
    pub bmRequestType: u8,
    /// Request command.
    pub bRequest: u8,
    /// Its meaning varies according to the request.
    pub wValue: u16,
    /// It is usually used to transfer the index or offset.
    ///
    /// Its meaning varies according to the request.
    pub wIndex: u16,
    /// Data length. If data is transferred,
    ///
    /// this field indicates the number of transferred bytes.
    pub wLength: u16,
}
/// Standard device descriptor, corresponding to <b>Standard Device Descriptor</b> in the USB protocol.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct UsbDeviceDescriptor {
    /// Size of the descriptor, in bytes.
    pub bLength: u8,
    /// Descriptor type.
    pub bDescriptorType: u8,
    /// USB protocol release number.
    pub bcdUSB: u16,
    /// Device class code allocated by the USB-IF.
    pub bDeviceClass: u8,
    /// Device subclass code allocated by USB-IF. The value is limited by that of bDeviceClass.
    pub bDeviceSubClass: u8,
    /// Protocol code allocated by USB-IF. The value is limited by that of bDeviceClass and bDeviceSubClass.
    pub bDeviceProtocol: u8,
    /// Maximum packet size of endpoint 0. Only values 8, 16, 32, and 64 are valid.
    pub bMaxPacketSize0: u8,
    /// Vendor ID allocated by USB-IF.
    pub idVendor: u16,
    /// Product ID allocated by the vendor.
    pub idProduct: u16,
    /// Device release number.
    pub bcdDevice: u16,
    /// Index of the string descriptor that describes the vendor.
    pub iManufacturer: u8,
    /// Index of the string descriptor that describes the product.
    pub iProduct: u8,
    /// Index of the string descriptor that describes the device SN.
    pub iSerialNumber: u8,
    /// Configuration quantity.
    pub bNumConfigurations: u8,
}
/// Standard configuration descriptor, corresponding to <b>Standard Configuration Descriptor</b>
///
/// in the USB protocol.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct UsbConfigDescriptor {
    /// Size of the descriptor, in bytes.
    pub bLength: u8,
    /// Descriptor type.
    pub bDescriptorType: u8,
    /// Total length of the configuration descriptor, including the configuration, interface, endpoint,
    ///
    /// and class- or vendor-specific descriptors.
    pub wTotalLength: u16,
    /// Number of interfaces supported by the configuration.
    pub bNumInterfaces: u8,
    /// Configuration index, which is used to select the configuration.
    pub bConfigurationValue: u8,
    /// Index of the string descriptor that describes the configuration.
    pub iConfiguration: u8,
    /// Configuration attributes, including the power mode and remote wakeup.
    pub bmAttributes: u8,
    /// Maximum power consumption of the bus-powered USB device, in 2 mA.
    pub bMaxPower: u8,
}
/// Standard interface descriptor, corresponding to <b>Standard Interface Descriptor</b>
/// in the USB protocol.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct UsbInterfaceDescriptor {
    /// Size of the descriptor, in bytes.
    pub bLength: u8,
    /// Descriptor type.
    pub bDescriptorType: u8,
    /// Interface number.
    pub bInterfaceNumber: u8,
    /// Value used to select the alternate setting of the interface.
    pub bAlternateSetting: u8,
    /// Number of endpoints (excluding endpoint 0) used by the interface.
    pub bNumEndpoints: u8,
    /// Interface class code allocated by the USB-IF.
    pub bInterfaceClass: u8,
    /// Interface subclass code allocated by USB-IF. The value is limited by that of bInterfaceClass.
    pub bInterfaceSubClass: u8,
    /// Protocol code allocated by USB-IF. The value is limited by that of bInterfaceClass and bInterfaceSubClass.
    pub bInterfaceProtocol: u8,
    /// Index of the string descriptor that describes the interface.
    pub iInterface: u8,
}
/// Standard endpoint descriptor, corresponding to <b>Standard Endpoint Descriptor</b> in the USB protocol.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct UsbEndpointDescriptor {
    /// Size of the descriptor, in bytes.
    pub bLength: u8,
    /// Descriptor type.
    pub bDescriptorType: u8,
    /// Endpoint address, including the endpoint number and endpoint direction.
    pub bEndpointAddress: u8,
    /// Endpoint attributes, including the transfer type, synchronization type, and usage type.
    pub bmAttributes: u8,
    /// Maximum packet size supported by an endpoint.
    pub wMaxPacketSize: u16,
    /// Interval for polling endpoints for data transfer.
    pub bInterval: u8,
    /// Refresh rate for audio devices.
    pub bRefresh: u8,
    /// Endpoint synchronization address for audio devices.
    pub bSynchAddress: u8,
}
/// Endpoint descriptor.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkEndpointDescriptor {
    /// Standard endpoint descriptor.
    pub endpointDescriptor: UsbEndpointDescriptor,
    /// Unresolved descriptor, including class- or vendor-specific descriptors.
    pub extra: *const u8,
    /// Length of the unresolved descriptor.
    pub extraLength: u32,
}
/// Interface descriptor.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkInterfaceDescriptor {
    /// Standard interface descriptor.
    pub interfaceDescriptor: UsbInterfaceDescriptor,
    /// Endpoint descriptor contained in the interface.
    pub endPoint: *mut UsbDdkEndpointDescriptor,
    /// Unresolved descriptor, including class- or vendor-specific descriptors.
    pub extra: *const u8,
    /// Length of the unresolved descriptor.
    pub extraLength: u32,
}
/// USB interface.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkInterface {
    /// Number of alternate settings of the interface.
    pub numAltsetting: u8,
    /// Alternate setting of the interface.
    pub altsetting: *mut UsbDdkInterfaceDescriptor,
}
/// Configuration descriptor.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkConfigDescriptor {
    /// Standard configuration descriptor.
    pub configDescriptor: UsbConfigDescriptor,
    /// Interfaces contained in the configuration.
    pub interface: *mut UsbDdkInterface,
    /// Unresolved descriptor, including class- or vendor-specific descriptors.
    pub extra: *const u8,
    /// Length of the unresolved descriptor.
    pub extraLength: u32,
}
/// Request pipe.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbRequestPipe {
    /// Interface operation handle.
    pub interfaceHandle: u64,
    /// Timeout duration, in milliseconds.
    pub timeout: u32,
    /// Endpoint address.
    pub endpoint: u8,
}
/// Device memory map created by calling <b>OH_Usb_CreateDeviceMemMap</b>.
///
/// A buffer using the device memory map can provide better performance.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[repr(C)]
pub struct UsbDeviceMemMap {
    /// Buffer address.
    pub address: *mut u8,
    /// Buffer size.
    pub size: usize,
    /// Offset of the used buffer. The default value is 0, indicating that there is no offset
    ///
    /// and the buffer starts from the specified address.
    pub offset: u32,
    /// Length of the used buffer. By default, the value is equal to the size, indicating that
    ///
    /// the entire buffer is used.
    pub bufferLength: u32,
    /// Length of the transferred data.
    pub transferedLength: u32,
}
impl UsbDdkErrCode {
    /// The operation is successful.
    pub const USB_DDK_SUCCESS: UsbDdkErrCode = UsbDdkErrCode(0);
    /// The operation failed.
    ///
    /// **Deprecated** since 16
    #[deprecated(since = "16")]
    pub const USB_DDK_FAILED: UsbDdkErrCode = UsbDdkErrCode(-1);
    /// Permission denied.
    ///
    /// Available since API-level: 14
    #[cfg(feature = "api-14")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
    pub const USB_DDK_NO_PERM: UsbDdkErrCode = UsbDdkErrCode(201);
    /// Invalid parameter.
    pub const USB_DDK_INVALID_PARAMETER: UsbDdkErrCode = UsbDdkErrCode(401);
    /// Memory-related error, for example, insufficient memory, memory data copy failure,
    ///
    /// or memory application failure.
    pub const USB_DDK_MEMORY_ERROR: UsbDdkErrCode = UsbDdkErrCode(27400001);
    /// Null pointer exception
    ///
    /// **Deprecated** since 16
    #[deprecated(since = "16")]
    pub const USB_DDK_NULL_PTR: UsbDdkErrCode = UsbDdkErrCode(-5);
    /// Device busy.
    ///
    /// **Deprecated** since 16
    #[deprecated(since = "16")]
    pub const USB_DDK_DEVICE_BUSY: UsbDdkErrCode = UsbDdkErrCode(-6);
    /// Invalid operation.
    pub const USB_DDK_INVALID_OPERATION: UsbDdkErrCode = UsbDdkErrCode(27400002);
    /// Device I/O operation failed.
    ///
    /// Available since API-level: 14
    #[cfg(feature = "api-14")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-14")))]
    pub const USB_DDK_IO_FAILED: UsbDdkErrCode = UsbDdkErrCode(27400003);
    /// Transmission timeout.
    pub const USB_DDK_TIMEOUT: UsbDdkErrCode = UsbDdkErrCode(27400004);
}
#[repr(transparent)]
/// Defines error codes for USB DDK.
///
///
/// Available since API-level: 10
///
/// Version: 1.0
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct UsbDdkErrCode(pub ::core::ffi::c_int);
/// all usb devices.
///
///
/// Available since API-level: 18
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Usb_DeviceArray {
    /// device id array
    pub deviceIds: *mut u64,
    /// Number of devices. If the value is 0, no device exists
    pub num: u32,
}
extern "C" {
    /// Initializes the DDK.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed or internal error.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_MEMORY_ERROR`] memory allocation failed.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_Init() -> i32;
    /// Releases the DDK.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_Release();
    /// Releases the DDK.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    ///
    /// Available since API-level: 18
    ///
    /// Version: 1.0
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_Usb_ReleaseResource() -> i32;
    /// Obtains the USB device descriptor.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `deviceId` - ID of the device whose descriptor is to be obtained.
    ///
    /// * `desc` - Standard device descriptor defined in the USB protocol.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] desc is null.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_GetDeviceDescriptor(deviceId: u64, desc: *mut UsbDeviceDescriptor) -> i32;
    /// Obtains the configuration descriptor. To avoid memory leakage, use <b>OH_Usb_FreeConfigDescriptor</b>
    ///
    /// to release a descriptor after use.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `deviceId` - ID of the device whose configuration descriptor is to be obtained.
    ///
    /// * `configIndex` - Configuration index, which corresponds to <b>bConfigurationValue</b> in the USB protocol.
    ///
    /// * `config` - Configuration descriptor, which includes the standard configuration descriptor defined in the
    ///
    /// USB protocol and the associated interface descriptor and endpoint descriptor.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] config is null.
    /// [`USB_DDK_IO_FAILED`] data IO exception.
    /// [`USB_DDK_MEMORY_ERROR`] memory allocation failed.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_GetConfigDescriptor(
        deviceId: u64,
        configIndex: u8,
        config: *mut *mut UsbDdkConfigDescriptor,
    ) -> i32;
    /// Releases the configuration descriptor. To avoid memory leakage, use <b>OH_Usb_FreeConfigDescriptor</b>
    ///
    /// to release a descriptor after use.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `config` - Configuration descriptor obtained by calling <b>OH_Usb_GetConfigDescriptor</b>.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_FreeConfigDescriptor(config: *mut UsbDdkConfigDescriptor);
    /// Claims a USB interface.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `deviceId` - ID of the device to be operated.
    ///
    /// * `interfaceIndex` - Interface index, which corresponds to <b>bInterfaceNumber</b> in the USB protocol.
    ///
    /// * `interfaceHandle` - Interface operation handle. After the interface is claimed successfully, a value will be
    ///
    /// assigned to this parameter.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] interfaceHandle is null.
    /// [`USB_DDK_MEMORY_ERROR`] memory exceeds limit.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_ClaimInterface(
        deviceId: u64,
        interfaceIndex: u8,
        interfaceHandle: *mut u64,
    ) -> i32;
    /// Releases a USB interface.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `interfaceHandle` - Interface operation handle.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] parameter error.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_ReleaseInterface(interfaceHandle: u64) -> i32;
    /// Activates the alternate setting of the USB interface.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `interfaceHandle` - Interface operation handle.
    ///
    /// * `settingIndex` - Index of the alternate setting, which corresponds to <b>bAlternateSetting</b>
    ///
    /// in the USB protocol.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] parameter error.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_SelectInterfaceSetting(interfaceHandle: u64, settingIndex: u8) -> i32;
    /// Obtains the activated alternate setting of the USB interface.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `interfaceHandle` - Interface operation handle.
    ///
    /// * `settingIndex` - Index of the alternate setting, which corresponds to <b>bAlternateSetting</b>
    ///
    /// in the USB protocol.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] settingIndex is null.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_GetCurrentInterfaceSetting(interfaceHandle: u64, settingIndex: *mut u8) -> i32;
    /// Sends a control read transfer request. This API works in a synchronous manner.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `interfaceHandle` - Interface operation handle.
    ///
    /// * `setup` - Request data, which corresponds to <b>Setup Data</b> in the USB protocol.
    ///
    /// * `timeout` - Timeout duration, in milliseconds.
    ///
    /// * `data` - Data to be transferred.
    ///
    /// * `dataLen` - Data length. The return value indicates the length of the actually read data.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] setup is null or data is null or dataLen is null or dataLen is less than
    ///
    /// size of the read data.
    /// [`USB_DDK_MEMORY_ERROR`] the memory of read data copies failed.
    /// [`USB_DDK_IO_FAILED`] data IO exception.
    /// [`USB_DDK_TIMEOUT`] interface timeout.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_SendControlReadRequest(
        interfaceHandle: u64,
        setup: *const UsbControlRequestSetup,
        timeout: u32,
        data: *mut u8,
        dataLen: *mut u32,
    ) -> i32;
    /// Sends a control write transfer request. This API works in a synchronous manner.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `interfaceHandle` - Interface operation handle.
    ///
    /// * `setup` - Request data, which corresponds to <b>Setup Data</b> in the USB protocol.
    ///
    /// * `timeout` - Timeout duration, in milliseconds.
    ///
    /// * `data` - Data to be transferred.
    ///
    /// * `dataLen` - Data length.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] setup is null or data is null.
    /// [`USB_DDK_MEMORY_ERROR`] the memory of read data copies failed.
    /// [`USB_DDK_IO_FAILED`] data IO exception.
    /// [`USB_DDK_TIMEOUT`] interface timeout.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_SendControlWriteRequest(
        interfaceHandle: u64,
        setup: *const UsbControlRequestSetup,
        timeout: u32,
        data: *const u8,
        dataLen: u32,
    ) -> i32;
    /// Sends a pipe request. This API works in a synchronous manner. This API applies to interrupt transfer
    ///
    /// and bulk transfer.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `pipe` - Pipe used to transfer data.
    ///
    /// * `devMmap` - Device memory map, which can be obtained by calling <b>OH_Usb_CreateDeviceMemMap</b>.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] pipe is null or devMmap is null or address of devMmap is null.
    /// [`USB_DDK_MEMORY_ERROR`] the memory of read data copies failed.
    /// [`USB_DDK_IO_FAILED`] data IO exception.
    /// [`USB_DDK_TIMEOUT`] interface timeout.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_SendPipeRequest(
        pipe: *const UsbRequestPipe,
        devMmap: *mut UsbDeviceMemMap,
    ) -> i32;
    /// Sends a pipe request. This API works in a synchronous manner. This API applies to interrupt transfer
    ///
    /// and bulk transfer.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `pipe` - Pipe used to transfer data.
    ///
    /// * `ashmem` - Shared memory, which can be obtained by calling <b>OH_DDK_CreateAshmem</b>.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] pipe is null or ashmem is null or address of ashmem is null.
    /// [`USB_DDK_MEMORY_ERROR`] the memory of read data copies failed.
    /// [`USB_DDK_IO_FAILED`] data IO exception.
    /// [`USB_DDK_TIMEOUT`] interface timeout.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_Usb_SendPipeRequestWithAshmem(
        pipe: *const UsbRequestPipe,
        ashmem: *mut DDK_Ashmem,
    ) -> i32;
    /// Creates a buffer. To avoid resource leakage, destroy a buffer by calling
    ///
    /// <b>OH_Usb_DestroyDeviceMemMap</b> after use.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `deviceId` - ID of the device for which the buffer is to be created.
    ///
    /// * `size` - Buffer size.
    ///
    /// * `devMmap` - Data memory map, through which the created buffer is returned to the caller.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_PARAMETER`] devMmap is null.
    /// [`USB_DDK_MEMORY_ERROR`] mmap failed or alloc memory of devMmap failed.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_CreateDeviceMemMap(
        deviceId: u64,
        size: usize,
        devMmap: *mut *mut UsbDeviceMemMap,
    ) -> i32;
    /// Destroys a buffer. To avoid resource leakage, destroy a buffer in time after use.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `devMmap` - Device memory map created by calling <b>OH_Usb_CreateDeviceMemMap</b>.
    ///
    /// Available since API-level: 10
    ///
    /// Version: 1.0
    pub fn OH_Usb_DestroyDeviceMemMap(devMmap: *mut UsbDeviceMemMap);
    /// Obtain USB devices.
    ///
    /// ohos.permission.ACCESS_DDK_USB
    /// # Arguments
    ///
    /// * `devices` - USB device array.
    ///
    /// # Returns
    ///
    /// * [`USB_DDK_SUCCESS`] the operation is successful.
    /// [`USB_DDK_NO_PERM`] permission check failed.
    /// [`USB_DDK_INVALID_OPERATION`] connect usb ddk service failed.
    /// [`USB_DDK_INVALID_PARAMETER`] devices is null.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_Usb_GetDevices(devices: *mut Usb_DeviceArray) -> i32;
}
