// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#[allow(unused_imports)]
use crate::camera::Camera_Device;
use crate::camera::*;

/// Camera input object.
///
/// A pointer can be created using [`OH_CameraManager_CreateCameraInput`] method.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
pub struct Camera_Input {
    _unused: [u8; 0],
}
/// Camera input error callback to be called in [`CameraInput_Callbacks`].
///
/// # Arguments
///
/// * `cameraInput` - the [`Camera_Input`] which deliver the callback.
///
/// * `errorCode` - the [`Camera_ErrorCode`] of the camera input.
///
/// [`CAMERA_CONFLICT_CAMERA`] [`CAMERA_DEVICE_DISABLED`] [`CAMERA_DEVICE_PREEMPTED`] [`CAMERA_SERVICE_FATAL_ERROR`]
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_CameraInput_OnError = ::core::option::Option<
    unsafe extern "C" fn(cameraInput: *const Camera_Input, errorCode: Camera_ErrorCode),
>;
/// A listener for camera input error events.
///
/// [`OH_CameraInput_RegisterCallback`]
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CameraInput_Callbacks {
    /// Camera input error event.
    pub onError: OH_CameraInput_OnError,
}
/// Camera input occlusion detection result callback.
///
/// # Arguments
///
/// * `cameraInput` - the [`Camera_Input`] which deliver the callback.
///
/// * `occlusionDetectionResult` - the [`Camera_OcclusionDetectionResult`] of the camera.
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_CameraInput_OnOcclusionDetectionCallback = ::core::option::Option<
    unsafe extern "C" fn(
        cameraInput: *const Camera_Input,
        occlusionDetectionResult: Camera_OcclusionDetectionResult,
    ),
>;
extern "C" {
    /// Register camera input change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance.
    ///
    /// * `callback` - the [`CameraInput_Callbacks`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraInput_RegisterCallback(
        cameraInput: *mut Camera_Input,
        callback: *mut CameraInput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Unregister camera input change event callback.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance.
    ///
    /// * `callback` - the [`CameraInput_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraInput_UnregisterCallback(
        cameraInput: *mut Camera_Input,
        callback: *mut CameraInput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Open camera.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance to be opened.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_CONFLICT_CAMERA`] if can not use camera cause of conflict.
    /// [`#CAMERA_DEVICE_DISABLED`] if camera disabled cause of security reason.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraInput_Open(cameraInput: *mut Camera_Input) -> Camera_ErrorCode;
    /// Open camera.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance to be opened.
    ///
    /// * `secureSeqId` - which indicates SequenceId that secure camera is on.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_CONFLICT_CAMERA`] if can not use camera cause of conflict.
    /// [`#CAMERA_DEVICE_DISABLED`] if camera disabled cause of security reason.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CameraInput_OpenSecureCamera(
        cameraInput: *mut Camera_Input,
        secureSeqId: *mut u64,
    ) -> Camera_ErrorCode;
    /// Open camera with specified concurrent type.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance to be opened.
    ///
    /// * `type` - the [`Camera_ConcurrentType`] instance.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_CONFLICT_CAMERA`] if can not use camera cause of conflict.
    /// [`#CAMERA_DEVICE_DISABLED`] if camera disabled cause of security reason.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_CameraInput_OpenConcurrentCameras(
        cameraInput: *mut Camera_Input,
        type_: Camera_ConcurrentType,
    ) -> Camera_ErrorCode;
    /// Close camera.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance to be closed.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraInput_Close(cameraInput: *mut Camera_Input) -> Camera_ErrorCode;
    /// Release camera input instance.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance to be released.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_CameraInput_Release(cameraInput: *mut Camera_Input) -> Camera_ErrorCode;
    /// Query whether physical camera orientation is variable under different fold status.
    ///
    /// # Arguments
    ///
    /// {CameraInput} cameraInput the [`Camera_Input`] instance.
    ///
    /// {bool} isVariable the result of whether physical camera orientation is variable.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 22
    #[cfg(feature = "api-22")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-22")))]
    pub fn OH_CameraInput_IsPhysicalCameraOrientationVariable(
        cameraInput: *mut Camera_Input,
        isVariable: *mut bool,
    ) -> Camera_ErrorCode;
    /// Get physical camera orientation under current fold status.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance.
    ///
    /// * `orientation` - the physical camera orientation of current fold status.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 22
    #[cfg(feature = "api-22")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-22")))]
    pub fn OH_CameraInput_GetPhysicalCameraOrientation(
        cameraInput: *mut Camera_Input,
        orientation: *mut u32,
    ) -> Camera_ErrorCode;
    /// Choose whether to use the physical camera orientation.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance.
    ///
    /// * `isUsed` - the flag of whether to use physical camera orientation.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_OPERATION_NOT_ALLOWED`] if operation not allowed.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 22
    #[cfg(feature = "api-22")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-22")))]
    pub fn OH_CameraInput_UsePhysicalCameraOrientation(
        cameraInput: *mut Camera_Input,
        isUsed: bool,
    ) -> Camera_ErrorCode;
    /// Subscribes to occlusion detection callback.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance.
    ///
    /// * `occlusionDetectionCallback` - callback used for subscription.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_CameraInput_RegisterOcclusionDetectionCallback(
        cameraInput: *mut Camera_Input,
        occlusionDetectionCallback: OH_CameraInput_OnOcclusionDetectionCallback,
    ) -> Camera_ErrorCode;
    /// Unsubscribes from occlusion detection callback.
    ///
    /// # Arguments
    ///
    /// * `cameraInput` - the [`Camera_Input`] instance.
    ///
    /// * `occlusionDetectionCallback` - callback used for unsubscription.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_CameraInput_UnregisterOcclusionDetectionCallback(
        cameraInput: *mut Camera_Input,
        occlusionDetectionCallback: OH_CameraInput_OnOcclusionDetectionCallback,
    ) -> Camera_ErrorCode;
}
