// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#[allow(unused_imports)]
use crate::avsession_base::{AVSession_PlaybackSpeed, AVSession_PlaybackState};
use crate::avsession_errors::AVSession_ErrCode;

/// AVSession playbackstate object.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVSession_AVPlaybackState {
    _unused: [u8; 0],
}
/// Defines the playback position.
///
///
/// Available since API-level: 13
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AVSession_PlaybackPosition {
    /// Elapsed time(position) of this media set by the app.
    pub elapsedTime: i64,
    /// Record the system time when elapsedTime is set.
    pub updateTime: i64,
}
extern "C" {
    /// Get State of PlayBackState.
    ///
    /// # Arguments
    ///
    /// * `playbackState` - reference returned by [`OH_AVSession_AVPlaybackState`]
    ///
    /// * `state` - the pointer [`AVSession_PlaybackState`] variable that will be set play state value.
    ///
    /// # Returns
    ///
    /// * [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// or [`AV_SESSION_ERR_INVALID_PARAMETER`] if parameter valiation fails
    /// 1.The param of playbackState is nullptr;
    /// 2.The param of state is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_GetPlaybackState(
        playbackState: *mut OH_AVSession_AVPlaybackState,
        state: *mut AVSession_PlaybackState,
    ) -> AVSession_ErrCode;
    /// Get position of PlayBackState.
    ///
    /// # Arguments
    ///
    /// * `playbackState` - reference returned by [`OH_AVSession_AVPlaybackState`]
    ///
    /// * `position` - the pointer [`AVSession_PlaybackPosition`] variable that will be set playback position value.
    ///
    /// # Returns
    ///
    /// * [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// or [`AV_SESSION_ERR_INVALID_PARAMETER`] if parameter valiation fails
    /// 1.The param of playbackState is nullptr;
    /// 2.The param of position is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_GetPlaybackPosition(
        playbackState: *mut OH_AVSession_AVPlaybackState,
        position: *mut AVSession_PlaybackPosition,
    ) -> AVSession_ErrCode;
    /// Get speed of PlayBackState.
    ///
    /// # Arguments
    ///
    /// * `playbackState` - reference returned by [`OH_AVSession_AVPlaybackState`]
    ///
    /// * `speed` - the pointer variable that will be set the speed.
    ///
    /// # Returns
    ///
    /// * [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// or [`AV_SESSION_ERR_INVALID_PARAMETER`] if parameter valiation fails
    /// 1.The param of playbackState is nullptr;
    /// 2.The param of speed is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_GetPlaybackSpeed(
        playbackState: *mut OH_AVSession_AVPlaybackState,
        speed: *mut i32,
    ) -> AVSession_ErrCode;
    /// Get volume of PlayBackState.
    ///
    /// # Arguments
    ///
    /// * `playbackState` - reference returned by [`OH_AVSession_AVPlaybackState`]
    ///
    /// * `volume` - the pointer variable that will be set the volume.
    ///
    /// # Returns
    ///
    /// * [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// or [`AV_SESSION_ERR_INVALID_PARAMETER`] if parameter valiation fails
    /// 1.The param of playbackState is nullptr;
    /// 2.The param of volume is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_GetPlaybackVolume(
        playbackState: *mut OH_AVSession_AVPlaybackState,
        volume: *mut i32,
    ) -> AVSession_ErrCode;
}
