// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::asset_base::*;

extern "C" {
    /// Create a [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// # Arguments
    ///
    /// * `mediaAsset` - the [`OH_MediaAsset`] instance.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_MediaAssetChangeRequest_Create(
        mediaAsset: *mut OH_MediaAsset,
    ) -> *mut OH_MediaAssetChangeRequest;
    /// Add resource of the asset using file uri.
    ///
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// * `resourceType` - the [`MediaLibrary_ResourceType`] of the resource to add.
    ///
    /// * `fileUri` - the file uri.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_NO_SUCH_FILE`] if file does not exist.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    /// [`#MEDIA_LIBRARY_OPERATION_NOT_SUPPORTED`] if operation is not supported.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_MediaAssetChangeRequest_AddResourceWithUri(
        changeRequest: *mut OH_MediaAssetChangeRequest,
        resourceType: MediaLibrary_ResourceType,
        fileUri: *mut ::core::ffi::c_char,
    ) -> MediaLibrary_ErrorCode;
    /// Add resource of the asset using ArrayBuffer.
    ///
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// * `resourceType` - the [`MediaLibrary_ResourceType`] of the resource to add.
    ///
    /// * `buffer` - the data buffer to add.
    ///
    /// * `length` - the length of the data buffer.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    /// [`#MEDIA_LIBRARY_OPERATION_NOT_SUPPORTED`] if operation is not supported.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_MediaAssetChangeRequest_AddResourceWithBuffer(
        changeRequest: *mut OH_MediaAssetChangeRequest,
        resourceType: MediaLibrary_ResourceType,
        buffer: *mut u8,
        length: u32,
    ) -> MediaLibrary_ErrorCode;
    /// Get write cache handler.
    ///
    /// ohos.permission.WRITE_IMAGEVIDEO
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// * `fd` - the write cache handler.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    /// [`#MEDIA_LIBRARY_PERMISSION_DENIED`] if permission is denied.
    /// [`#MEDIA_LIBRARY_OPERATION_NOT_SUPPORTED`] if operation is not supported.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_MediaAssetChangeRequest_GetWriteCacheHandler(
        changeRequest: *mut OH_MediaAssetChangeRequest,
        fd: *mut i32,
    ) -> MediaLibrary_ErrorCode;
    /// Save the photo asset captured by camera.
    ///
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// * `imageFileType` - The [`MediaLibrary_ImageFileType`] of photo to be saved.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    /// [`#MEDIA_LIBRARY_OPERATION_NOT_SUPPORTED`] if operation is not supported.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_MediaAssetChangeRequest_SaveCameraPhoto(
        changeRequest: *mut OH_MediaAssetChangeRequest,
        imageFileType: MediaLibrary_ImageFileType,
    ) -> MediaLibrary_ErrorCode;
    /// Discard the photo asset captured by camera.
    ///
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    /// [`#MEDIA_LIBRARY_OPERATION_NOT_SUPPORTED`] if operation is not supported.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_MediaAssetChangeRequest_DiscardCameraPhoto(
        changeRequest: *mut OH_MediaAssetChangeRequest,
    ) -> MediaLibrary_ErrorCode;
    /// Release the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_MediaAssetChangeRequest_Release(
        changeRequest: *mut OH_MediaAssetChangeRequest,
    ) -> MediaLibrary_ErrorCode;
}
