// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::asset_base::*;

extern "C" {
    /// Apply the change request of asset or album.
    ///
    /// ohos.permission.WRITE_IMAGEVIDEO
    /// # Arguments
    ///
    /// * `changeRequest` - the [`OH_MediaAssetChangeRequest`] instance to be applied.
    ///
    /// # Returns
    ///
    /// * [`#MEDIA_LIBRARY_OK`] if the method call succeeds.
    /// [`#MEDIA_LIBRARY_PARAMETER_ERROR`] Parameter error. Possible causes:
    /// 1. Mandatory parameters are left unspecified.
    /// 2. Incorrect parameter types.
    /// 3. Parameter verification failed.
    /// [`#MEDIA_LIBRARY_PERMISSION_DENIED`] Permission is denied.
    /// [`#MEDIA_LIBRARY_INTERNAL_SYSTEM_ERROR`] if internal system error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_MediaAccessHelper_ApplyChanges(
        changeRequest: *mut OH_MediaAssetChangeRequest,
    ) -> MediaLibrary_ErrorCode;
}
