// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::type_def::*;

extern "C" {
    /// Initializes a mutex attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the mutex attribute.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex attribute is initialized;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_mutexattr_init(attr: *mut ffrt_mutexattr_t) -> ::core::ffi::c_int;
    /// Sets the type of a mutex attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the mutex attribute.
    ///
    /// * `type` - Indicates a int to the mutex type.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex attribute type is set successfully;
    /// returns <b>ffrt_error_inval</b> if <b>attr</b> is a null pointer or
    /// the mutex attribute type is not <b>ffrt_mutex_normal</b> or <b>ffrt_mutex_recursive</b>.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_mutexattr_settype(
        attr: *mut ffrt_mutexattr_t,
        type_: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
    /// Gets the type of a mutex attribute.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the mutex attribute.
    ///
    /// * `type` - Indicates a pointer to the mutex type.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex attribute type is get successfully;
    /// returns <b>ffrt_error_inval</b> if <b>attr</b> or <b>type</b> is a null pointer.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_mutexattr_gettype(
        attr: *mut ffrt_mutexattr_t,
        type_: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
    /// Destroys a mutex attribute, the user needs to invoke this interface.
    ///
    /// # Arguments
    ///
    /// * `attr` - Indicates a pointer to the mutex attribute.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex attribute is destroyed;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn ffrt_mutexattr_destroy(attr: *mut ffrt_mutexattr_t) -> ::core::ffi::c_int;
    /// Initializes a mutex.
    ///
    /// # Arguments
    ///
    /// * `mutex` - Indicates a pointer to the mutex.
    ///
    /// * `attr` - Indicates a pointer to the mutex attribute.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex is initialized;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_mutex_init(
        mutex: *mut ffrt_mutex_t,
        attr: *const ffrt_mutexattr_t,
    ) -> ::core::ffi::c_int;
    /// Locks a mutex.
    ///
    /// # Arguments
    ///
    /// * `mutex` - Indicates a pointer to the mutex.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex is locked;
    /// returns <b>ffrt_error_inval</b> or blocks the calling thread otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_mutex_lock(mutex: *mut ffrt_mutex_t) -> ::core::ffi::c_int;
    /// Unlocks a mutex.
    ///
    /// # Arguments
    ///
    /// * `mutex` - Indicates a pointer to the mutex.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex is unlocked;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_mutex_unlock(mutex: *mut ffrt_mutex_t) -> ::core::ffi::c_int;
    /// Attempts to lock a mutex.
    ///
    /// # Arguments
    ///
    /// * `mutex` - Indicates a pointer to the mutex.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex is locked;
    /// returns <b>ffrt_error_inval</b> or <b>ffrt_error_busy</b> otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_mutex_trylock(mutex: *mut ffrt_mutex_t) -> ::core::ffi::c_int;
    /// Destroys a mutex, the user needs to invoke this interface.
    ///
    /// # Arguments
    ///
    /// * `mutex` - Indicates a pointer to the mutex.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the mutex is destroyed;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 10
    pub fn ffrt_mutex_destroy(mutex: *mut ffrt_mutex_t) -> ::core::ffi::c_int;
}
