// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#[allow(unused_imports)]
use crate::avsession_base::{AVMetadata_DisplayTag, AVMetadata_SkipIntervals};
use crate::avsession_errors::AVMetadata_Result;

#[repr(C)]
pub struct OH_AVMetadataBuilderStruct {
    _unused: [u8; 0],
}
/// Declaring the avmetadata builder.
/// The instance of builder is used for creating avmetadata.
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVMetadataBuilder = OH_AVMetadataBuilderStruct;
#[repr(C)]
pub struct OH_AVMetadataStruct {
    _unused: [u8; 0],
}
/// Declaring the avmetadata.
/// The instance of avmetadata set by application for current resource.
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVMetadata = OH_AVMetadataStruct;
extern "C" {
    /// Creates an AVMetadataBuilder instance.
    ///
    /// # Arguments
    ///
    /// * `builder` - The builder reference to the created result.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`] The param of builder is nullptr.
    /// [`AVMETADATA_ERROR_NO_MEMORY`] No memory to allocate a new instance.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_Create(
        builder: *mut *mut OH_AVMetadataBuilder,
    ) -> AVMetadata_Result;
    /// Destroy a bulder.
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`] The param of builder is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_Destroy(builder: *mut OH_AVMetadataBuilder) -> AVMetadata_Result;
    /// Set current asset id of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `assetId` - The current assetId of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of assetId is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetAssetId(
        builder: *mut OH_AVMetadataBuilder,
        assetId: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the title of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `title` - The title of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of title is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetTitle(
        builder: *mut OH_AVMetadataBuilder,
        title: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the artist of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `artist` - The artist of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of artist is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetArtist(
        builder: *mut OH_AVMetadataBuilder,
        artist: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the author of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `author` - The author of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of author is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetAuthor(
        builder: *mut OH_AVMetadataBuilder,
        author: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the album information
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `album` - The album name
    ///
    /// # Returns
    ///
    /// * Return code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of album is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetAlbum(
        builder: *mut OH_AVMetadataBuilder,
        album: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the writer of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `writer` - The writer of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of writer is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetWriter(
        builder: *mut OH_AVMetadataBuilder,
        writer: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the composer of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `composer` - The composer of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1. The param of builder is nullptr.
    /// 2. The param of composer is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetComposer(
        builder: *mut OH_AVMetadataBuilder,
        composer: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the duration of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `duration` - The duration of resource, in miliseconds
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`] The param of builder is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetDuration(
        builder: *mut OH_AVMetadataBuilder,
        duration: i64,
    ) -> AVMetadata_Result;
    /// Set the media image uri of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `mediaImageUri` - The mediaImageUri of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of mediaImageUri nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetMediaImageUri(
        builder: *mut OH_AVMetadataBuilder,
        mediaImageUri: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the subtitle of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `subtitle` - The subtitle of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of subtitle nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetSubtitle(
        builder: *mut OH_AVMetadataBuilder,
        subtitle: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the media description of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `description` - The description of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of description nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetDescription(
        builder: *mut OH_AVMetadataBuilder,
        description: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the media lyric content of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `lyric` - The lyric of resource.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of lyric nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetLyric(
        builder: *mut OH_AVMetadataBuilder,
        lyric: *const ::core::ffi::c_char,
    ) -> AVMetadata_Result;
    /// Set the skip intervals of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `intervals` - The intervals of resource, only can be set : 10, 15, 30
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of intervals is invalid.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetSkipIntervals(
        builder: *mut OH_AVMetadataBuilder,
        intervals: AVMetadata_SkipIntervals,
    ) -> AVMetadata_Result;
    /// Set the display tags of the resource
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `tags` - The display tags of resource which are supported by this app to be displayed on the media center
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`] The param of builder is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_SetDisplayTags(
        builder: *mut OH_AVMetadataBuilder,
        tags: i32,
    ) -> AVMetadata_Result;
    /// Set the protocols supported
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `filter` - The protocols supported by this session,if not set, the default is [`TYPE_CAST_PLUS_STREAM`]
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of filter is invalid.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMetadataBuilder_SetFilter(
        builder: *mut OH_AVMetadataBuilder,
        filter: u32,
    ) -> AVMetadata_Result;
    /// Create the avmetadta.
    ///
    /// # Arguments
    ///
    /// * `builder` - The metadata builder instance pointer
    ///
    /// * `avMetadata` - Pointer to a viriable to receive the avMetadata object.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_NO_MEMORY`] No memory to allocate a new instance.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`]:
    /// 1.The param of builder is nullptr;
    /// 2.The param of avMetadata is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadataBuilder_GenerateAVMetadata(
        builder: *mut OH_AVMetadataBuilder,
        avMetadata: *mut *mut OH_AVMetadata,
    ) -> AVMetadata_Result;
    /// Request to release the avmetadta.
    ///
    /// # Arguments
    ///
    /// * `avMetadata` - Pointer to a viriable to receive the avMetadata object.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AVMETADATA_SUCCESS`] If the execution is successful.
    /// [`AVMETADATA_ERROR_INVALID_PARAM`] The param of avMetadata is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVMetadata_Destroy(avMetadata: *mut OH_AVMetadata) -> AVMetadata_Result;
}
