// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::camera::*;
#[allow(unused_imports)]
use ohos_sys_opaque_types::OHNativeWindow;

/// Video output object
///
/// A pointer can be created using [`Camera_VideoOutput`] method.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
pub struct Camera_VideoOutput {
    _unused: [u8; 0],
}
/// Video output frame start callback to be called in [`VideoOutput_Callbacks`].
///
/// # Arguments
///
/// * `videoOutput` - the [`Camera_VideoOutput`] which deliver the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_VideoOutput_OnFrameStart =
    ::core::option::Option<unsafe extern "C" fn(videoOutput: *mut Camera_VideoOutput)>;
/// Video output frame end callback to be called in [`VideoOutput_Callbacks`].
///
/// # Arguments
///
/// * `videoOutput` - the [`Camera_VideoOutput`] which deliver the callback.
///
/// * `frameCount` - the frame count which delivered by the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_VideoOutput_OnFrameEnd = ::core::option::Option<
    unsafe extern "C" fn(videoOutput: *mut Camera_VideoOutput, frameCount: i32),
>;
/// Video output error callback to be called in [`VideoOutput_Callbacks`].
///
/// # Arguments
///
/// * `videoOutput` - the [`Camera_VideoOutput`] which deliver the callback.
///
/// * `errorCode` - the [`Camera_ErrorCode`] of the video output.
///
/// [`CAMERA_SERVICE_FATAL_ERROR`]
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_VideoOutput_OnError = ::core::option::Option<
    unsafe extern "C" fn(videoOutput: *mut Camera_VideoOutput, errorCode: Camera_ErrorCode),
>;
/// A listener for video output.
///
/// [`OH_VideoOutput_RegisterCallback`]
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VideoOutput_Callbacks {
    /// Video output frame start event.
    pub onFrameStart: OH_VideoOutput_OnFrameStart,
    /// Video output frame end event.
    pub onFrameEnd: OH_VideoOutput_OnFrameEnd,
    /// Video output error event.
    pub onError: OH_VideoOutput_OnError,
}
extern "C" {
    /// Register video output change event callback.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance.
    ///
    /// * `callback` - the [`VideoOutput_Callbacks`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_VideoOutput_RegisterCallback(
        videoOutput: *mut Camera_VideoOutput,
        callback: *mut VideoOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Unregister video output change event callback.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance.
    ///
    /// * `callback` - the [`VideoOutput_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_VideoOutput_UnregisterCallback(
        videoOutput: *mut Camera_VideoOutput,
        callback: *mut VideoOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Start video output.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to be started.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SESSION_NOT_CONFIG`] if the capture session not config.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_VideoOutput_Start(videoOutput: *mut Camera_VideoOutput) -> Camera_ErrorCode;
    /// Stop video output.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to be stoped.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_VideoOutput_Stop(videoOutput: *mut Camera_VideoOutput) -> Camera_ErrorCode;
    /// Release video output.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to be released.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_VideoOutput_Release(videoOutput: *mut Camera_VideoOutput) -> Camera_ErrorCode;
    /// Get active video output profile.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to deliver active video profile.
    ///
    /// * `profile` - the active [`Camera_VideoProfile`] to be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_GetActiveProfile(
        videoOutput: *mut Camera_VideoOutput,
        profile: *mut *mut Camera_VideoProfile,
    ) -> Camera_ErrorCode;
    /// Delete video profile instance.
    ///
    /// # Arguments
    ///
    /// * `profile` - the [`Camera_VideoProfile`] instance to deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_DeleteProfile(profile: *mut Camera_VideoProfile) -> Camera_ErrorCode;
    /// Check whether mirror mode is supported for videoOutput
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance
    ///
    /// * `isSupported` - the result of whether mirror mode supported.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 15
    #[cfg(feature = "api-15")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-15")))]
    pub fn OH_VideoOutput_IsMirrorSupported(
        videoOutput: *mut Camera_VideoOutput,
        isSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Enable or disable mirror mode for videoOutput
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance
    ///
    /// * `mirrorMode` - enable mirror mode if mirrorMode is TRUE, otherwise disable
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 15
    #[cfg(feature = "api-15")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-15")))]
    pub fn OH_VideoOutput_EnableMirror(
        videoOutput: *mut Camera_VideoOutput,
        mirrorMode: bool,
    ) -> Camera_ErrorCode;
    /// Gets the video rotation angle.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance which used to get the video rotation angle.
    ///
    /// * `deviceDegree` - the current device rotation degree.
    ///
    /// * `imageRotation` - the [`Camera_ImageRotation`] result of video rotation angle.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_GetVideoRotation(
        videoOutput: *mut Camera_VideoOutput,
        deviceDegree: ::core::ffi::c_int,
        imageRotation: *mut Camera_ImageRotation,
    ) -> Camera_ErrorCode;
    /// Gets the video rotation angle without device degree.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance which used to get the video rotation angle.
    ///
    /// * `imageRotation` - the [`Camera_ImageRotation`] result of video rotation angle.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_VideoOutput_GetVideoRotationWithoutDeviceDegree(
        videoOutput: *mut Camera_VideoOutput,
        imageRotation: *mut Camera_ImageRotation,
    ) -> Camera_ErrorCode;
    /// Get supported video output frame rate list.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to deliver supported frame rate list.
    ///
    /// * `frameRateRange` - the supported [`Camera_FrameRateRange`] list to be filled if the method call succeeds.
    ///
    /// * `size` - the size of supported [`Camera_FrameRateRange`] list will be filled.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_GetSupportedFrameRates(
        videoOutput: *mut Camera_VideoOutput,
        frameRateRange: *mut *mut Camera_FrameRateRange,
        size: *mut u32,
    ) -> Camera_ErrorCode;
    /// Delete frame rate list.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to deliver supported frame rate list.
    ///
    /// * `frameRateRange` - the [`Camera_FrameRateRange`] list to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_DeleteFrameRates(
        videoOutput: *mut Camera_VideoOutput,
        frameRateRange: *mut Camera_FrameRateRange,
    ) -> Camera_ErrorCode;
    /// Set video output frame rate.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to be set frame rate.
    ///
    /// * `minFps` - the minimum to be set.
    ///
    /// * `maxFps` - the maximum to be set.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_SetFrameRate(
        videoOutput: *mut Camera_VideoOutput,
        minFps: i32,
        maxFps: i32,
    ) -> Camera_ErrorCode;
    /// Get active video output frame rate.
    ///
    /// # Arguments
    ///
    /// * `videoOutput` - the [`Camera_VideoOutput`] instance to deliver the active frame rate.
    ///
    /// * `frameRateRange` - the active [`Camera_FrameRateRange`] to be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_VideoOutput_GetActiveFrameRate(
        videoOutput: *mut Camera_VideoOutput,
        frameRateRange: *mut Camera_FrameRateRange,
    ) -> Camera_ErrorCode;
}
