// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::camera::*;
#[allow(unused_imports)]
use ohos_sys_opaque_types::OHNativeWindow;

/// Preview output object
///
/// A pointer can be created using [`Camera_PreviewOutput`] method.
///
///
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
pub struct Camera_PreviewOutput {
    _unused: [u8; 0],
}
/// Preview output frame start callback to be called in [`PreviewOutput_Callbacks`].
///
/// # Arguments
///
/// * `previewOutput` - the [`Camera_PreviewOutput`] which deliver the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PreviewOutput_OnFrameStart =
    ::core::option::Option<unsafe extern "C" fn(previewOutput: *mut Camera_PreviewOutput)>;
/// Preview output frame end callback to be called in [`PreviewOutput_Callbacks`].
///
/// # Arguments
///
/// * `previewOutput` - the [`Camera_PreviewOutput`] which deliver the callback.
///
/// * `frameCount` - the frame count which delivered by the callback.
///
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PreviewOutput_OnFrameEnd = ::core::option::Option<
    unsafe extern "C" fn(previewOutput: *mut Camera_PreviewOutput, frameCount: i32),
>;
/// Preview output error callback to be called in [`PreviewOutput_Callbacks`].
///
/// # Arguments
///
/// * `previewOutput` - the [`Camera_PreviewOutput`] which deliver the callback.
///
/// * `errorCode` - the [`Camera_ErrorCode`] of the preview output.
///
/// [`CAMERA_SERVICE_FATAL_ERROR`]
/// Available since API-level: 11
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
pub type OH_PreviewOutput_OnError = ::core::option::Option<
    unsafe extern "C" fn(previewOutput: *mut Camera_PreviewOutput, errorCode: Camera_ErrorCode),
>;
/// A listener for preview output.
///
/// [`OH_PreviewOutput_RegisterCallback`]
/// Available since API-level: 11
///
/// Version: 1.0
#[cfg(feature = "api-11")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PreviewOutput_Callbacks {
    /// Preview output frame start event.
    pub onFrameStart: OH_PreviewOutput_OnFrameStart,
    /// Preview output frame end event.
    pub onFrameEnd: OH_PreviewOutput_OnFrameEnd,
    /// Preview output error event.
    pub onError: OH_PreviewOutput_OnError,
}
extern "C" {
    /// Register preview output change event callback.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance.
    ///
    /// * `callback` - the [`PreviewOutput_Callbacks`] to be registered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PreviewOutput_RegisterCallback(
        previewOutput: *mut Camera_PreviewOutput,
        callback: *mut PreviewOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Unregister preview output change event callback.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance.
    ///
    /// * `callback` - the [`PreviewOutput_Callbacks`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PreviewOutput_UnregisterCallback(
        previewOutput: *mut Camera_PreviewOutput,
        callback: *mut PreviewOutput_Callbacks,
    ) -> Camera_ErrorCode;
    /// Start preview output.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to be started.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SESSION_NOT_CONFIG`] if the capture session not config.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PreviewOutput_Start(previewOutput: *mut Camera_PreviewOutput) -> Camera_ErrorCode;
    /// Stop preview output.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to be stoped.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PreviewOutput_Stop(previewOutput: *mut Camera_PreviewOutput) -> Camera_ErrorCode;
    /// Release preview output.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to be released.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 11
    #[cfg(feature = "api-11")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-11")))]
    pub fn OH_PreviewOutput_Release(previewOutput: *mut Camera_PreviewOutput) -> Camera_ErrorCode;
    /// Get active preview output profile.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to deliver active profile.
    ///
    /// * `profile` - the active [`Camera_Profile`] to be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_GetActiveProfile(
        previewOutput: *mut Camera_PreviewOutput,
        profile: *mut *mut Camera_Profile,
    ) -> Camera_ErrorCode;
    /// Delete preview profile instance.
    ///
    /// # Arguments
    ///
    /// * `profile` - the [`Camera_Profile`] instance to deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_DeleteProfile(profile: *mut Camera_Profile) -> Camera_ErrorCode;
    /// Gets the preview rotation angle.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance which used to get the preview rotation angle.
    ///
    /// * `displayRotation` - the current display rotation angle.
    ///
    /// * `imageRotation` - the [`Camera_ImageRotation`] result of preview rotation angle.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_GetPreviewRotation(
        previewOutput: *mut Camera_PreviewOutput,
        displayRotation: ::core::ffi::c_int,
        imageRotation: *mut Camera_ImageRotation,
    ) -> Camera_ErrorCode;
    /// Gets the preview rotation angle without display rotation.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance which used to get the preview rotation angle.
    ///
    /// * `imageRotation` - the [`Camera_ImageRotation`] result of preview rotation angle.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_PreviewOutput_GetPreviewRotationWithoutDisplayRotation(
        previewOutput: *mut Camera_PreviewOutput,
        imageRotation: *mut Camera_ImageRotation,
    ) -> Camera_ErrorCode;
    /// Sets the preview rotation angle.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance which used to set the preview rotation angle.
    ///
    /// * `previewRotation` - the [`Camera_ImageRotation`] of preview display rotation angle.
    ///
    /// * `isDisplayLocked` - TRUE means the display is locked.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_SetPreviewRotation(
        previewOutput: *mut Camera_PreviewOutput,
        previewRotation: Camera_ImageRotation,
        isDisplayLocked: bool,
    ) -> Camera_ErrorCode;
    /// Get supported preview output frame rate list.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to deliver supported frame rate list.
    ///
    /// * `frameRateRange` - the supported [`Camera_FrameRateRange`] list to be filled if the method call succeeds.
    ///
    /// * `size` - the size of supported [`Camera_FrameRateRange`] list will be filled.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_GetSupportedFrameRates(
        previewOutput: *mut Camera_PreviewOutput,
        frameRateRange: *mut *mut Camera_FrameRateRange,
        size: *mut u32,
    ) -> Camera_ErrorCode;
    /// Delete frame rate list.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to deliver supported frame rate list.
    ///
    /// * `frameRateRange` - the [`Camera_FrameRateRange`] list to be deleted.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_DeleteFrameRates(
        previewOutput: *mut Camera_PreviewOutput,
        frameRateRange: *mut Camera_FrameRateRange,
    ) -> Camera_ErrorCode;
    /// Set preview output frame rate.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to be set frame rate.
    ///
    /// * `minFps` - the minimum to be set.
    ///
    /// * `maxFps` - the maximum to be set.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_SetFrameRate(
        previewOutput: *mut Camera_PreviewOutput,
        minFps: i32,
        maxFps: i32,
    ) -> Camera_ErrorCode;
    /// Get active preview output frame rate.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance to deliver the active frame rate.
    ///
    /// * `frameRateRange` - the active [`Camera_FrameRateRange`] to be filled if the method call succeeds.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_PreviewOutput_GetActiveFrameRate(
        previewOutput: *mut Camera_PreviewOutput,
        frameRateRange: *mut Camera_FrameRateRange,
    ) -> Camera_ErrorCode;
    /// Check whether to support bandwidth compression.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance which used to check whether bandwidth compression supported.
    ///
    /// * `isSupported` - the result of whether bandwidth compression supported.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_PreviewOutput_IsBandwidthCompressionSupported(
        previewOutput: *mut Camera_PreviewOutput,
        isSupported: *mut bool,
    ) -> Camera_ErrorCode;
    /// Enable bandwidth compression or not.
    ///
    /// # Arguments
    ///
    /// * `previewOutput` - the [`Camera_PreviewOutput`] instance which used to enable bandwidth compression or not.
    ///
    /// * `enabled` - the flag indicates whether bandwidth compression is enabled.
    ///
    /// # Returns
    ///
    /// * [`#CAMERA_OK`] if the method call succeeds.
    /// [`#CAMERA_OPERATION_NOT_ALLOWED`] if operation not allowed.
    /// [`#CAMERA_INVALID_ARGUMENT`] if parameter missing or parameter type incorrect.
    /// [`#CAMERA_SESSION_NOT_CONFIG`] if the capture session not config.
    /// [`#CAMERA_SERVICE_FATAL_ERROR`] if camera service fatal error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_PreviewOutput_EnableBandwidthCompression(
        previewOutput: *mut Camera_PreviewOutput,
        enabled: bool,
    ) -> Camera_ErrorCode;
}
