// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#[allow(unused_imports)]
use crate::avmetadata::{OH_AVMetadata, OH_AVMetadataBuilder};
use crate::avplaybackstate::AVSession_PlaybackPosition;
#[allow(unused_imports)]
use crate::avplaybackstate::OH_AVSession_AVPlaybackState;
use crate::avsession_base::*;
use crate::avsession_errors::{AVSessionCallback_Result, AVSession_ErrCode};
#[allow(unused_imports)]
use crate::deviceinfo::{AVSession_DeviceInfo, AVSession_OutputDeviceInfo};

/// AVSession object
///
/// A pointer can be created using [`OH_AVSession_Create`] method.
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[repr(C)]
pub struct OH_AVSession {
    _unused: [u8; 0],
}
/// OH_AVCastController object
///
/// A pointer can be created using the [`OH_AVSession_CreateAVCastController`] method.
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVCastController {
    _unused: [u8; 0],
}
/// Declaring the callback struct for playback command
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVSessionCallback_OnCommand = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        command: AVSession_ControlCommand,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for forward command
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVSessionCallback_OnFastForward = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        seekTime: u32,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for rewind command
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVSessionCallback_OnRewind = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        seekTime: u32,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for seek command
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVSessionCallback_OnSeek = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        seekTime: u64,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for set loop mode command
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVSessionCallback_OnSetLoopMode = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        curLoopMode: AVSession_LoopMode,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for toggle favorite command
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
pub type OH_AVSessionCallback_OnToggleFavorite = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        assetId: *const ::core::ffi::c_char,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSessionCallback_Result,
>;
/// Declaring the callback struct for output device change
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVSessionCallback_OutputDeviceChange = ::core::option::Option<
    unsafe extern "C" fn(
        session: *mut OH_AVSession,
        state: AVSession_ConnectionState,
        outputDeviceInfo: *mut AVSession_OutputDeviceInfo,
    ) -> AVSessionCallback_Result,
>;
extern "C" {
    /// Request to create the avsession.
    ///
    /// # Arguments
    ///
    /// * `sessionType` - The session type to set
    ///
    /// * `sessionTag` - The session tag set by the application
    ///
    /// * `bundleName` - The bundle name to set
    ///
    /// * `abilityName` - The abilityName name to set
    ///
    /// * `avsession` - Pointer to a viriable to receive the OH_AVSession
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] If session already existed or internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]:
    /// 1. The param of sessionType is invalid.
    /// 2. The param of sessionTag is nullptr.
    /// 3. The param of bundleName is nullptr.
    /// 4. The param of abilityName is nullptr.
    /// 5. The param of avsession is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_Create(
        sessionType: AVSession_Type,
        sessionTag: *const ::core::ffi::c_char,
        bundleName: *const ::core::ffi::c_char,
        abilityName: *const ::core::ffi::c_char,
        avsession: *mut *mut OH_AVSession,
    ) -> AVSession_ErrCode;
    /// Request to destory the avsession.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`] The param of avsession is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_Destroy(avsession: *mut OH_AVSession) -> AVSession_ErrCode;
    /// Activate the avsession.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`] The param of avsession is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_Activate(avsession: *mut OH_AVSession) -> AVSession_ErrCode;
    /// Deactivate the avsession.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`] The param of avsession is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_Deactivate(avsession: *mut OH_AVSession) -> AVSession_ErrCode;
    /// Get session type.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `sessionType` - The returned session type
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is invalid.
    /// 2. The param of sessionType is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_GetSessionType(
        avsession: *mut OH_AVSession,
        sessionType: *mut AVSession_Type,
    ) -> AVSession_ErrCode;
    /// Get session id.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `sessionId` - The returned session id
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of sessionId is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_GetSessionId(
        avsession: *mut OH_AVSession,
        sessionId: *mut *const ::core::ffi::c_char,
    ) -> AVSession_ErrCode;
    /// Request to set av metadata.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `avmetadata` - The metadata to set
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of avmetadata is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_SetAVMetadata(
        avsession: *mut OH_AVSession,
        avmetadata: *mut OH_AVMetadata,
    ) -> AVSession_ErrCode;
    /// Request to set av playbackstate.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `playbackState` - The playbackState to set
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of playbackState is invalid.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_SetPlaybackState(
        avsession: *mut OH_AVSession,
        playbackState: AVSession_PlaybackState,
    ) -> AVSession_ErrCode;
    /// Request to set playback position.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `playbackPosition` - The playbackPosition to set
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of playbackPosition is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_SetPlaybackPosition(
        avsession: *mut OH_AVSession,
        playbackPosition: *mut AVSession_PlaybackPosition,
    ) -> AVSession_ErrCode;
    /// Request to set favorite state.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `favorite` - true means making the resource to be liked, false means dislike.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`] The param of avsession is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_SetFavorite(
        avsession: *mut OH_AVSession,
        favorite: bool,
    ) -> AVSession_ErrCode;
    /// Request to set loop mode.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `loopMode` - The loopmode to be set for playback.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of loopMode is invalid.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_SetLoopMode(
        avsession: *mut OH_AVSession,
        loopMode: AVSession_LoopMode,
    ) -> AVSession_ErrCode;
    /// Request to enable remote cast.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `enabled` - enable or disable remote cast
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_CODE_SESSION_NOT_EXIST`] session does not exist.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_SetRemoteCastEnabled(
        avsession: *mut OH_AVSession,
        enabled: bool,
    ) -> AVSession_ErrCode;
    /// Request to register command callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `command` - The control command type to be registered.
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnCommand`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_CODE_COMMAND_INVALID`] The command is invalid.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_RegisterCommandCallback(
        avsession: *mut OH_AVSession,
        command: AVSession_ControlCommand,
        callback: OH_AVSessionCallback_OnCommand,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister command callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `command` - The control command type to be unregistered.
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnCommand`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_CODE_COMMAND_INVALID`] The command is invalid.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_UnregisterCommandCallback(
        avsession: *mut OH_AVSession,
        command: AVSession_ControlCommand,
        callback: OH_AVSessionCallback_OnCommand,
    ) -> AVSession_ErrCode;
    /// Request to register fastforward callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnFastForward`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_RegisterForwardCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnFastForward,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister fastforward callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnFastForward`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_UnregisterForwardCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnFastForward,
    ) -> AVSession_ErrCode;
    /// Request to register rewind callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnRewind`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_RegisterRewindCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnRewind,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister rewind callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnRewind`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_UnregisterRewindCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnRewind,
    ) -> AVSession_ErrCode;
    /// Request to register seek callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnSeek`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_RegisterSeekCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnSeek,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister seek callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnSeek`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_UnregisterSeekCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnSeek,
    ) -> AVSession_ErrCode;
    /// Request to register set loopmode callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnSetLoopMode`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_RegisterSetLoopModeCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnSetLoopMode,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister set loopmode callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnSetLoopMode`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_UnregisterSetLoopModeCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnSetLoopMode,
    ) -> AVSession_ErrCode;
    /// Request to register toggle favorite callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnToggleFavorite`] to be registered.
    ///
    /// * `userData` - User data which is passed by user.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_RegisterToggleFavoriteCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnToggleFavorite,
        userData: *mut ::core::ffi::c_void,
    ) -> AVSession_ErrCode;
    /// Request to unregister toggle favorite callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OnToggleFavorite`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code：
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_AVSession_UnregisterToggleFavoriteCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OnToggleFavorite,
    ) -> AVSession_ErrCode;
    /// Request to register output device change callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OutputDeviceChange`] to be registered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_RegisterOutputDeviceChangeCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OutputDeviceChange,
    ) -> AVSession_ErrCode;
    /// Request to unregister output device change callback.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `callback` - the [`OH_AVSessionCallback_OutputDeviceChange`] to be unregistered.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of callback is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_UnregisterOutputDeviceChangeCallback(
        avsession: *mut OH_AVSession,
        callback: OH_AVSessionCallback_OutputDeviceChange,
    ) -> AVSession_ErrCode;
    /// Request to acquire an AVSession instance if already created.
    /// Call [`OH_AVSession_Destroy`] to release the OH_AVSession when it is not used anymore.
    ///
    /// # Arguments
    ///
    /// * `sessionTag` - The session tag set by the application
    ///
    /// * `bundleName` - The bundle name to set
    ///
    /// * `abilityName` - The abilityName name to set
    ///
    /// * `avsession` - Pointer to a viriable to receive the OH_AVSession
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_CODE_SESSION_NOT_EXIST`] If session is not existed.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]:
    /// 1. The param of sessionTag is invalid.
    /// 2. The param of bundleName is nullptr.
    /// 3. The param of abilityName is nullptr.
    /// 4. The param of avsession is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AcquireSession(
        sessionTag: *const ::core::ffi::c_char,
        bundleName: *const ::core::ffi::c_char,
        abilityName: *const ::core::ffi::c_char,
        avsession: *mut *mut OH_AVSession,
    ) -> AVSession_ErrCode;
    /// Create an AVCastController object.
    /// Call [`OH_AVCastController_Destroy`] to release the OH_AVCastController when it is not used anymore.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `avcastcontroller` - [`OH_AVCastController`] Pointer to a variable to receive the avcastcontroller
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_CODE_SESSION_NOT_EXIST`] The session does not exist.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of avcastcontroller is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_CreateAVCastController(
        avsession: *mut OH_AVSession,
        avcastcontroller: *mut *mut OH_AVCastController,
    ) -> AVSession_ErrCode;
    /// Request to stop current cast and disconnect device connection.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_CODE_SESSION_NOT_EXIST`] The session does not exist.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_StopCasting(avsession: *mut OH_AVSession) -> AVSession_ErrCode;
    /// Acquire current output device.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `outputDeviceInfo` - Pointer [`AVSession_OutputDeviceInfo`] to a variable to receive the OutputDeviceInfo
    /// Do not release the outputDeviceInfo pointer separately, instead call [`OH_AVSession_ReleaseOutputDevice`]
    /// to release the outputDeviceInfo when it is not used anymore.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_SERVICE_EXCEPTION`] Internal server error.
    /// [`AV_SESSION_ERR_CODE_SESSION_NOT_EXIST`] The session does not exist.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1. The param of avsession is nullptr.
    /// 2. The param of outputDeviceInfo is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_AcquireOutputDevice(
        avsession: *mut OH_AVSession,
        outputDeviceInfo: *mut *mut AVSession_OutputDeviceInfo,
    ) -> AVSession_ErrCode;
    /// Release outputDeviceInfo object.
    ///
    /// # Arguments
    ///
    /// * `avsession` - The avsession instance pointer
    ///
    /// * `outputDeviceInfo` - outputdeivce should be released.
    ///
    /// # Returns
    ///
    /// * Function result code:
    /// [`AV_SESSION_ERR_SUCCESS`] If the execution is successful.
    /// [`AV_SESSION_ERR_INVALID_PARAMETER`]
    /// 1.The param of avsession is nullptr;
    /// 2.The param of outputDeviceInfo is nullptr.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVSession_ReleaseOutputDevice(
        avsession: *mut OH_AVSession,
        outputDeviceInfo: *mut AVSession_OutputDeviceInfo,
    ) -> AVSession_ErrCode;
}
