// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
impl Wifi_ResultCode {
    /// The operation is successful.
    pub const SUCCESS: Wifi_ResultCode = Wifi_ResultCode(0);
    /// Permission verification failed. The application does not have the
    /// permission required to call the API.
    pub const PERMISSION_DENIED: Wifi_ResultCode = Wifi_ResultCode(201);
    /// Parameter error. Possible reasons: 1. The input parameter is a null pointer;
    ///
    /// 2. Parameter values exceed the defined range.
    pub const INVALID_PARAM: Wifi_ResultCode = Wifi_ResultCode(401);
    /// Capability not supported. Failed to call function due to limited device capabilities.
    pub const NOT_SUPPORTED: Wifi_ResultCode = Wifi_ResultCode(801);
    /// Operation failed.
    /// Possible reasons: Internal execution failed.
    pub const OPERATION_FAILED: Wifi_ResultCode = Wifi_ResultCode(2501000);
    /// Wi-Fi STA disabled.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub const STA_DISABLED: Wifi_ResultCode = Wifi_ResultCode(2501001);
}
#[repr(transparent)]
/// Enumerates the wifi result codes.
///
///
/// Available since API-level: 13
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Wifi_ResultCode(pub ::core::ffi::c_uint);
extern "C" {
    /// Check whether the wifi switch is enabled.
    ///
    /// # Arguments
    ///
    /// * `enabled` - - It is a boolean pointer used to receive wifi switch status values.
    ///
    /// Equal to true indicates that the wifi switch is turned on, false indicates that
    ///
    /// the wifi switch is turned off.
    ///
    /// The caller needs to pass in a non empty boolean pointer, otherwise an error will be returned.
    ///
    ///
    /// # Returns
    ///
    /// * wifi functions result code.
    ///
    /// For a detailed definition, please refer to [`Wifi_ResultCode`].
    ///
    /// [`WIFI_SUCCESS`] Successfully obtained the wifi switch status.
    ///
    /// [`WIFI_INVALID_PARAM`] The input parameter enabled is a null pointer.
    ///
    /// [`WIFI_OPERATION_FAILED`] Internal execution failed.
    ///
    ///
    /// Available since API-level: 13
    #[cfg(feature = "api-13")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
    pub fn OH_Wifi_IsWifiEnabled(enabled: *mut bool) -> Wifi_ResultCode;
    /// Get the device Mac address.
    ///
    /// # Arguments
    ///
    /// * `macAddr` - - The character array of device Mac address terminated using '
    /// * `macAddrLen` - - The size of the memory allocated for the macAddr character array.
    /// ohos.permission.GET_WIFI_LOCAL_MAC and ohos.permission.GET_WIFI_INFO.
    ///
    /// # Returns
    ///
    /// * wifi functions result code.
    /// For a detailed definition, please refer to [`Wifi_ResultCode`].
    /// [`WIFI_SUCCESS`] Successfully obtained the device Mac address.
    /// [`WIFI_PERMISSION_DENIED`] Permission denied.
    /// [`WIFI_NOT_SUPPORTED`] Capability not supported.
    /// [`WIFI_INVALID_PARAM`] The input parameter macAddr is a null pointer.
    /// [`WIFI_OPERATION_FAILED`] Internal execution failed.
    /// [`WIFI_STA_DISABLED`] Wi-Fi STA disabled.
    ///
    /// Available since API-level: 21
    #[cfg(feature = "api-21")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-21")))]
    pub fn OH_Wifi_GetDeviceMacAddress(
        macAddr: *mut ::core::ffi::c_char,
        macAddrLen: *mut ::core::ffi::c_uint,
    ) -> Wifi_ResultCode;
}
