// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::type_def::*;

extern "C" {
    /// Initializes a rwlock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// * `attr` - Indicates a pointer to the rwlock attribute.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is initialized;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_init(
        rwlock: *mut ffrt_rwlock_t,
        attr: *const ffrt_rwlockattr_t,
    ) -> ::core::ffi::c_int;
    /// Locks a write lock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is locked;
    /// returns <b>ffrt_error_inval</b> or blocks the calling thread otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_wrlock(rwlock: *mut ffrt_rwlock_t) -> ::core::ffi::c_int;
    /// Attempts to lock a write lock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is locked;
    /// returns <b>ffrt_error_inval</b> or <b>ffrt_error_busy</b> otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_trywrlock(rwlock: *mut ffrt_rwlock_t) -> ::core::ffi::c_int;
    /// Locks a read lock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is locked;
    /// returns <b>ffrt_error_inval</b> or blocks the calling thread otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_rdlock(rwlock: *mut ffrt_rwlock_t) -> ::core::ffi::c_int;
    /// Attempts to lock a read lock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is locked;
    /// returns <b>ffrt_error_inval</b> or <b>ffrt_error_busy</b> otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_tryrdlock(rwlock: *mut ffrt_rwlock_t) -> ::core::ffi::c_int;
    /// Unlocks a rwlock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is unlocked;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_unlock(rwlock: *mut ffrt_rwlock_t) -> ::core::ffi::c_int;
    /// Destroys a rwlock.
    ///
    /// # Arguments
    ///
    /// * `rwlock` - Indicates a pointer to the rwlock.
    ///
    /// # Returns
    ///
    /// * Returns <b>ffrt_success</b> if the rwlock is destroyed;
    /// returns <b>ffrt_error_inval</b> otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn ffrt_rwlock_destroy(rwlock: *mut ffrt_rwlock_t) -> ::core::ffi::c_int;
}
