// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
impl AVSession_ErrCode {
    /// The operation completed successfully.
    pub const AV_SESSION_ERR_SUCCESS: AVSession_ErrCode = AVSession_ErrCode(0);
    /// Invalid parameter。
    pub const AV_SESSION_ERR_INVALID_PARAMETER: AVSession_ErrCode = AVSession_ErrCode(401);
    /// Service exception.
    pub const AV_SESSION_ERR_SERVICE_EXCEPTION: AVSession_ErrCode = AVSession_ErrCode(6600101);
    /// The session does not exist.
    pub const AV_SESSION_ERR_CODE_SESSION_NOT_EXIST: AVSession_ErrCode = AVSession_ErrCode(6600102);
    /// Invalid session command.
    pub const AV_SESSION_ERR_CODE_COMMAND_INVALID: AVSession_ErrCode = AVSession_ErrCode(6600105);
    /// The session is not activated.
    pub const AV_SESSION_ERR_CODE_SESSION_INACTIVE: AVSession_ErrCode = AVSession_ErrCode(6600106);
    /// Too many commands or events.
    pub const AV_SESSION_ERR_CODE_MESSAGE_OVERLOAD: AVSession_ErrCode = AVSession_ErrCode(6600107);
    /// The remote connection is not established.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_REMOTE_CONNECTION_NOT_EXIST: AVSession_ErrCode =
        AVSession_ErrCode(6600109);
    /// The error code for cast control is unspecified.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_UNSPECIFIED: AVSession_ErrCode =
        AVSession_ErrCode(6611000);
    /// An unspecified error occurs in the remote player.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_REMOTE_ERROR: AVSession_ErrCode =
        AVSession_ErrCode(6611001);
    /// The playback position falls behind the live window.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_BEHIND_LIVE_WINDOW: AVSession_ErrCode =
        AVSession_ErrCode(6611002);
    /// The process of cast control times out.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_TIMEOUT: AVSession_ErrCode =
        AVSession_ErrCode(6611003);
    /// The runtime check failed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_RUNTIME_CHECK_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6611004);
    /// Cross-device data transmission is locked.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PLAYER_NOT_WORKING: AVSession_ErrCode =
        AVSession_ErrCode(6611100);
    /// The specified seek mode is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_SEEK_MODE_UNSUPPORTED: AVSession_ErrCode =
        AVSession_ErrCode(6611101);
    /// The position to seek to is out of the range of the media asset or the specified seek mode is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_ILLEGAL_SEEK_TARGET: AVSession_ErrCode =
        AVSession_ErrCode(6611102);
    /// The specified playback mode is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PLAY_MODE_UNSUPPORTED: AVSession_ErrCode =
        AVSession_ErrCode(6611103);
    /// The specified playback speed is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PLAY_SPEED_UNSUPPORTED: AVSession_ErrCode =
        AVSession_ErrCode(6611104);
    /// The action failed because either the media source device or the media sink device has been revoked.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DEVICE_MISSING: AVSession_ErrCode =
        AVSession_ErrCode(6611105);
    /// The parameter is invalid, for example, the url is illegal to play.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_INVALID_PARAM: AVSession_ErrCode =
        AVSession_ErrCode(6611106);
    /// Allocation of memory failed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_NO_MEMORY: AVSession_ErrCode =
        AVSession_ErrCode(6611107);
    /// Operation is not allowed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_OPERATION_NOT_ALLOWED: AVSession_ErrCode =
        AVSession_ErrCode(6611108);
    /// An unspecified input/output error occurs.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_UNSPECIFIED: AVSession_ErrCode =
        AVSession_ErrCode(6612000);
    /// Network connection failure.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_NETWORK_CONNECTION_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6612001);
    /// Network timeout.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_NETWORK_CONNECTION_TIMEOUT: AVSession_ErrCode =
        AVSession_ErrCode(6612002);
    /// Invalid "Content-Type" HTTP header.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_INVALID_HTTP_CONTENT_TYPE: AVSession_ErrCode =
        AVSession_ErrCode(6612003);
    /// The HTTP server returns an unexpected HTTP response status code.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_BAD_HTTP_STATUS: AVSession_ErrCode =
        AVSession_ErrCode(6612004);
    /// The file does not exist.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_FILE_NOT_FOUND: AVSession_ErrCode =
        AVSession_ErrCode(6612005);
    /// No permission is granted to perform the IO operation.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_NO_PERMISSION: AVSession_ErrCode =
        AVSession_ErrCode(6612006);
    /// Access to cleartext HTTP traffic is not allowed by the app's network security configuration.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_CLEARTEXT_NOT_PERMITTED: AVSession_ErrCode =
        AVSession_ErrCode(6612007);
    /// Reading data out of the data bound.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_READ_POSITION_OUT_OF_RANGE: AVSession_ErrCode =
        AVSession_ErrCode(6612008);
    /// The media does not contain any contents that can be played.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_NO_CONTENTS: AVSession_ErrCode =
        AVSession_ErrCode(6612100);
    /// The media cannot be read, for example, because of dust or scratches.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_READ_ERROR: AVSession_ErrCode =
        AVSession_ErrCode(6612101);
    /// This resource is already in use.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_CONTENT_BUSY: AVSession_ErrCode =
        AVSession_ErrCode(6612102);
    /// The content using the validity interval has expired.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_CONTENT_EXPIRED: AVSession_ErrCode =
        AVSession_ErrCode(6612103);
    /// Using the requested content to play is not allowed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_USE_FORBIDDEN: AVSession_ErrCode =
        AVSession_ErrCode(6612104);
    /// The use of the allowed content cannot be verified.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_NOT_VERIFIED: AVSession_ErrCode =
        AVSession_ErrCode(6612105);
    /// The number of times this content has been used as requested has reached the maximum allowed number of uses.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_EXHAUSTED_ALLOWED_USES: AVSession_ErrCode =
        AVSession_ErrCode(6612106);
    /// An error occurs when sending packet from source device to sink device.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_IO_NETWORK_PACKET_SENDING_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6612107);
    /// Unspecified error related to content parsing.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PARSING_UNSPECIFIED: AVSession_ErrCode =
        AVSession_ErrCode(6613000);
    /// Parsing error associated with media container format bit streams.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PARSING_CONTAINER_MALFORMED: AVSession_ErrCode =
        AVSession_ErrCode(6613001);
    /// Parsing error associated with the media manifest.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PARSING_MANIFEST_MALFORMED: AVSession_ErrCode =
        AVSession_ErrCode(6613002);
    /// An error occurs when attempting to extract a file with an unsupported media container format
    /// or an unsupported media container feature.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PARSING_CONTAINER_UNSUPPORTED: AVSession_ErrCode =
        AVSession_ErrCode(6613003);
    /// Unsupported feature in the media manifest.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_PARSING_MANIFEST_UNSUPPORTED: AVSession_ErrCode =
        AVSession_ErrCode(6613004);
    /// Unspecified decoding error.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DECODING_UNSPECIFIED: AVSession_ErrCode =
        AVSession_ErrCode(6614000);
    /// Decoder initialization failed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DECODING_INIT_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6614001);
    /// Decoder query failed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DECODING_QUERY_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6614002);
    /// Decoding the media samples failed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DECODING_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6614003);
    /// The format of the content to decode exceeds the capabilities of the device.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DECODING_FORMAT_EXCEEDS_CAPABILITIES:
        AVSession_ErrCode = AVSession_ErrCode(6614004);
    /// The format of the content to decode is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_DECODING_FORMAT_UNSUPPORTED: AVSession_ErrCode =
        AVSession_ErrCode(6614005);
    /// Unspecified errors related to the audio renderer.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_AUDIO_RENDERER_UNSPECIFIED: AVSession_ErrCode =
        AVSession_ErrCode(6615000);
    /// Initializing the audio renderer failed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_AUDIO_RENDERER_INIT_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6615001);
    /// The audio renderer fails to write data.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AV_SESSION_ERR_CODE_CAST_CONTROL_AUDIO_RENDERER_WRITE_FAILED: AVSession_ErrCode =
        AVSession_ErrCode(6615002);
}
#[repr(transparent)]
/// AVSession error code
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AVSession_ErrCode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
impl AVSessionCallback_Result {
    /// Result of avsession callabck is success.
    pub const AVSESSION_CALLBACK_RESULT_SUCCESS: AVSessionCallback_Result =
        AVSessionCallback_Result(0);
    /// Result of avsession callabck failed.
    pub const AVSESSION_CALLBACK_RESULT_FAILURE: AVSessionCallback_Result =
        AVSessionCallback_Result(-1);
}
#[repr(transparent)]
/// Defines enumeration of avsession callback result.
///
///
/// Available since API-level: 13
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AVSessionCallback_Result(pub ::core::ffi::c_int);
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
impl AVMetadata_Result {
    /// The call was successful.
    pub const AVMETADATA_SUCCESS: AVMetadata_Result = AVMetadata_Result(0);
    /// This means that the function was executed with an invalid input parameter.
    pub const AVMETADATA_ERROR_INVALID_PARAM: AVMetadata_Result = AVMetadata_Result(1);
    /// This means there is no memory left.
    pub const AVMETADATA_ERROR_NO_MEMORY: AVMetadata_Result = AVMetadata_Result(2);
}
#[repr(transparent)]
/// AVMetadata error code
///
///
/// Available since API-level: 13
///
/// Version: 1.0
#[cfg(feature = "api-13")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-13")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AVMetadata_Result(pub ::core::ffi::c_uint);
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
impl AVQueueItem_Result {
    /// The call was successful.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AVQUEUEITEM_SUCCESS: AVQueueItem_Result = AVQueueItem_Result(0);
    /// This means that the function was executed with an invalid input parameter.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AVQUEUEITEM_ERROR_INVALID_PARAM: AVQueueItem_Result = AVQueueItem_Result(1);
    /// This means there is no memory left.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub const AVQUEUEITEM_ERROR_NO_MEMORY: AVQueueItem_Result = AVQueueItem_Result(2);
}
#[repr(transparent)]
/// AVQUEUEITEM error code
///
///
/// Available since API-level: 23
///
/// Version: 1.0
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AVQueueItem_Result(pub ::core::ffi::c_uint);
